import type { ThreeReadsEdition } from '../types.js';

export const capitalGatePremiumEdition: ThreeReadsEdition = {
  id: 'wall-street-2026-07-18-capital-gate-premium',
  slug: '2026-07-18-capital-gate-premium',
  status: 'published',
  publishedAt: '2026-07-18',
  contentAsOf: '2026-07-18',
  title: '자본은 가장 좁은 관문에 프리미엄을 붙인다',
  centralQuestion: '정책·사모시장·AI 인프라의 좁은 관문이 실제 현금흐름보다 먼저 프리미엄을 받는다면, 무엇이 그 가격을 검증하거나 무너뜨리는가?',
  introduction: '브라질 PIX는 결제의 기본 관문이 되자 미국 통상정책의 표적이 됐고, 벤처자본은 비상장 성장의 후기 라운드에 집중되며, Etched는 AI 추론 병목을 풀겠다는 약속으로 양산 전 평가액을 끌어올리고 있습니다. 세 프리미엄을 검증하는 공통 기준은 거래량·회수·가동률입니다.',
  authoringTime: '2026-07-18 14:40 KST',
  factCheckedAt: '2026-07-18 14:40 KST',
  verification: {
    authoredBy: 'owner',
    verifiedBy: 'owner',
    verifiedAt: '2026-07-18T14:40:00+09:00',
    status: 'ownerVerified',
    note: '로그인된 원문, 공식 자료와 시장 기준을 사용자가 직접 교차확인한 원고를 편집했습니다.',
  },
  independentDisclosure: '주가해부실의 독자적 해설 · 주요 출처: The Wall Street Journal',
  methodology: {
    newsWindow: '2026-07-17 14:29 KST부터 2026-07-18 14:29 KST까지 로그인된 WSJ Latest Headlines의 최근 24시간 기사 15개를 확인했습니다.',
    duplicateCheck: '최근 14일 결과를 URL·기업·인물·산업·사건·핵심 메커니즘·통합 프레임으로 비교해 이미 사용한 주제를 제외했습니다.',
    candidateSelection: '정책·결제 인프라, 벤처·자본시장, AI 반도체로 분야를 분산하고 시장 중요도·구조적 인사이트·신규성·다양성 점수로 세 건을 선정했습니다.',
    factCheckSummary: [
      'PIX: WSJ 원문, USTR Section 301 최종조치와 브라질 중앙은행 통계를 교차검증했습니다.',
      'VC: WSJ 원문, Anthropic 공식 Series H 발표와 NVCA 2026 Yearbook을 교차검증했습니다.',
      'Etched: WSJ 원문, Etched 공식 제품 자료·보도자료와 같은 세션 시장 데이터를 교차검증했습니다.',
    ],
    correctedExpressions: [
      'PIX 하나 때문에 관세가 부과됐다고 하지 않고 PIX를 포함한 복수 쟁점이 근거가 됐다고 구분했습니다.',
      '벤처 지분의 장부상 가치를 실현수익으로 바꾸지 않았습니다.',
      'Etched의 200억달러 평가액과 10억달러 이상 고객계약을 확정 평가·인식 매출로 표현하지 않았습니다.',
    ],
    notYetFinal: [
      '브라질 보복조치와 추가 협상, PIX 규칙 변화',
      '비상장 보유지분의 IPO·세컨더리 매각과 LP 현금분배',
      'Etched 라운드 종결·고객검증·양산수율·매출인식·총마진',
    ],
    priceBasis: [
      'Visa·Mastercard·EWZ의 7월 17일 가격은 기사 발행 전 최신 미국시장 거래라 PIX 기사 반응으로 해석하지 않았습니다.',
      'Renaissance IPO ETF의 7월 17일 종가는 비상장 포트폴리오의 직접 가격이 아닙니다.',
      'NVIDIA·QQQ의 7월 17일 종가는 Etched 기사 발행 전 시장 배경이며 Etched의 직접 반응이 아닙니다.',
    ],
  },
  reads: [
    {
      id: 'pix-trade-policy-gate',
      order: 1,
      headline: 'PIX와 통상정책',
      source: {
        name: 'The Wall Street Journal',
        url: 'https://www.wsj.com/world/americas/trump-brazil-payment-system-pix-097bacaa',
        articleIdentifier: '097bacaa',
        publishedAt: '2026-07-17T22:00:00-04:00',
        accessedAt: '2026-07-18T14:40:00+09:00',
      },
      relatedCompanies: [],
      relatedCompanySlugs: [],
      relatedIndustries: ['결제 인프라', '통상정책'],
      whatHappened: '미국은 PIX를 포함한 브라질의 복수 무역·정책 관행을 근거로 일부 상품에 25% Section 301 관세를 확정했습니다. PIX는 1억7,000만 명 이상의 사용 경험과 2026년 1월 70억 건 이상의 거래를 가진 생활 인프라지만 관세의 유일한 원인은 아닙니다.',
      whyItMatters: '생활 결제의 기본 관문이 제품 경쟁을 넘어 국가 간 통상 협상의 대상이 됐습니다.',
      structuralMeaning: '결제망의 해자는 브랜드보다 거래 빈도, 기본 탑재, 정산 속도, 수수료와 규제 지위에서 생깁니다. 관문 프리미엄은 실제 거래량과 가맹점 비용, 네트워크 수익 변화로 검증돼야 합니다.',
      confirmedFacts: ['USTR는 2026년 7월 15일 일부 브라질산 상품에 25% 관세를 확정했습니다.', '브라질 중앙은행은 PIX 개인 사용자 1억7,000만 명 이상과 2026년 1월 70억 건 이상 거래를 집계했습니다.'],
      keyNumbers: ['25% Section 301 관세', '3,000개 안팎 품목', '연간 $11B 이상 수출', 'PIX 개인 사용자 +170M', '월 거래 +7B건'],
      marketReaction: 'Visa -1.77%, Mastercard -1.47%, EWZ -0.28%는 기사 발행 전 가격이며 해당 기사 하나의 반응으로 해석하지 않았습니다.',
      priceBasis: '2026-07-17 미국 정규장 이후 최신 거래 · 기사 발행 전',
      currentStage: '관세는 확정됐지만 브라질 보복 범위와 추가 협상, PIX 규칙 변경 여부는 미정입니다.',
      correctedWording: ['PIX 때문에 25% 관세가 아니라 PIX를 포함한 복수 쟁점을 근거로 한 관세입니다.'],
      interpretation: 'PIX가 글로벌 카드 네트워크의 브라질 수익을 얼마나 대체할지는 거래량·카드 결제량·수수료에서 확인해야 합니다.',
      notYetFinal: ['실제 관세 적용 품목별 영향', '브라질 보복조치', '양국 협상과 결제망 규칙 변화'],
      cashFlowTransmission: '낮은 수수료·의무 제공 → PIX 거래량 집중 → 카드 결제량·take rate 변화 → 네트워크 현금흐름과 통상비용 변화',
      counterScenario: '관세 협상 타결, 대상 품목 축소, 카드사의 부가서비스 차별화와 PIX·카드의 상호보완이 수익성을 지킬 수 있습니다.',
      factCheckStatus: 'checked',
      watchItems: ['PIX 월간 거래건수·금액', '카드 결제량과 take rate', '관세 적용액', '브라질 보복·협상 문서'],
      officialSources: [
        { id: 'ustr-brazil-section-301-2026', name: 'USTR · Section 301 Action on Brazil', url: 'https://ustr.gov/about/policy-offices/press-office/press-releases/2026/july/ustr-section-301-action-brazils-unreasonable-acts-policies-and-practices', publishedAt: '2026-07-15', accessedAt: '2026-07-18' },
        { id: 'bcb-pix-statistics', name: 'Banco Central do Brasil · Pix Statistics', url: 'https://www.bcb.gov.br/en/financialstability/pixstatistics', publishedAt: '2026-07-01', accessedAt: '2026-07-18' },
      ],
    },
    {
      id: 'venture-capital-liquidity-gate',
      order: 2,
      headline: 'VC의 회수 관문',
      source: {
        name: 'The Wall Street Journal',
        url: 'https://www.wsj.com/finance/venture-capital-anthropic-spark-yasmin-razavi-93dd6041',
        articleIdentifier: '93dd6041',
        publishedAt: '2026-07-17T21:00:00-04:00',
        accessedAt: '2026-07-18T14:40:00+09:00',
      },
      relatedCompanies: [],
      relatedCompanySlugs: [],
      relatedIndustries: ['벤처캐피털', '사모시장'],
      whatHappened: '비상장 장기화로 벤처투자는 초기 발굴보다 후기 집중·반복투자 쪽으로 이동하고 있습니다. NVCA는 2025년 미국 VC 투자액 3,200억달러 가운데 AI가 65.4%, 2,220억달러를 차지했다고 집계했습니다.',
      whyItMatters: '높은 사모 평가액은 IPO·세컨더리 매각과 LP 현금분배라는 좁은 회수 관문을 통과해야 실현수익이 됩니다.',
      structuralMeaning: '반복 후속투자는 승자의 희석을 방어하고 정보·관계 우위를 강화하지만 높은 진입가·낮은 경영통제·긴 회수기간을 감수합니다. 장부상 지분가치는 현금분배가 아닙니다.',
      confirmedFacts: ['Anthropic은 2026년 5월 $65B Series H를 마쳐 $965B post-money 평가액을 발표했습니다.', 'NVCA는 2025년 미국 VC 투자액을 $320B로 집계했습니다.'],
      keyNumbers: ['2025 미국 VC $320B', 'AI 비중 65.4%·$222B', '메가딜 3.2%가 총액 67%', '유니콘 859개', 'VC 지원 IPO 49개'],
      marketReaction: 'Renaissance IPO ETF $52.78(-0.72%)는 기사 발행 전 종가이고 비상장 포트폴리오의 직접 가격이 아닙니다.',
      priceBasis: '2026-07-17 미국 정규장 마감 · Anthropic $965B는 2026-05-28 확정 사모 post-money',
      currentStage: '일부 대형 펀딩은 완료됐지만 다수 지분은 아직 회수되지 않은 장부상 가치입니다.',
      correctedWording: ['약 $7B는 실현수익이 아니라 최근 평가액을 적용한 WSJ 추정 지분가치입니다.'],
      interpretation: '후기 집중투자가 전통 초기투자보다 높은 순수익률을 낼지는 회수할 때까지 확정할 수 없습니다.',
      notYetFinal: ['Anthropic·OpenAI 상장 시점', '락업 뒤 가격', '실제 매각과 LP 분배'],
      cashFlowTransmission: '비상장 장기화 → 후기 진입가격·후속투자 확대 → IPO·세컨더리 할인율 → 실제 매각과 LP 현금분배',
      counterScenario: 'AI 매출 둔화와 공모시장 할인이 후기 투자자의 수익률을 압축할 수 있습니다.',
      factCheckStatus: 'checked',
      watchItems: ['DPI·TVPI', '세컨더리 할인율', 'IPO 공모가 대비 종가', '락업과 희석', 'AI 기업 현금소진'],
      officialSources: [
        { id: 'anthropic-series-h-2026', name: 'Anthropic · Series H funding', url: 'https://www.anthropic.com/news/series-h', publishedAt: '2026-05-28', accessedAt: '2026-07-18' },
        { id: 'nvca-yearbook-2026', name: 'NVCA · 2026 Yearbook', url: 'https://nvca.org/2026-nvca-yearbook/', publishedAt: '2026-05-01', accessedAt: '2026-07-18' },
        { id: 'spacex-sec-fwp-2026', name: 'U.S. SEC · SpaceX free writing prospectus', url: 'https://www.sec.gov/Archives/edgar/data/1181412/000162828026040610/spacexfwp.htm', publishedAt: '2026-06-11', accessedAt: '2026-07-18' },
      ],
    },
    {
      id: 'etched-inference-premium-gate',
      order: 3,
      headline: 'Etched의 추론 프리미엄',
      source: {
        name: 'The Wall Street Journal',
        url: 'https://www.wsj.com/tech/ai/ai-chip-startup-etched-is-in-talks-for-20-billion-valuation-caf1787d',
        articleIdentifier: 'caf1787d',
        publishedAt: '2026-07-17T19:42:00-04:00',
        accessedAt: '2026-07-18T14:40:00+09:00',
      },
      relatedCompanies: [],
      relatedCompanySlugs: [],
      relatedIndustries: ['AI 반도체', '추론 인프라'],
      whatHappened: 'Etched는 TSMC N4P 기반 A0 실리콘과 10억달러 이상의 고객계약을 발표했지만 첫 랙 제품은 고객검증·양산준비 단계입니다. WSJ가 보도한 100억·200억달러 평가 라운드는 모두 종결 전입니다.',
      whyItMatters: 'AI 추론 병목을 풀겠다는 약속이 출하·매출보다 먼저 사모 평가액에 반영됐습니다.',
      structuralMeaning: 'AI 추론시장의 좁은 관문은 전력당 토큰, 지연시간, 메모리 대역폭, 양산 수율과 고객 배치입니다. 전문화 프리미엄은 반복 가능한 생산성과 소프트웨어 호환성으로 검증돼야 합니다.',
      confirmedFacts: ['Etched는 A0 실리콘과 TSMC N4P 기반 첫 랙 제품의 고객검증을 발표했습니다.', '회사는 누적 $800M 조달과 직전 $5B post-money, $1B 이상 고객계약을 발표했습니다.'],
      keyNumbers: ['협상 평가액 $20B', '별도 라운드 $10B', '직전 $5B', '누적 조달 $800M', '회사 발표 고객계약 +$1B'],
      marketReaction: 'Etched는 비상장사입니다. NVDA -2.28%, QQQ -1.49%는 기사 발행 전 시장 배경일 뿐 직접 반응이 아닙니다.',
      priceBasis: '2026-07-17 미국 정규장 마감 · $10B·$20B는 미종결 사모협상 값',
      currentStage: '작동 A0 칩과 고객검증·생산준비 단계이며 첫 랙 출하와 대규모 매출인식은 아직 검증 전입니다.',
      correctedWording: ['$20B 평가 확정이 아니라 협상 중입니다.', '$1B 매출이 아니라 회사 발표상 $1B 이상 고객계약입니다.'],
      interpretation: '전문 추론시스템이 GPU 생태계보다 실제 비용·성능 우위를 반복할지는 아직 확인되지 않았습니다.',
      notYetFinal: ['두 자금조달 종결', '독립 벤치마크', '양산수율', '고객 인수검사', '매출인식과 총마진'],
      cashFlowTransmission: '전문 추론설계 → 전력당 처리량·고객 원가 개선 → 계약 → 랙 출하·설치·가동률 → 반복 주문·매출·총마진',
      counterScenario: '모델 구조 변화, 소프트웨어 생태계 부족, N4P 수율·패키징·냉각 지연이 프리미엄을 낮출 수 있습니다.',
      factCheckStatus: 'checked',
      watchItems: ['라운드 종결평가액', '출하 랙 수', '전력당 토큰·지연시간', 'N4P 수율', '계약 취소조건', '소프트웨어 호환성'],
      officialSources: [
        { id: 'etched-frontier-inference', name: 'Etched · Frontier Inference Clusters', url: 'https://www.etched.com/', publishedAt: '2026-07-18', accessedAt: '2026-07-18' },
        { id: 'etched-working-chip-2026', name: 'Etched · Working chip and customer contracts release', url: 'https://www.globenewswire.com/news-release/2026/06/30/3319922/0/en/Etched-Emerges-From-Stealth-With-Working-Chip-800M-Raised-and-Over-1B-in-Customer-Contracts.html', publishedAt: '2026-06-30', accessedAt: '2026-07-18' },
      ],
    },
  ],
  commonThread: 'PIX는 결제의 기본 관문이 되면서 통상정책의 표적이 됐고, 대형 벤처펀드는 후기 라운드의 비상장 진입권에 자본을 집중하며, Etched는 AI 추론의 전력·지연시간 병목을 풀겠다는 약속으로 제품 양산 전에 프리미엄을 받습니다. 세 경우 모두 관문을 가졌다는 사실과 현금흐름을 만들었다는 사실은 다릅니다.',
  cashFlowTransmission: [
    'PIX: 낮은 수수료와 의무 제공이 거래량을 집중시키고 카드 결제량·take rate와 통상비용을 바꿉니다.',
    'VC: 비상장 장기화가 후기 진입가격과 후속투자를 높이고 IPO·세컨더리 할인과 LP 분배가 수익률을 결정합니다.',
    'Etched: 전문 추론설계가 전력당 처리량을 높여야 계약이 출하·가동률·매출·총마진으로 전환됩니다.',
  ],
  investorQuestions: [
    '관문을 통과하는 실제 양은 거래량·회수액·출하와 가동률로 얼마나 확인되는가?',
    '프리미엄을 유지하는 통상·희석·수율·전력·전환 비용은 얼마인가?',
    '이용자·장부가치·고객계약이 실제 수수료 수익·LP 분배·인식 매출과 총마진으로 바뀌는 비율은 얼마인가?',
  ],
  oneLineTakeaway: '관문을 장악한 프리미엄은 크지만, 거래량·회수·가동률로 검증되지 않은 가격은 아직 현금흐름이 아닙니다.',
  relatedCompanySlugs: [],
  relatedIndustries: ['결제 인프라', '벤처캐피털', 'AI 반도체'],
  relatedStockDissectionIds: [],
  analytics: {
    content_id: 'wall-street-2026-07-18-capital-gate-premium',
    campaign_id: 'wall-street-2026-07-18-capital-gate-premium',
    recommended_utm: { source: 'instagram', medium: 'social', campaign: 'wall-street-2026-07-18-capital-gate-premium', content: 'profile-link' },
  },
  disclaimer: '본 콘텐츠는 주가해부실의 독자적 분석이며 The Wall Street Journal 또는 Dow Jones와 제휴·후원 관계가 없습니다. 투자 권유가 아닌 정보 제공 목적의 자료입니다.',
};

export default capitalGatePremiumEdition;
