import type { ThreeReadsEdition } from '../types.js';

export const switchingCostsEdition: ThreeReadsEdition = {
  id: 'wall-street-2026-07-25-switching-costs',
  slug: '2026-07-25-switching-costs',
  status: 'published',
  publishedAt: '2026-07-25',
  contentAsOf: '2026-07-25',
  title: '비용을 낮추는 힘은 대체 가능성에서 나온다',
  centralQuestion: '공급·거래·모델의 대체 가능성이 커질 때 누가 가격을 낮추고, 누가 전환비용과 지연비용을 떠안는가?',
  introduction: 'Apple의 메모리 조달, Paramount–Warner Bros. 합병 지연, 기업의 멀티모델 AI 전환을 하나의 질문으로 읽었습니다. 대안의 명목가격이 아니라 실제 전환비용을 뺀 순가치가 협상력과 현금흐름을 결정합니다.',
  authoringTime: '2026-07-25 12:50 KST',
  factCheckedAt: '2026-07-25 12:45 KST',
  verification: {
    authoredBy: 'owner',
    verifiedBy: 'owner',
    verifiedAt: '2026-07-25T12:45:00+09:00',
    status: 'ownerVerified',
    note: '로그인된 WSJ 원문과 Micron·미 국방부·California DOJ·미 연방 DOJ·SEC·Cursor·OpenAI·NVIDIA 자료 및 동일 세션 시장 데이터를 교차확인했습니다.',
  },
  independentDisclosure: '주가해부실의 독자적 분석이며 The Wall Street Journal 또는 Dow Jones와 제휴·후원 관계가 없습니다.',
  methodology: {
    newsWindow: '2026년 7월 24일 미국 정규장 종료 전후 공개된 WSJ 원문 세 건을 2026년 7월 25일 확인했습니다.',
    duplicateCheck: '최근 14일 edition의 URL·사건·메커니즘을 비교해 중복되지 않는 공급·거래·모델 대체 가능성 주제를 선정했습니다.',
    candidateSelection: '가격보다 실제 전환 가능성과 전환비용이 현금흐름에 미치는 영향을 설명하는 세 사건을 선택했습니다.',
    factCheckSummary: [
      'Apple: 중국 판매 제품의 메모리 사용 허용 요청과 Micron 반대, 미국 투자계획과 1260H 자료를 분리했습니다.',
      'Paramount–WBD: 810억달러 지분가치와 1,100억달러 기업가치, 법원 합의와 계약상 날짜를 구분했습니다.',
      '기업 AI: 특정 코딩 실험·개별 계약 사례를 산업 전체 절감률로 일반화하지 않았습니다.',
    ],
    correctedExpressions: [
      '중국산 메모리가 승인됐다고 하지 않고 중국 판매 제품에 대한 사용 허용 요청으로 표시했습니다.',
      'Paramount가 합병을 포기했거나 2027년 6월 완료가 확정됐다고 표현하지 않았습니다.',
      '특정 실험의 비용 차이를 모든 기업의 보편 절감률로 바꾸지 않았습니다.',
    ],
    notYetFinal: [
      '중국 메모리 허용 여부·적용 범위·Apple 인증과 실제 계약',
      'Paramount–WBD 본안 판결·최종 종결·남은 승인과 실제 시너지',
      '멀티모델 규제·무료 크레딧 종료 뒤 유지율·장기 품질·보안 비용',
    ],
    priceBasis: [
      'AAPL·MU, PSKY·WBD, QQQ 가격은 모두 2026년 7월 24일 미국 정규장 종가입니다.',
      '세 기사 모두 정규장 종료 뒤 최초 발행 또는 최종 업데이트돼 당일 주가를 직접 반응으로 단정하지 않습니다.',
    ],
  },
  reads: [
    {
      id: 'apple-memory-switching-cost',
      order: 1,
      headline: 'Apple의 메모리 선택권이 미국 산업정책과 충돌했다',
      source: {
        name: 'The Wall Street Journal',
        url: 'https://www.wsj.com/tech/trump-apple-micron-china-chips-784bbd3d',
        articleIdentifier: '784bbd3d',
        publishedAt: '2026-07-25T01:00:00Z',
        updatedAt: '2026-07-25T01:39:00Z',
        accessedAt: '2026-07-25T12:45:00+09:00',
      },
      relatedCompanies: ['Apple', 'Micron Technology', 'CXMT', 'YMTC'],
      relatedCompanySlugs: [],
      relatedIndustries: ['메모리 반도체', '미국 산업정책'],
      whatHappened: 'Apple은 중국에서 판매하는 기기에 CXMT와 YMTC 메모리를 쓸 수 있도록 허용을 요청하고 있으며 Micron은 국내 산업 훼손 가능성을 이유로 반대하고 있습니다.',
      whyItMatters: '허용되는 공급사가 늘면 입찰 경쟁과 물량 배분 협상력이 회복될 수 있지만 정책 허용·품질 인증·수율·납기와 계약을 통과해야 원가 절감이 실현됩니다.',
      structuralMeaning: '대체 공급자의 존재가 구매자의 협상력을 만들지만 전환비용이 절감 가능한 단가보다 크면 가격 결정력은 쉽게 이동하지 않습니다.',
      confirmedFacts: ['Apple과 Micron이 상반된 입장으로 미국 행정부를 설득 중입니다.', 'Micron은 2035년까지 미국 투자계획을 $250B 이상으로 확대했습니다.', '2024년 미 국방부 1260H 목록에는 YMTC가 명시됐습니다.'],
      keyNumbers: ['기사상 메모리 가격 약 4배', 'Apple 주장상 Micron 매출총이익률 80% 이상', 'Micron 미국 투자 $250B 이상'],
      marketReaction: 'AAPL $333.02 +3.57%, MU $920.95 -6.90%였지만 기사 발행 전 정규장 움직임이므로 직접 반응으로 해석하지 않습니다.',
      priceBasis: '2026-07-24 미국 정규장 종가 · 기사 최초 발행은 장 종료 뒤',
      currentStage: '행정부 대상 로비와 정책 검토 단계입니다.',
      correctedWording: ['중국산 메모리 승인 대신 중국 판매 제품에 대한 사용 허용 요청으로 표현합니다.', '미국 판매 제품의 즉시 탑재로 확장하지 않습니다.'],
      interpretation: '공급사 증가가 Apple 원가와 Micron 마진에 미칠 크기는 정책 범위·인증·제품 믹스에 달렸습니다.',
      notYetFinal: ['허용 여부와 적용 지역·제품', 'Apple 공급사 인증', '실제 공급계약과 절감액'],
      cashFlowTransmission: '허용 공급사 증가 → 입찰 경쟁 강화 → 조달단가 하락 가능성 → 기기 원가와 총마진 영향',
      counterScenario: '허용이 거부되거나 중국 업체가 품질·수율·납기 조건을 충족하지 못하면 대체 가능성이 현금흐름으로 이어지지 않습니다.',
      factCheckStatus: 'checked',
      watchItems: ['행정부 최종 결정', 'Apple 공급사 인증', 'DRAM·NAND 계약가격', 'Micron 제품 믹스와 투자 집행'],
      officialSources: [
        { id: 'micron-us-investment-2026', name: 'Micron · U.S. investment announcement', url: 'https://investors.micron.com/news-releases/news-release-details/micron-accelerates-us-investments-pours-first-concrete-new-york', publishedAt: '2026-07-09', accessedAt: '2026-07-25' },
        { id: 'dod-1260h-2024', name: 'U.S. Department of Defense · 1260H List', url: 'https://media.defense.gov/2024/Jan/31/2003384819/-1/-1/0/1260H-LIST.PDF', publishedAt: '2024-01-31', accessedAt: '2026-07-25' },
      ],
    },
    {
      id: 'paramount-wbd-delay-cost',
      order: 2,
      headline: 'Paramount–Warner Bros. 합병은 법정에서 시간이 비용으로 바뀌었다',
      source: {
        name: 'The Wall Street Journal',
        url: 'https://www.wsj.com/business/media/paramount-agrees-to-pause-its-warner-bros-merger-88ae1de1',
        articleIdentifier: '88ae1de1',
        publishedAt: '2026-07-24T23:57:00Z',
        updatedAt: '2026-07-25T02:21:00Z',
        accessedAt: '2026-07-25T12:45:00+09:00',
      },
      relatedCompanies: ['Paramount Skydance', 'Warner Bros. Discovery'],
      relatedCompanySlugs: [],
      relatedIndustries: ['미디어', 'M&A'],
      whatHappened: 'Paramount Skydance는 법적 다툼이 해결되거나 2027년 6월 1일이 될 때까지 Warner Bros. Discovery 인수를 진행하지 않기로 주 정부 측과 합의했습니다.',
      whyItMatters: '거래 종결이 늦어질수록 ticking fee·자금조달 유지비·통합 지연과 실행 분산이 쌓여 예상 시너지의 현재가치를 낮출 수 있습니다.',
      structuralMeaning: 'M&A에서 법원과 규제는 대체 불가능한 관문이며 종결을 선택하지 못하는 시간이 직접적인 현금비용이 됩니다.',
      confirmedFacts: ['본안 판단 후 5일 또는 2027년 6월 1일 중 빠른 시점까지 종결이 중단됩니다.', '지분가치는 약 $81B, 부채 포함 기업가치는 $110B입니다.', '2026년 9월 30일 뒤 분기당 주당 최대 $0.25 ticking fee가 발생합니다.'],
      keyNumbers: ['$81B 지분가치', '$110B 기업가치', '분기당 주당 최대 $0.25 ticking fee', '$7B 규제 종료 수수료'],
      marketReaction: 'PSKY $8.21 -3.47%, WBD $25.77 -0.69%였으나 합의와 기사 업데이트가 장 후반·종료 뒤여서 단일 뉴스 반응으로 단정하지 않습니다.',
      priceBasis: '2026-07-24 미국 정규장 종가 · 최종 기사 업데이트는 장 종료 뒤',
      currentStage: '계약 체결 후 규제·법원 심사 중이며 자발적 종결 중단 합의가 적용됩니다.',
      correctedWording: ['합병 포기나 2027년 6월 완료 확정으로 표현하지 않습니다.', '$81B와 $110B는 지분가치와 기업가치의 기준 차이입니다.'],
      interpretation: '지연비용이 예상 시너지와 거래 성공확률을 얼마나 낮출지는 본안 일정과 자금조달 조건에 달렸습니다.',
      notYetFinal: ['본안 판결', '최종 종결과 남은 승인', '실제 시너지와 자금조달비용'],
      cashFlowTransmission: '법적 종결 제한 → 거래기간 연장 → ticking fee·자금조달비용·통합 지연 → 예상 시너지 현재가치 변화',
      counterScenario: '법원이 신속히 회사 측 손을 들어주거나 합의가 이뤄지면 지연기간과 비용이 줄 수 있습니다.',
      factCheckStatus: 'checked',
      watchItems: ['법원 일정', '9월 30일 이후 ticking fee', '남은 승인', '자금조달 비용', 'WBD 독립 실적'],
      officialSources: [
        { id: 'california-doj-paramount-wbd-2026', name: 'California DOJ · Halting agreement', url: 'https://oag.ca.gov/news/press-releases/attorney-general-bonta-secures-deal-halting-warner-bros-paramount-merger-until', publishedAt: '2026-07-24', accessedAt: '2026-07-25' },
        { id: 'us-doj-paramount-wbd-2026', name: 'U.S. DOJ · Investigation closing statement', url: 'https://www.justice.gov/opa/pr/statement-department-justice-antitrust-division-closing-its-investigation-merger-paramount', publishedAt: '2026-06-12', accessedAt: '2026-07-25' },
        { id: 'paramount-wbd-8k-2026', name: 'Paramount · WBD merger Form 8-K', url: 'https://www.sec.gov/Archives/edgar/data/2041610/000110465926021911/tm2533570d75_8k.htm', publishedAt: '2026-02-27', accessedAt: '2026-07-25' },
      ],
    },
    {
      id: 'enterprise-ai-routing-cost',
      order: 3,
      headline: '기업 AI 구매가 ‘최고 모델 한 개’에서 ‘업무별 라우팅’으로 이동했다',
      source: {
        name: 'The Wall Street Journal',
        url: 'https://www.wsj.com/business/china-us-ai-model-costs-53a12e96',
        articleIdentifier: '53a12e96',
        publishedAt: '2026-07-25T00:30:00Z',
        updatedAt: '2026-07-25T00:35:00Z',
        accessedAt: '2026-07-25T12:45:00+09:00',
      },
      relatedCompanies: ['Cursor', 'OpenAI', 'Anthropic', 'Pylon', 'Telnyx'],
      relatedCompanySlugs: [],
      relatedIndustries: ['기업 AI', '모델 라우팅'],
      whatHappened: '기업들은 단일 최상위 모델 대신 업무 난도·정확도·지연시간·보안·가격에 따라 여러 모델을 조합하는 구조를 도입하고 있습니다.',
      whyItMatters: '고가 추론을 필요한 순간에만 사용하면 단가는 낮아질 수 있지만 평가·보안·재작업·자체 인프라를 포함한 업무당 완결비용으로 검증해야 합니다.',
      structuralMeaning: '모델 대체 가능성은 공급자의 단가와 락인에 압력을 주는 동시에 라우팅·평가·보안 계층을 새로운 통제 지점으로 만듭니다.',
      confirmedFacts: ['Cursor의 특정 실험에서 혼합 구성과 GPT-5.5 단독 구성의 비용 차이가 확인됐습니다.', '복수 모델 라우팅을 도입하는 기업 사례가 늘고 있습니다.', '공급자는 계층형 가격과 무료 토큰으로 사용량을 확보하고 있습니다.'],
      keyNumbers: ['Cursor 혼합 구성 $1,339', 'GPT-5.5 단독 $10,565', 'OpenAI Sol·Terra·Luna 입력/출력 $5/30·$2.5/15·$1/6 per 1M tokens'],
      marketReaction: 'QQQ $684.23 -1.10%였지만 기사 발행 전 정규장 움직임이므로 모델 가격 경쟁의 직접 반응이 아닙니다.',
      priceBasis: '2026-07-24 미국 정규장 종가 · 기사 최초 발행은 장 종료 뒤',
      currentStage: '기업별 실험과 초기 운영 전환이 진행 중입니다.',
      correctedWording: ['특정 실험의 비용 차이를 산업 전체 절감률로 일반화하지 않습니다.', '오픈·중국계 모델이 항상 더 안전하거나 총비용이 낮다고 하지 않습니다.'],
      interpretation: '장기 마진과 고객 락인은 토큰 가격보다 실제 모델별 사용량과 업무당 완결비용에서 드러납니다.',
      notYetFinal: ['중국계·오픈 모델 규제', '무료 크레딧 종료 뒤 유지율', '장기 품질·보안·운영 비용'],
      cashFlowTransmission: '사용 가능 모델 증가 → 업무별 모델 라우팅 → 고가 추론 사용량 축소 → 업무당 AI 비용 변화',
      counterScenario: '저가 모델의 오류와 재작업·법적 위험·운영 복잡성이 절감액을 넘으면 총비용은 오를 수 있습니다.',
      factCheckStatus: 'checked',
      watchItems: ['업무당 완결비용', '모델별 사용량 믹스', '무료 크레딧 종료 뒤 유지율', '라우터 채택', '데이터 주권 규정'],
      officialSources: [
        { id: 'cursor-agent-swarm-economics-2026', name: 'Cursor · Agent swarms and the new model economics', url: 'https://cursor.com/blog/agent-swarm-model-economics', publishedAt: '2026-07-20', accessedAt: '2026-07-25' },
        { id: 'openai-gpt-5-6-pricing-2026', name: 'OpenAI · GPT-5.6', url: 'https://openai.com/index/gpt-5-6/', publishedAt: '2026-07-09', accessedAt: '2026-07-25' },
        { id: 'nvidia-open-weights-letter-2026', name: 'Open Weights and American AI Leadership', url: 'https://images.nvidia.com/pdf/Open-Weights-and-American-AI-Leadership.pdf', publishedAt: '2026-07-24', accessedAt: '2026-07-25' },
      ],
    },
  ],
  commonThread: 'Apple은 잠재적 대체 공급사로 조달 협상력을 높이려 하고, Paramount–WBD는 대체 불가능한 법원 관문 때문에 지연비용을 부담하며, 기업 AI 고객은 모델을 업무별로 교체해 단일 공급자의 락인을 낮춥니다. 대체안이 계약·인증·배포로 실행되고 절감액이 전환비용을 넘어야 현금흐름이 개선됩니다.',
  cashFlowTransmission: [
    '허용 공급사 증가 → 입찰 경쟁 강화 → 메모리 조달단가 하락 가능성 → 기기 원가와 총마진 영향',
    '법적 종결 제한 → 거래기간 연장 → ticking fee·자금조달비용·통합 지연 → 예상 시너지 현재가치 변화',
    '사용 가능 모델 증가 → 업무별 라우팅 → 고가 추론 사용량 축소 → 업무당 AI 비용 변화',
  ],
  investorQuestions: [
    '선택지가 발표나 로비를 넘어 인증·계약·실제 사용으로 전환되는가?',
    '절감되는 단가가 품질검증·규제·보안·자금조달을 포함한 전환비용보다 큰가?',
    '대체 가능성 확대 뒤 공급자의 매출총이익률·고객 유지율·자본투자 계획은 어떻게 바뀌는가?',
  ],
  oneLineTakeaway: '싸진 가격보다 먼저 볼 것은 실제로 갈아탈 수 있는 선택지와 그 전환비용이다.',
  relatedCompanySlugs: [],
  relatedIndustries: ['메모리 반도체', '미디어 M&A', '기업 AI', '모델 라우팅'],
  relatedStockDissectionIds: [],
  analytics: {
    content_id: 'wall-street-2026-07-25-switching-costs',
    campaign_id: 'wall-street-2026-07-25-switching-costs',
    recommended_utm: { source: 'instagram', medium: 'social', campaign: 'wall-street-2026-07-25-switching-costs', content: 'profile-link' },
  },
  disclaimer: '본 콘텐츠는 주가해부실의 독자적 분석이며 The Wall Street Journal 또는 Dow Jones와 제휴·후원 관계가 없습니다. 투자 권유가 아닌 정보 제공 목적의 자료입니다.',
};

export default switchingCostsEdition;
