import type { ThreeReadsEdition } from '../types.js';

export const standardsSetPriceEdition: ThreeReadsEdition = {
  id: 'three-reads-2026-07-17-standards-set-price',
  slug: '2026-07-17-standards-set-price',
  status: 'published',
  publishedAt: '2026-07-17',
  contentAsOf: '2026-07-17',
  title: '먼저 고정한 표준이 가격을 정한다',
  centralQuestion: '누가 자본·브랜드·코드를 시장의 기준점으로 먼저 고정해 다음 가격과 협상력을 가져가는가?',
  introduction: '희토류 공급망, Burberry의 브랜드 회복, Kimi K3의 모델 경쟁을 계약과 전환율이라는 하나의 질문으로 연결합니다.',
  authoringTime: '2026-07-17 16:55 KST',
  factCheckedAt: '2026-07-17 16:55 KST',
  verification: {
    authoredBy: 'owner',
    verifiedBy: 'owner',
    verifiedAt: '2026-07-17T16:55:00+09:00',
    status: 'ownerVerified',
    note: '로그인된 원문과 공식 자료를 사용자가 직접 교차확인한 원고를 편집했습니다.',
  },
  independentDisclosure: '주가해부실의 독자적 해설 · 주요 출처: The Wall Street Journal',
  methodology: {
    newsWindow: '2026-07-16 16:46 KST부터 2026-07-17 16:46 KST까지 로그인된 WSJ Latest Headlines와 주요 섹션의 최근 24시간 기사를 확인했습니다.',
    duplicateCheck: '최근 14일 결과를 URL·기업·산업·사건·핵심 메커니즘·통합 프레임으로 비교해 이미 사용한 주제는 제외했습니다.',
    candidateSelection: '후보 15개를 시장 중요도, 구조적 인사이트, 신규성, 다양성으로 평가해 희토류, Burberry, Moonshot AI 세 건을 선정했습니다.',
    factCheckSummary: [
      '희토류: WSJ 원문, EU 집행위원회, 미국 국방부, USA Rare Earth 공시를 교차검증했습니다.',
      'Burberry: WSJ 원문, 회사 공식 RNS·1분기 자료와 컨센서스를 교차검증했습니다.',
      'Kimi K3: WSJ 원문, Kimi 공식 기술 블로그와 API 가격 페이지를 교차검증했습니다.',
    ],
    correctedExpressions: [
      '희토류 460억 달러는 단일 연방예산이 아니라 IFRI가 여러 정책수단을 합산한 배정액으로 표현했습니다.',
      'Burberry는 모든 지역이 아니라 모든 제품 부문이 성장했다고 구분했습니다.',
      'Kimi K3는 완전 오픈소스 출시가 아니라 서비스 출시와 전체 가중치 공개 예정으로 구분했습니다.',
    ],
    notYetFinal: [
      '희토류 프로젝트의 금융종결·인허가·상업생산과 오프테이크 이행',
      'Burberry FY27 연간 실적·마진 확대 폭과 신규 고객의 재구매',
      'Kimi K3 전체 가중치·기술보고서·독립 벤치마크와 투자라운드 종결',
    ],
    priceBasis: [
      'USA Rare Earth $15.91는 2026-07-17 00:15 UTC 미국 시간외이며 기사 발행 전 가격이라 기사 반응으로 해석하지 않았습니다.',
      'Burberry +2.33%는 2026-07-17 약 08:50 BST 런던 정규장 초반 장중 수치입니다.',
      'Moonshot AI는 비상장사이며 Kimi K3 출시만의 독립적인 공개시장 가격은 없습니다.',
    ],
  },
  reads: [
    {
      id: 'rare-earth-supply-race',
      order: 1,
      headline: '미국·유럽의 희토류 확보 경쟁',
      source: {
        name: 'The Wall Street Journal',
        url: 'https://www.wsj.com/world/europe/the-u-s-is-trampling-allies-in-the-global-hunt-for-rare-earths-82371d13',
        publishedAt: '2026-07-16T23:00:00-04:00',
        accessedAt: '2026-07-17T16:55:00+09:00',
      },
      relatedCompanies: ['USA Rare Earth', 'Pensana', 'Serra Verde'],
      relatedCompanySlugs: [],
      relatedIndustries: ['핵심광물', '희토류 공급망'],
      whatHappened: '미국과 유럽은 중국에 집중된 희토류·핵심광물 공급망을 분산하려 하지만, 미국은 정부금융·장기 구매계약·해외 프로젝트 투자로 미래 생산량을 더 빠르게 묶고 있습니다. IFRI 분석을 인용한 원고에서 미국의 2021년 3월~2026년 2월 배정액은 약 460억 달러로 같은 기간 EU의 약 8배입니다. Pensana 금융 협상, Serra Verde의 장기 오프테이크와 USA Rare Earth 인수 계약은 자금과 물량을 함께 고정하는 사례입니다.',
      whyItMatters: '정부금융과 장기 오프테이크가 미래 생산량을 먼저 묶습니다.',
      structuralMeaning: '희토류의 협상력은 매장량만이 아니라 금융·허가·정제·인증·오프테이크가 하나의 계약으로 묶이는 순간 생깁니다. 가격 하한과 장기 수요가 자본비용을 낮추고, 단가·물량·가동률이 현금흐름을 결정합니다.',
      confirmedFacts: ['EU는 2030년 단일 제3국 의존도를 전략 원자재별 65% 이하로 낮추는 목표를 두고 있습니다.', '미국 국방부는 2027년 방산용 mine-to-magnet 공급망 목표를 공개했습니다.'],
      companyOrInstitutionOutlook: ['RESourceEU는 12개월간 30억 유로 투입을 제시했습니다.', '여러 프로젝트는 금융종결·인허가·상업생산 단계가 남아 있습니다.'],
      keyNumbers: ['IFRI 집계 약 $46B·EU의 약 8배', 'RESourceEU €3B', 'Pensana 최대 $160M 협상', 'Serra Verde 금융 $565M', 'USA Rare Earth 인수가 약 $2.8B'],
      marketReaction: '기사 발행은 미국 정규장과 시간외 시세 이후였습니다. USAR 최신 확인치 $15.91·전일 대비 약 -8.17%는 기사 반응으로 해석하지 않았습니다.',
      priceBasis: '2026-07-17 00:15 UTC, 미국 시간외. 기사 발행 전 가격입니다.',
      currentStage: '일부 정책·계약은 확정됐지만 여러 광산·정제 프로젝트와 인수는 건설·승인·금융종결 단계가 남아 있습니다.',
      correctedWording: ['460억 달러는 확정된 단일 연방예산이 아니라 IFRI가 5년간 여러 수단을 합산한 배정액입니다.', '미국의 물량 선점이 곧바로 유럽의 공급 불능을 뜻하지는 않습니다.'],
      interpretation: '자금 격차가 실제 생산량·정제능력·유럽 공급 부족으로 이어질지는 프로젝트 실행률에 달려 있습니다.',
      notYetFinal: ['USA Rare Earth의 Serra Verde 인수 종결', 'Pensana 금융', '상업생산 일정과 실제 오프테이크 이행'],
      cashFlowTransmission: '정책자금·가격 하한·오프테이크 → 낮아진 자본비용 → 건설·정제 → 장기 물량·단가·가동률 → 현금흐름',
      counterScenario: '신규 공급 확대와 재활용, 미·EU 공동구매가 병목을 완화할 수 있습니다.',
      factCheckStatus: 'checked',
      watchItems: ['금융종결액', '프로젝트 허가기간', '정제수율과 고객 인증', '장기계약 가격 하한', 'EU 공동구매 실행'],
      officialSources: [
        { id: 'eu-critical-raw-materials-act', name: 'European Commission · Critical Raw Materials Act', url: 'https://commission.europa.eu/topics/competitiveness/green-deal-industrial-plan/european-critical-raw-materials-act_en', publishedAt: '2023-03-16', accessedAt: '2026-07-17' },
        { id: 'eu-resourceeu', name: 'European Commission · RESourceEU action plan', url: 'https://commission.europa.eu/news-and-media/news/new-measures-secure-raw-materials-and-strengthen-eus-economic-security-2025-12-03_en', publishedAt: '2025-12-03', accessedAt: '2026-07-17' },
        { id: 'dod-mine-to-magnet', name: 'U.S. Department of Defense · Mine-to-Magnet', url: 'https://www.defense.gov/News/News-Stories/Article/Article/3700059/dod-looks-to-establish-mine-to-magnet-supply-chain-for-rare-earth-materials/', publishedAt: '2024-03-11', accessedAt: '2026-07-17' },
        { id: 'usar-serra-verde', name: 'USA Rare Earth · Serra Verde acquisition', url: 'https://investors.usare.com/news-releases/news-release-details/usa-rare-earth-announces-definitive-agreement-acquire-serra', publishedAt: '2026-04-20', accessedAt: '2026-07-17' },
        { id: 'usar-nasdaq-history', name: 'Nasdaq · USA Rare Earth historical prices', url: 'https://www.nasdaq.com/market-activity/stocks/usar/historical', publishedAt: '2026-07-16', accessedAt: '2026-07-17' },
      ],
    },
    {
      id: 'burberry-turnaround',
      order: 2,
      headline: 'Burberry 1분기 턴어라운드',
      source: {
        name: 'The Wall Street Journal',
        url: 'https://www.wsj.com/business/retail/burberry-reports-flat-sales-growth-amid-turnaround-efforts-b9adbd16',
        publishedAt: '2026-07-17T02:53:00-04:00',
        accessedAt: '2026-07-17T16:55:00+09:00',
      },
      relatedCompanies: ['Burberry'],
      relatedCompanySlugs: [],
      relatedIndustries: ['명품', '소매'],
      whatHappened: 'Burberry의 2027회계연도 1분기 comparable retail sales는 5% 증가했고, 여성복·남성복·액세서리·아동복이 모두 성장한 것은 3년 만에 처음입니다. 13주 매출은 4억5,500만 파운드였고 미주 +12%, 중화권 +9%, 아시아태평양 +3%, EMEIA -3%였습니다. 헤리티지 상품과 매장 경험을 다시 묶는 Burberry Forward가 앞단 고객 지표에서 신호를 보였습니다.',
      whyItMatters: '브랜드 회복이 정상가 판매와 재구매로 이어지는지 확인해야 합니다.',
      structuralMeaning: '명품 턴어라운드는 캠페인 노출이 신규 고객, 매장 전환율, 정상가 판매, 재고 할인 축소, 총마진과 영업현금흐름으로 이어질 때 완성됩니다.',
      confirmedFacts: ['Q1 comparable retail sales +5%', '매출 £455M', '미주 +12%, 중화권 +9%, APAC +3%, EMEIA -3%'],
      companyOrInstitutionOutlook: ['회사는 FY27 매출 성장과 마진 확대를 기대합니다.', 'H1 도매매출 가이던스는 높은 한 자릿수 증가로 제시됐습니다.'],
      keyNumbers: ['신규 레인웨어 고객 +19%', 'e-commerce 10%대 중반 성장', 'FY27 비용절감 목표 £100M 중 FY26 £80M 달성'],
      marketReaction: '원문 동적 시세에 BRBY +2.33%가 표시됐지만 결과가 예상치와 같아 상승을 특정 숫자 하나의 효과로 단정하지 않았습니다.',
      priceBasis: '2026-07-17 약 08:50 BST, 런던 정규장 초반 장중 수치이며 종가가 아닙니다.',
      currentStage: '1분기 수치는 회사가 발표했지만 연간 매출 성장·마진 확대와 도매 가이던스는 회사 전망입니다.',
      correctedWording: ['모든 지역 성장이 아니라 모든 제품 부문 성장입니다.', '5% comparable growth는 동일점포와 온라인의 고정환율 비교치로 전체 소매매출 증가율과 다릅니다.'],
      interpretation: '브랜드 회복이 지속적인 가격결정력과 마진 확대로 이어지는지는 아직 확인이 필요합니다.',
      notYetFinal: ['FY27 연간 실적', '중동 분쟁의 소비 영향', '마진 확대 폭과 비용절감의 실제 유입'],
      cashFlowTransmission: '상품·캠페인 집중 → 신규 고객·매장 전환 → 정상가 판매 → 총마진·재고 현금화 → 영업현금흐름',
      counterScenario: '미국·중국 회복이 둔화하거나 관광 소비가 약해져 매출 증가가 할인과 마케팅비로 상쇄될 수 있습니다.',
      factCheckStatus: 'checked',
      watchItems: ['정상가 판매율과 총마진', '재고회전', '신규 고객 재구매', '지역별 관광소비', 'H1 도매매출'],
      officialSources: [
        { id: 'burberry-q1-fy27', name: 'Burberry Group · FY2027 Q1 Trading Update', url: 'https://www.rns-pdf.londonstockexchange.com/rns/7189M_1-2026-7-16.pdf', publishedAt: '2026-07-17', accessedAt: '2026-07-17' },
        { id: 'burberry-consensus', name: 'Burberry Group · Q1 FY2027 Consensus', url: 'https://www.burberryplc.com/investors/consensus', publishedAt: '2026-07-10', accessedAt: '2026-07-17' },
        { id: 'burberry-lse', name: 'London Stock Exchange · Burberry Group', url: 'https://www.londonstockexchange.com/stock/BRBY/burberry-group-plc', publishedAt: '2026-07-17', accessedAt: '2026-07-17' },
      ],
    },
    {
      id: 'kimi-k3-model',
      order: 3,
      headline: 'Moonshot AI의 Kimi K3',
      source: {
        name: 'The Wall Street Journal',
        url: 'https://www.wsj.com/tech/ai/chinas-moonshot-ai-releases-model-to-challenge-top-u-s-systems-d84fe6e9',
        publishedAt: '2026-07-17T01:26:00-04:00',
        accessedAt: '2026-07-17T16:55:00+09:00',
      },
      relatedCompanies: ['Moonshot AI'],
      relatedCompanySlugs: [],
      relatedIndustries: ['인공지능', '개발자 도구'],
      whatHappened: 'Moonshot AI는 총 2.8조 파라미터, 100만 토큰 컨텍스트와 네이티브 비전을 갖춘 Kimi K3를 공개했습니다. 서비스와 API는 출시됐지만 전체 가중치와 기술보고서는 2026년 7월 27일 공개 예정입니다. 일부 코딩·에이전트 벤치마크에서 여러 미국 모델을 앞섰다는 회사 결과가 있으나 모델별 하네스가 달라 동일 조건의 독립평가로 보기는 어렵습니다.',
      whyItMatters: '성능·가격·공개 범위가 AI 모델의 새로운 기준이 될 수 있습니다.',
      structuralMeaning: 'AI 모델의 협상력은 파라미터 수보다 성능·추론비용·배포 가능성·개발자 채택이 반복 사용의 표준으로 굳을 때 생깁니다.',
      confirmedFacts: ['Kimi K3 서비스와 API가 공개됐습니다.', '2.8T 파라미터와 1M 컨텍스트를 회사가 명시했습니다.'],
      companyOrInstitutionOutlook: ['전체 가중치와 상세 기술보고서는 2026년 7월 27일 공개 예정입니다.', '진행 중인 투자 라운드의 315억 달러 평가는 종결된 공개시장 가격이 아닙니다.'],
      keyNumbers: ['2.8T 파라미터', '16/896 전문가 활성화', '1M 컨텍스트', '입력 ¥20/MTok·출력 ¥100/MTok'],
      marketReaction: 'Moonshot AI는 비상장사라 독립적인 공개 주가 반응이 없습니다.',
      priceBasis: '주가 정보는 사용하지 않았고 API 가격은 2026-07-17 공식 플랫폼 표시 기준입니다.',
      currentStage: '서비스·API는 출시됐고 전체 가중치와 상세 기술보고서는 공개 예정입니다.',
      correctedWording: ['미국 최상위 모델을 이겼다고 일반화하지 않고 일부 회사 보고 벤치마크로 한정했습니다.', '완전 오픈소스 출시가 아니라 서비스 출시와 전체 가중치 공개 예정을 구분했습니다.'],
      interpretation: '미국 모델의 가격결정력이 실제로 약해질지, 기업 워크로드에서 같은 품질이 재현될지는 아직 확인되지 않았습니다.',
      notYetFinal: ['전체 가중치와 기술보고서 공개', '독립 벤치마크', '진행 중인 투자 라운드와 홍콩 IPO 준비'],
      cashFlowTransmission: '성능·공개 범위 → 개발자 채택 → 반복 사용·API 매출 → 경쟁사 토큰 가격과 모델 프리미엄 재평가',
      counterScenario: '실제 호스팅 비용, 하네스 의존성, 공개 지연, 보안·규제 우려가 채택을 제한할 수 있습니다.',
      factCheckStatus: 'checked',
      watchItems: ['실제 추론원가와 지연시간', '독립평가', '다운로드·API 사용량', '기업 도입', '규제·보안정책', '자금조달 종결'],
      officialSources: [
        { id: 'kimi-k3-blog', name: 'Kimi · Kimi K3: Open Frontier Intelligence', url: 'https://www.kimi.com/fr-fr/blog/kimi-k3', publishedAt: '2026-07-17', accessedAt: '2026-07-17' },
        { id: 'kimi-api', name: 'Kimi · API 공식 플랫폼', url: 'https://platform.kimi.com/', publishedAt: '2026-07-17', accessedAt: '2026-07-17' },
        { id: 'kimi-model-docs', name: 'Kimi Code · 모델 문서', url: 'https://www.kimi.com/code/docs/en/kimi-code/models.html', publishedAt: '2026-07-17', accessedAt: '2026-07-17' },
      ],
    },
  ],
  commonThread: '희토류에서는 금융과 장기 계약이 미래 생산량을 먼저 묶고, Burberry에서는 상품과 매장 경험이 브랜드를 다시 살 이유로 고정하며, Kimi K3에서는 성능·공개 범위·API 가격이 개발자의 비교 기준을 만듭니다. 세 사건 모두 크기보다 자본·상품·코드를 반복 가능한 계약과 선택의 표준으로 먼저 고정하는 쪽이 협상력을 얻는다는 공통점이 있습니다. 다만 프로젝트 실행, 고객 재구매, 독립 성능 재현이 뒤따르지 않으면 그 표준은 유지되지 않습니다.',
  cashFlowTransmission: [
    '희토류: 정책자금·가격 하한·오프테이크가 자본비용을 낮추고 건설과 정제를 거쳐 장기 물량·단가·가동률로 현금흐름을 만듭니다.',
    'Burberry: 캠페인과 상품 집중이 신규 고객·매장 전환·정상가 판매를 거쳐 총마진과 재고 현금화로 이어져야 합니다.',
    'Kimi K3: 성능과 공개 범위가 개발자 채택과 API 사용량을 만들고 경쟁사의 토큰 가격과 모델 프리미엄을 압박합니다.',
  ],
  investorQuestions: [
    '발표된 기준이 실제 계약·정상가 판매·반복 사용으로 전환되는 비율은 얼마인가?',
    '기준을 유지하는 데 드는 자본비용·마케팅비·추론원가와 경쟁사의 대응은 무엇인가?',
    '고객과 공급자가 바꾸기 어려운 표준으로 굳었는가, 아직 되돌릴 수 있는 선택인가?',
  ],
  oneLineTakeaway: '큰 숫자보다 먼저 봐야 할 것은 그 숫자를 시장의 반복 가능한 기준으로 고정하는 계약과 전환율입니다.',
  relatedCompanySlugs: [],
  relatedIndustries: ['핵심광물', '명품', '인공지능'],
  relatedStockDissectionIds: [],
  disclaimer: '본 콘텐츠는 주가해부실이 공개 자료와 원문 기사를 바탕으로 작성한 독자적 분석이며, The Wall Street Journal 또는 Dow Jones와 제휴·후원 관계가 없습니다. 투자 권유가 아닌 정보 제공 목적의 자료입니다.',
};

export default standardsSetPriceEdition;
