import type { ThreeReadsEdition } from '../types.js';

export const optionCostEdition: ThreeReadsEdition = {
  id: 'wall-street-2026-07-23-option-cost',
  slug: '2026-07-23-option-cost',
  status: 'published',
  publishedAt: '2026-07-24',
  updatedAt: '2026-07-24',
  contentAsOf: '2026-07-23',
  title: '선택권은 공짜가 아니다',
  centralQuestion: '결정을 미루고 선택지를 남겨두는 동안 그 비용은 누구의 현금흐름에 쌓이는가?',
  introduction: '전쟁과 금리, 사모펀드의 매각 연기, 사우디의 농축 가능성은 서로 다른 이야기처럼 보입니다. 하지만 모두 지금 결정을 끝내지 않고 미래 선택지를 남겨두는 대신 가계·기업·LP·지역 안보에 비용을 넘기는 구조입니다.',
  authoringTime: '2026-07-24 02:20 KST',
  factCheckedAt: '2026-07-24 02:20 KST',
  verification: {
    authoredBy: 'owner',
    verifiedBy: 'owner',
    verifiedAt: '2026-07-24T02:20:00+09:00',
    status: 'ownerVerified',
    note: '로그인된 WSJ 원문 메타데이터와 기사 업데이트 수치, 미국 정부·IAEA·PitchBook·Preqin 자료를 교차확인했습니다.',
  },
  independentDisclosure: '주가해부실의 독자적 해설 · 주요 출처: The Wall Street Journal · 세 번째 글은 WSJ 편집위원회 사설',
  methodology: {
    newsWindow: '2026년 7월 21~23일 공개·업데이트된 WSJ 원문 세 건을 2026년 7월 24일 02:20 KST에 다시 확인했습니다.',
    duplicateCheck: '기존 7월 17일·18일 edition과 URL·사건·메커니즘을 비교해 중복되지 않는 금리·사모시장·비확산 주제를 선정했습니다.',
    candidateSelection: '현재 현금흐름에 영향을 주는 시장 가격, 사모자산 회수, 장기 정책 선택권을 하나의 비용 전달 구조로 연결했습니다.',
    factCheckSummary: [
      '국채: WSJ 기사 업데이트 시각과 Tradeweb 장중 4.711%, 미국 재무부 일별 금리 자료의 서로 다른 관측 기준을 구분했습니다.',
      '사모펀드: PitchBook NAV $348.5B·$512.7B와 Preqin 포트폴리오 기업가치 $3.91T·74%를 다른 정의로 분리했습니다.',
      '원전: 미국 에너지부의 123 협정 발표와 IAEA 추가의정서 설명을 확인하고 WSJ 편집위원회의 정책 판단을 사실과 분리했습니다.',
    ],
    correctedExpressions: [
      '초안의 10년물 4.665%를 현재 기사 업데이트의 4.711%로 보정하고 같은 시점 값처럼 혼합하지 않았습니다.',
      '$3.91T를 좀비펀드 손실이나 NAV로 표현하지 않고 북미 미매각 포트폴리오 기업가치로 구분했습니다.',
      '사우디의 국내 농축이 즉시 허용됐다고 하지 않고 2년 공동 연구 뒤 결정될 선택지로 표시했습니다.',
    ],
    notYetFinal: [
      '10년물 금리가 5%를 다시 시험할지와 고금리의 성장·주가 영향',
      '노후 펀드 자산의 실제 매각가·세컨더리 할인·LP 현금분배',
      '미·사우디 협정의 의회 심사 결과와 농축·검증의 최종 조건',
    ],
    priceBasis: [
      '4.711%는 Tradeweb 기준 2026년 7월 23일 목요일 장중 수치이며 종가나 미국 재무부 일별 고정금리와 같지 않습니다.',
      '사모펀드 수치는 2025년 말 NAV와 2025년 9월 포트폴리오 기업가치로 기준일·정의가 다릅니다.',
      '원전 사설은 공개시장 주가 반응을 특정하지 않고 정책·비확산 시나리오만 설명합니다.',
    ],
  },
  reads: [
    {
      id: 'long-yield-option-cost',
      order: 1,
      headline: '장기금리가 청구하는 선택 비용',
      source: {
        name: 'The Wall Street Journal',
        url: 'https://www.wsj.com/finance/investing/what-surging-bond-yields-mean-for-consumers-and-markets-cb37b61f',
        articleIdentifier: 'cb37b61f',
        publishedAt: '2026-07-22',
        updatedAt: '2026-07-23T11:46:00-04:00',
        accessedAt: '2026-07-24T02:20:00+09:00',
      },
      relatedCompanies: [],
      relatedCompanySlugs: [],
      relatedIndustries: ['미국 국채', '금리·신용'],
      whatHappened: '중동 교전 재개와 유가·인플레이션 우려, 예상보다 견조한 고용이 금리 인하 기대를 밀어내며 미 국채 매도가 이어졌습니다. Tradeweb 기준 10년물 금리는 7월 23일 장중 4.711%로 2025년 1월 이후 가장 높았습니다.',
      whyItMatters: '10년물은 주택담보대출·학자금·회사채의 기준이자 주식의 대체수익률이어서 전쟁과 인플레이션의 불확실성이 가계·기업의 자금비용으로 전달됩니다.',
      structuralMeaning: '군사·통화정책의 선택권을 오래 유지할수록 만기 프리미엄과 실질 조달비용이 높아질 수 있습니다. 다만 4.711%는 장중 관측값이고 5% 재시험은 확정 전망이 아니라 시장이 탐색할 수 있는 시나리오입니다.',
      confirmedFacts: ['Tradeweb 기준 10년물 금리는 2026년 7월 23일 장중 4.711%에 도달했습니다.', 'WSJ는 이를 2025년 1월 이후 가장 높은 장중 수준으로 설명했습니다.', '기사 업데이트 시각은 2026년 7월 23일 11:46 ET입니다.'],
      keyNumbers: ['10년물 4.711% 장중', '이전 2026년 고점 4.687%', '2023년 10월 장중 5% 상회 경험', 'S&P 500 기사 시점 -1.5%'],
      marketReaction: '4.711%는 Tradeweb 장중 관측입니다. 미국 재무부의 일별 수익률 곡선은 별도 방법론·시점이므로 같은 값으로 취급하지 않았습니다.',
      priceBasis: '2026-07-23 11:46 ET 업데이트 · Tradeweb 장중 수치',
      currentStage: '10년물은 2026년 이전 고점을 넘었지만 5% 재시험과 경기·주식의 충격 크기는 아직 확정되지 않았습니다.',
      correctedWording: ['초안의 4.665%는 이전 스냅샷이며 현재 웹 edition은 기사 업데이트의 4.711%를 사용합니다.', '5%는 전망이 아니라 빠른 상승 시 탐색될 수 있는 시나리오입니다.'],
      interpretation: '결정을 미루는 정책 선택권의 비용이 가장 먼저 장기금리와 신규 차입자의 현금흐름에 쌓이고 있습니다.',
      notYetFinal: ['중동 교전과 유가 경로', '연준의 실제 정책 변경', '10년물 5% 재시험', '주택·회사채·주식에 누적될 영향'],
      cashFlowTransmission: '교전·유가 불확실성 → 인플레이션·정책금리 기대 → 장기금리 → 모기지·회사채·할인율 → 가계·기업의 이자와 투자 부담',
      counterScenario: '교전 완화, 유가 하락, 고용 둔화나 강한 국채 수요가 장기금리를 다시 낮출 수 있습니다.',
      factCheckStatus: 'checked',
      watchItems: ['10년물 종가와 변동성', '유가·기대인플레이션', '연준 경로', '모기지·회사채 스프레드', '주식 이익수익률'],
      officialSources: [
        { id: 'us-treasury-daily-rates-2026-07', name: 'U.S. Treasury · Daily Treasury Par Yield Curve Rates', url: 'https://home.treasury.gov/resource-center/data-chart-center/interest-rates/TextView?field_tdr_date_value_month=202607&type=daily_treasury_yield_curve', publishedAt: '2026-07-23', accessedAt: '2026-07-24' },
      ],
    },
    {
      id: 'zombie-private-equity-option-cost',
      order: 2,
      headline: '매각을 미룬 대가가 LP에 쌓인다',
      source: {
        name: 'The Wall Street Journal',
        url: 'https://www.wsj.com/finance/investing/private-equity-assets-stuck-in-zombie-funds-are-at-a-record-high-4dbd01be',
        articleIdentifier: '4dbd01be',
        publishedAt: '2026-07-21T20:00:00-04:00',
        accessedAt: '2026-07-24T02:20:00+09:00',
      },
      relatedCompanies: [],
      relatedCompanySlugs: [],
      relatedIndustries: ['사모펀드', '기관 유동성'],
      whatHappened: 'PitchBook 기준 2025년 말 최소 10년 된 미국 사모펀드의 미매각 자산 NAV는 $348.5B로 사상 최대였고 7~9년 펀드 자산은 $512.7B였습니다. Preqin은 2025년 9월 북미 미매각 포트폴리오 기업가치를 $3.91T, 전체의 74%로 집계했습니다.',
      whyItMatters: '매각을 미루면 장부가 손실 확정은 늦출 수 있지만 LP의 현금분배와 재투자 여력이 줄고 연금·보험사의 지급 의무와 유동성 부담이 커질 수 있습니다.',
      structuralMeaning: '$348.5B와 $512.7B는 펀드 연령별 순자산가치이고 $3.91T·74%는 북미 미매각 포트폴리오 기업가치입니다. 장부가치가 곧 손실은 아니며 컨티뉴에이션 차량도 모두 부실을 뜻하지 않습니다.',
      confirmedFacts: ['10년 이상 미국 PE 펀드의 미매각 자산 NAV는 2025년 말 $348.5B였습니다.', '7~9년 펀드 자산은 2025년 $512.7B였습니다.', '북미 미매각 포트폴리오 기업가치는 2025년 9월 $3.91T로 전체의 74%였습니다.'],
      keyNumbers: ['$348.5B · 10년 이상 펀드 NAV', '$512.7B · 7~9년 펀드 자산', '$3.91T · 북미 미매각 포트폴리오 기업가치', '74% · 북미 PE 자산 비중'],
      marketReaction: '비상장 자산에는 기사 당일 하나의 공개시장 가격이 없습니다. 숫자는 손실액이 아니라 서로 다른 데이터 제공자의 장부 기준입니다.',
      priceBasis: 'PitchBook 2025년 말 · Preqin 2025년 9월 · NAV와 기업가치 구분',
      currentStage: '세컨더리 거래와 컨티뉴에이션 차량이 회수 선택지를 늘리지만 실제 할인율·DPI·LP 분배는 아직 확정되지 않았습니다.',
      correctedWording: ['$3.91T는 좀비펀드 손실도 NAV도 아닙니다.', '컨티뉴에이션 차량을 모두 부실 자산 처리로 일반화하지 않습니다.', '장부가치와 회수 현금을 구분합니다.'],
      interpretation: '매각 연기의 선택권은 자산을 더 오래 키울 시간을 주지만 그동안 필요한 유동성 비용을 LP와 지급 의무가 있는 기관이 부담합니다.',
      notYetFinal: ['실제 매각가와 세컨더리 할인', '컨티뉴에이션 차량의 조건', 'DPI와 LP 현금분배', '손실 인식과 재평가'],
      cashFlowTransmission: '고점 인수가·높은 금리 → 매각 지연 → 분배 감소·기간 연장 → LP 재투자 제약 → 연금·보험사의 유동성 부담',
      counterScenario: 'M&A와 IPO 시장 회복, 영업 개선, 질서 있는 세컨더리 거래가 할인과 유동성 부담을 줄일 수 있습니다.',
      factCheckStatus: 'checked',
      watchItems: ['DPI·분배액', '평균 보유기간', '세컨더리 할인율', '컨티뉴에이션 거래 조건', '출구 건수·가치'],
      officialSources: [
        { id: 'pitchbook-us-pe-data-2026', name: 'PitchBook · Private Equity Database and US PE Breakdown', url: 'https://pitchbook.com/private-equity-database', publishedAt: '2026-07-23', accessedAt: '2026-07-24' },
        { id: 'preqin-pe-q3-2025', name: 'Preqin · Private Equity Q3 2025 Update', url: 'https://www.preqin.com/insights/research/quarterly-updates/private-equity-q3-2025-preqin-quarterly-update', publishedAt: '2025-11-01', accessedAt: '2026-07-24' },
      ],
    },
    {
      id: 'saudi-nuclear-option-cost',
      order: 3,
      headline: '농축 선택권과 검증 비용',
      source: {
        name: 'The Wall Street Journal · Opinion',
        url: 'https://www.wsj.com/opinion/saudi-nuclear-enrichment-donald-trump-iran-uranium-90be14a6',
        articleIdentifier: '90be14a6',
        publishedAt: '2026-07-22T17:22:00-04:00',
        accessedAt: '2026-07-24T02:20:00+09:00',
      },
      relatedCompanies: [],
      relatedCompanySlugs: [],
      relatedIndustries: ['민간 원자력', '핵비확산'],
      whatHappened: '미국과 사우디는 123 민간 원자력 협정과 양자 안전조치 협정을 체결했고 협정은 의회 심사로 넘어갑니다. WSJ 편집위원회는 국내 농축의 경제성·상업성을 2년간 공동 연구한 뒤 결정하는 구조와 IAEA 추가의정서가 빠진 점을 비확산 위험으로 비판했습니다.',
      whyItMatters: '미국 기업의 원전 참여 기회와 사우디의 에너지 다변화를 열지만 농축 가능성을 남긴 선택권은 검증·외교·지역 위험 프리미엄의 비용을 높일 수 있습니다.',
      structuralMeaning: '골드 스탠더드는 국내 우라늄 농축과 플루토늄 재처리를 포기하는 기준이고 IAEA 추가의정서는 핵연료주기 전반의 추가 정보와 더 넓은 현장 접근을 제공합니다. 즉시 농축 허용·시설 건설·핵무기 개발은 확인된 사실이 아닙니다.',
      confirmedFacts: ['미국과 사우디는 2026년 7월 22일 평화적 원자력 협력 123 협정과 양자 안전조치 협정을 체결했습니다.', '협정은 미국 기업의 사우디 민간 원전 프로그램 참여를 넓히며 의회 심사를 거칩니다.', 'WSJ 사설은 국내 농축의 가치·상업성을 2년간 공동 연구한 뒤 결정하는 조건을 설명했습니다.'],
      keyNumbers: ['2년 · 농축 경제성·상업성 공동 연구', '123 협정 · 미국 원자력법상 협력 기반', '의회 심사 · 최종 조건 확인 필요'],
      marketReaction: '이 글은 WSJ 편집위원회의 사설입니다. 공개시장 주가를 협정의 직접 반응으로 연결하지 않았습니다.',
      priceBasis: '정책 협정과 사설 분석 · 공개시장 가격 사용 안 함',
      currentStage: '협정은 체결됐지만 의회 심사, 농축 연구 결과, IAEA 검증 조건과 실제 시설 결정은 남아 있습니다.',
      correctedWording: ['사우디 국내 농축이 즉시 허용됐다고 표현하지 않습니다.', '농축시설 건설·핵무기 개발·주변국 연쇄 핵개발은 확정 사실이 아닙니다.', '핵확산 위험은 WSJ 편집위원회의 정책 판단과 시나리오로 표시합니다.'],
      interpretation: '농축 선택권은 전략적 자율성을 넓힐 수 있지만 검증 기준을 낮추면 외교·안보 비용과 지역 위험 프리미엄이 커질 수 있다는 것이 편집위원회의 주장입니다.',
      notYetFinal: ['의회 심사 결과', '2년 공동 연구의 범위와 결론', 'IAEA 추가의정서 또는 대체 안전조치의 강도', '실제 원전·연료주기 사업자 선정'],
      cashFlowTransmission: '민간 원전 협력 → 미국 기업 참여·사우디 투자 → 농축 선택권 → 검증·외교 복잡성 → 프로젝트 자본비용과 지역 위험 프리미엄',
      counterScenario: '강한 양자 안전조치, 의회 보완, 국제 연료 공급과 투명한 검증이 농축 선택권의 확산 위험을 줄일 수 있습니다.',
      factCheckStatus: 'checked',
      watchItems: ['의회 제출 문서', '2년 연구의 공개 범위', 'IAEA 추가의정서·대체 안전조치', '미국 기업 계약', '지역 외교 반응'],
      officialSources: [
        { id: 'doe-us-saudi-nuclear-2026', name: 'U.S. Department of Energy · U.S.-Saudi Nuclear Cooperation Agreement', url: 'https://www.energy.gov/articles/united-states-and-saudi-arabia-reach-historic-nuclear-cooperation-agreement', publishedAt: '2026-07-22', accessedAt: '2026-07-24' },
        { id: 'iaea-additional-protocol-framework', name: 'IAEA · The Legal Framework for IAEA Safeguards', url: 'https://www.iaea.org/sites/default/files/24/09/legal_framework_for_safeguards_iaea_brief_sept2024.pdf', publishedAt: '2024-09-01', accessedAt: '2026-07-24' },
      ],
    },
  ],
  commonThread: '군사적 선택권은 유가·인플레이션·장기금리로, 매각 연기는 LP 분배와 기관 유동성으로, 농축 가능성은 검증·외교·지역 위험 프리미엄으로 비용을 넘깁니다. 결정을 미루는 것 자체가 무료가 아니라는 공통점입니다.',
  cashFlowTransmission: [
    '군사적 선택권 → 유가·인플레이션 불확실성 → 장기금리 → 가계·기업의 이자와 투자 부담',
    '매각 연기 선택권 → 손실 확정 지연 → 현금분배 감소 → LP·연금·보험사의 유동성 부담',
    '농축 선택권 → 전략적 자율성 가능성 → 검증·비확산 복잡성 → 프로젝트 자본비용과 지역 위험 프리미엄',
  ],
  investorQuestions: [
    '선택을 미룬 주체가 얻는 시간과 그동안 비용을 부담하는 주체는 누구인가?',
    '장중 금리·장부 NAV·정책 선택권이 실제 이자·분배·계약 현금흐름으로 어떻게 전환되는가?',
    '퇴로가 남아 있는가, 아니면 더 비싼 결정을 미래로 넘기고 있는가?',
  ],
  oneLineTakeaway: '좋은 선택권은 퇴로가 있는 선택권이다. 퇴로 없이 결정을 미루면 선택권은 자산이 아니라 비용이 된다.',
  relatedCompanySlugs: [],
  relatedIndustries: ['미국 국채', '사모펀드', '민간 원자력', '핵비확산'],
  relatedStockDissectionIds: [],
  analytics: {
    content_id: 'wall-street-2026-07-23-option-cost',
    campaign_id: 'wall-street-2026-07-23-option-cost',
    recommended_utm: { source: 'instagram', medium: 'social', campaign: 'wall-street-2026-07-23-option-cost', content: 'profile-link' },
  },
  disclaimer: '본 콘텐츠는 주가해부실의 독자적 분석이며 The Wall Street Journal 또는 Dow Jones와 제휴·후원 관계가 없습니다. 세 번째 글은 WSJ 편집위원회의 사설을 사실 자료와 분리해 설명했습니다. 투자 권유가 아닌 정보 제공 목적의 자료입니다.',
};

export default optionCostEdition;
