import { useEffect, useState, type ReactNode } from 'react';
import { ArrowRight, ExternalLink } from 'lucide-react';
import { loadStockDissection } from '../content/editorial/registry.js';
import { dateIsNotFuture, formatRelativeReturn, formatSignedPercent, isDetailVisible, moveCharacterLabels, relativeReturn, thesisImpactLabels } from '../content/editorial/selectors.js';
import { publishedEditorialSummaryIndex } from '../content/editorial/summaries.js';
import type { DailyStockDissection, ThreeReadsSummary } from '../content/editorial/types.js';
import { editorialDate, editorialInternalLink, editorialPath, type EditorialNavigate } from '../components/editorial/EditorialUi.js';

export default function StockDissectionRoute({ slug, navigation, onNavigate }: { slug: string; navigation: ReactNode; onNavigate: EditorialNavigate }) {
  const [item, setItem] = useState<DailyStockDissection | null | undefined>(undefined);
  useEffect(() => {
    let active = true;
    setItem(undefined);
    loadStockDissection(slug).then((loaded) => { if (active) setItem(loaded ?? null); }).catch(() => { if (active) setItem(null); });
    return () => { active = false; };
  }, [slug]);

  const today = new Date().toISOString().slice(0, 10);
  const publicItem = item && isDetailVisible(item.status) && dateIsNotFuture(item.publishedAt, today) ? item : null;
  if (item === undefined) return <div className="pick-shell editorial-shell">{navigation}<main className="editorial-route-state" role="status" aria-live="polite"><h1>주가 해부를 불러오는 중입니다.</h1></main></div>;
  if (!publicItem) return <div className="pick-shell editorial-shell">{navigation}<main className="editorial-route-state"><h1>공개된 주가 해부를 찾을 수 없습니다.</h1><p>출처와 기준일 검증을 마친 콘텐츠만 표시합니다.</p><a href="/ko/insights" onClick={editorialInternalLink('/ko/insights', onNavigate)}>리서치 목록으로 이동</a></main></div>;

  const comparisons = [publicItem.comparison?.market, publicItem.comparison?.sector].filter((value): value is NonNullable<typeof value> => Boolean(value) && value?.asOf === publicItem.priceAsOf);
  const relatedThreeReads = publishedEditorialSummaryIndex.filter((summary): summary is ThreeReadsSummary => summary.kind === 'threeReads' && publicItem.relatedThreeReadsIds.includes(summary.id)).slice(0, 3);
  const evidenceTypeLabels = { price: '가격 데이터', news: '관련 뉴스', company: '기업 발표', filing: '공시', regulatory: '규제 자료', market: '시장 데이터', sector: '업종 데이터', flow: '수급 자료' } as const;
  const factStatusLabels = { official: '공식 확인', mediaReported: '언론 보도', marketData: '시장 수치', editorialInterpretation: '편집자 해석' } as const;
  const visibleEvidence = publicItem.evidence?.slice(0, 5) ?? [];
  const remainingEvidence = publicItem.evidence?.slice(5) ?? [];

  return (
    <div className="pick-shell editorial-shell">
      {navigation}
      <main className="editorial-detail-main">
        <nav className="editorial-breadcrumb" aria-label="현재 위치"><a href="/ko/insights" onClick={editorialInternalLink('/ko/insights', onNavigate)}>리서치</a><span aria-hidden="true">/</span><strong>주가 해부</strong></nav>
        <header className="editorial-detail-header"><p>{publicItem.company.name}{publicItem.company.ticker ? ` · ${publicItem.company.ticker}` : ''}</p><h1>{publicItem.headline}</h1><div><time dateTime={publicItem.eventAsOf}>사건 기준 {editorialDate(publicItem.eventAsOf)}</time><time dateTime={publicItem.priceAsOf}>가격 기준 {editorialDate(publicItem.priceAsOf)}</time>{publicItem.intake ? <span>세션 {publicItem.intake.session === 'regular' ? '정규장' : publicItem.intake.session === 'preMarket' ? '장전' : '시간외'}</span> : null}</div></header>
        <dl className="editorial-verification editorial-authorship"><div><dt>작성·분석</dt><dd>주가해부실</dd></div><div><dt>편집 검증</dt><dd>Owner Verified{publicItem.verification ? ` · ${publicItem.verification.verifiedAt.replace('T', ' ').replace('+09:00', ' KST')}` : ''}</dd></div><div><dt>분석 기준</dt><dd>{editorialDate(publicItem.eventAsOf)} 사건 · {editorialDate(publicItem.priceAsOf)} 가격{publicItem.intake ? ` · ${publicItem.intake.session === 'regular' ? '정규장' : publicItem.intake.session === 'preMarket' ? '장전' : '시간외'}` : ''}</dd></div><div><dt>근거 자료</dt><dd>기업 공시 · 공식 발표 · 시장 데이터 · 주요 보도</dd></div></dl>

        <section className="editorial-detail-section editorial-price-section" aria-labelledby="stock-move-title"><div className="editorial-detail-heading"><span>01</span><h2 id="stock-move-title">확인된 움직임</h2></div><div className="editorial-price-panel"><div><span>{publicItem.priceMove.periodLabel}</span><strong>{formatSignedPercent(publicItem.priceMove.value, publicItem.priceMove.precision)}</strong></div>{comparisons.map((comparison) => <div key={comparison.name}><span>{comparison.name} 대비</span><strong>{formatRelativeReturn(relativeReturn(publicItem.priceMove.value, comparison.value), comparison.precision)}</strong><small>같은 거래일의 퍼센트포인트 차이</small></div>)}</div><ul className="editorial-confirmed-list">{publicItem.confirmedItems.map((entry) => <li key={entry}>{entry}</li>)}</ul></section>
        <section className="editorial-detail-section" aria-labelledby="stock-character-title"><div className="editorial-detail-heading"><span>02</span><h2 id="stock-character-title">이번 움직임의 성격</h2></div><div className="editorial-character-panel"><strong>{publicItem.cardCharacter ?? moveCharacterLabels[publicItem.moveCharacter]}</strong><p>{thesisImpactLabels[publicItem.thesisImpact]} · 공식 주문 취소나 가이던스 하향이 확인되지 않아 기준 판단을 자동 수정하지 않습니다.</p></div></section>
        <section className="editorial-detail-section" aria-labelledby="stock-catalyst-title"><div className="editorial-detail-heading"><span>03</span><h2 id="stock-catalyst-title">무슨 일이 있었나</h2></div><p className="editorial-lead-copy">{publicItem.directCatalyst}</p>{publicItem.fullArticle?.length ? <div className="editorial-article-body">{publicItem.fullArticle.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div> : null}</section>
        <section className="editorial-detail-section" aria-labelledby="stock-market-title"><div className="editorial-detail-heading"><span>04</span><h2 id="stock-market-title">시장 전체 요인</h2></div><div className="editorial-factor-grid editorial-single-factor"><article><ul>{publicItem.marketWideFactors.map((entry) => <li key={entry}>{entry}</li>)}</ul></article></div></section>
        <section className="editorial-detail-section" aria-labelledby="stock-company-title"><div className="editorial-detail-heading"><span>05</span><h2 id="stock-company-title">기업·산업 요인</h2></div><div className="editorial-factor-grid editorial-single-factor"><article><ul>{publicItem.companySpecificFactors.map((entry) => <li key={entry}>{entry}</li>)}</ul></article></div><div className="editorial-reason-grid">{publicItem.reasons.map((reason) => <article key={reason.title}><h3>{reason.title}</h3><p>{reason.explanation}</p></article>)}</div></section>
        <section className="editorial-detail-section" aria-labelledby="stock-unconfirmed-title"><div className="editorial-detail-heading"><span>06</span><h2 id="stock-unconfirmed-title">아직 확인되지 않은 것</h2></div><div className="editorial-certainty-grid editorial-single-factor"><article><h3>현재까지 공식 확인되지 않은 것</h3><ul>{publicItem.unconfirmedItems.map((entry) => <li key={entry}>{entry}</li>)}</ul></article></div></section>
        <section className="editorial-detail-section" aria-labelledby="stock-watch-title"><div className="editorial-detail-heading"><span>07</span><h2 id="stock-watch-title">앞으로 확인할 것</h2></div><ol className="editorial-watch-list">{publicItem.watchItems.map((entry) => <li key={entry}>{entry}</li>)}</ol></section>
        <section className="editorial-detail-section" aria-labelledby="stock-conclusion-title"><div className="editorial-detail-heading"><span>08</span><h2 id="stock-conclusion-title">주가해부실의 해석</h2></div><p className="editorial-conclusion">{publicItem.editorialConclusion ?? publicItem.marketInterpretation}</p></section>
        {visibleEvidence.length ? <section className="editorial-detail-section" aria-labelledby="stock-evidence-title"><div className="editorial-detail-heading"><span>09</span><h2 id="stock-evidence-title">분석에 사용한 자료</h2></div><div className="editorial-evidence-grid">{visibleEvidence.map((evidence) => <EvidenceCard key={evidence.id} evidence={evidence} typeLabel={evidenceTypeLabels[evidence.type]} statusLabel={factStatusLabels[evidence.factStatus]} />)}</div>{remainingEvidence.length ? <details className="editorial-evidence-details"><summary>전체 근거와 검증 기록 보기</summary><div className="editorial-evidence-grid">{remainingEvidence.map((evidence) => <EvidenceCard key={evidence.id} evidence={evidence} typeLabel={evidenceTypeLabels[evidence.type]} statusLabel={factStatusLabels[evidence.factStatus]} />)}</div></details> : null}</section> : null}
        {publicItem.verification ? <section className="editorial-detail-section" aria-labelledby="stock-verification-title"><div className="editorial-detail-heading"><span>10</span><h2 id="stock-verification-title">작성·검증 정보</h2></div><dl className="editorial-verification"><div><dt>작성·분석</dt><dd>주가해부실</dd></div><div><dt>편집 검증</dt><dd>Owner Verified</dd></div><div><dt>검증 시각</dt><dd><time dateTime={publicItem.verification.verifiedAt}>{publicItem.verification.verifiedAt.replace('T', ' ').replace('+09:00', ' KST')}</time></dd></div>{publicItem.verification.note ? <div><dt>기록</dt><dd>{publicItem.verification.note}</dd></div> : null}</dl><p className="editorial-verification-note">Owner Verified는 사실과 숫자를 확인했다는 편집 기록이며, 사건의 미래 결과를 보증하지 않습니다. 가격·실적·공시의 원천 출처는 위 근거 자료에서 별도로 확인합니다.</p></section> : null}
        {relatedThreeReads.length || publicItem.company.companySlug ? <section className="editorial-detail-section" aria-labelledby="stock-related-title"><div className="editorial-detail-heading"><span>11</span><h2 id="stock-related-title">관련 기업</h2></div><div className="editorial-related-links">{relatedThreeReads.map((related) => { const path = editorialPath(related); return <a key={related.id} href={path} onClick={editorialInternalLink(path, onNavigate)}>{related.title}<ArrowRight size={14} aria-hidden="true" /></a>; })}{publicItem.company.companySlug ? <a href={`/ko/companies/${encodeURIComponent(publicItem.company.companySlug)}`} onClick={editorialInternalLink(`/ko/companies/${encodeURIComponent(publicItem.company.companySlug)}`, onNavigate)}>{publicItem.company.name} 분석 보기<ArrowRight size={14} aria-hidden="true" /></a> : null}</div></section> : null}
        <aside className="editorial-disclaimer"><strong>면책</strong><p>{publicItem.disclaimer}</p></aside>
      </main>
    </div>
  );
}

function EvidenceCard({ evidence, typeLabel, statusLabel }: { evidence: NonNullable<DailyStockDissection['evidence']>[number]; typeLabel: string; statusLabel: string }) {
  return <article><div><span>{typeLabel}</span><strong>{statusLabel}</strong></div><h3>{evidence.title ?? evidence.publisher ?? evidence.id}</h3>{evidence.publisher ? <small>자료 제공처 {evidence.publisher}</small> : null}{evidence.asOf ? <time dateTime={evidence.asOf}>기준 {editorialDate(evidence.asOf)}</time> : null}{evidence.publishedAt ? <time dateTime={evidence.publishedAt}>발행 {editorialDate(evidence.publishedAt)}</time> : null}{evidence.note ? <p>{evidence.note}</p> : null}{evidence.url ? <a href={evidence.url} target="_blank" rel="noopener noreferrer" aria-label={`${evidence.title ?? evidence.id} 자료 새 창에서 열기`}>자료 열기 <ExternalLink size={13} aria-hidden="true" /></a> : null}</article>;
}
