import type { MarketMapCompanyRelation } from './types.js';

const reviewedAt = '2026-07-13';
const contextualCaution = '이 관계는 산업 구조를 이해하기 위한 참고 연결입니다. 특정 직접 계약을 의미하지 않습니다.';
const reviewNeededCaution = '산업 역할의 연결 후보이지만 두 기업의 공식 관계는 추가 확인이 필요합니다. 특정 직접 계약을 의미하지 않습니다.';

const relation = (
  input: Omit<MarketMapCompanyRelation, 'reviewedAt' | 'caution'> & { caution?: string },
): MarketMapCompanyRelation => ({
  ...input,
  caution: input.caution ?? (input.evidenceLevel === 'review-needed' ? reviewNeededCaution : contextualCaution),
  reviewedAt,
});

export const marketMapCompanyRelations: MarketMapCompanyRelation[] = [
  relation({
    id: 'us-ai-google-broadcom-demand', mapId: 'us-semiconductors',
    fromCompanyId: 'ai-datacenter-google', toCompanyId: 'ai-datacenter-broadcom', direction: 'directed',
    relationType: 'demand-link', evidenceLevel: 'contextual', shortLabel: '맞춤형 칩 수요',
    explanation: '클라우드 AI 인프라 투자가 늘어날 때 맞춤형 반도체와 네트워크 반도체 수요를 함께 살펴보는 산업 관계입니다.',
    sourceRefs: ['iea-energy-and-ai-2025'],
  }),
  relation({
    id: 'us-ai-google-nvidia-demand', mapId: 'us-semiconductors',
    fromCompanyId: 'ai-datacenter-google', toCompanyId: 'us-semiconductors-nvidia', direction: 'directed',
    relationType: 'demand-link', evidenceLevel: 'contextual', shortLabel: 'AI 가속기 수요',
    explanation: 'AI 서비스와 클라우드 투자가 늘어날 때 GPU 기반 서버 수요를 함께 확인하는 산업 관계입니다.',
    sourceRefs: ['iea-energy-and-ai-2025', 'nvidia-fy2027-q1-results'],
  }),
  relation({
    id: 'us-ai-broadcom-tsmc-production', mapId: 'us-semiconductors',
    fromCompanyId: 'ai-datacenter-broadcom', toCompanyId: 'ai-datacenter-tsmc', direction: 'directed',
    relationType: 'production-link', evidenceLevel: 'contextual', shortLabel: '설계·파운드리',
    explanation: '맞춤형 반도체 설계와 첨단 파운드리 생산 역할이 같은 생산 과정에서 이어지는 산업 관계입니다.',
    sourceRefs: ['semi-memory-fab-outlook-q2-2026'],
  }),
  relation({
    id: 'us-ai-nvidia-tsmc-production', mapId: 'us-semiconductors',
    fromCompanyId: 'us-semiconductors-nvidia', toCompanyId: 'ai-datacenter-tsmc', direction: 'directed',
    relationType: 'production-link', evidenceLevel: 'contextual', shortLabel: 'GPU·파운드리',
    explanation: 'AI GPU 설계와 첨단 공정 생산 생태계를 함께 살펴보는 생산 역할 관계입니다.',
    sourceRefs: ['nvidia-fy2027-q1-results', 'semi-memory-fab-outlook-q2-2026'],
  }),
  relation({
    id: 'us-ai-nvidia-sk-hynix-demand', mapId: 'us-semiconductors',
    fromCompanyId: 'us-semiconductors-nvidia', toCompanyId: 'ai-datacenter-sk-hynix', direction: 'directed',
    relationType: 'demand-link', evidenceLevel: 'contextual', shortLabel: 'HBM 수요',
    explanation: 'AI 가속기 수요 확대와 고대역폭 메모리 수요를 함께 살펴보는 산업 관계입니다.',
    sourceRefs: ['nvidia-fy2027-q1-results', 'sk-hynix-hbm4-production-2025'],
  }),
  relation({
    id: 'us-ai-sk-hynix-samsung-context', mapId: 'us-semiconductors',
    fromCompanyId: 'ai-datacenter-sk-hynix', toCompanyId: 'ai-datacenter-samsung', direction: 'contextual',
    relationType: 'market-context', evidenceLevel: 'contextual', shortLabel: '메모리 시장 비교',
    explanation: '두 기업의 HBM·DRAM 제품과 메모리 투자 흐름을 같은 시장 안에서 비교하는 관계입니다.',
    sourceRefs: ['sk-hynix-q1-2026-results', 'samsung-electronics-earnings-releases'],
  }),
  relation({
    id: 'us-ai-nvidia-micron-demand', mapId: 'us-semiconductors',
    fromCompanyId: 'us-semiconductors-nvidia', toCompanyId: 'ai-datacenter-micron', direction: 'directed',
    relationType: 'demand-link', evidenceLevel: 'contextual', shortLabel: '고성능 메모리 수요',
    explanation: 'AI 서버와 가속기 수요가 늘어날 때 HBM·DRAM 수요를 함께 살펴보는 산업 관계입니다.',
    sourceRefs: ['nvidia-fy2027-q1-results', 'micron-fy2026-q3-results'],
  }),
  relation({
    id: 'us-ai-nvidia-vertiv-infrastructure', mapId: 'us-semiconductors',
    fromCompanyId: 'us-semiconductors-nvidia', toCompanyId: 'ai-datacenter-vertiv', direction: 'directed',
    relationType: 'infrastructure-link', evidenceLevel: 'contextual', shortLabel: '전력·냉각 수요',
    explanation: 'AI 서버 밀도가 높아질 때 데이터센터 전력과 냉각 인프라 수요를 함께 확인하는 관계입니다.',
    sourceRefs: ['iea-energy-and-ai-2025', 'nvidia-fy2027-q1-results'],
  }),
  relation({
    id: 'us-ai-nvidia-dell-demand', mapId: 'us-semiconductors',
    fromCompanyId: 'us-semiconductors-nvidia', toCompanyId: 'ai-datacenter-dell', direction: 'directed',
    relationType: 'demand-link', evidenceLevel: 'contextual', shortLabel: 'AI 서버 수요',
    explanation: 'AI 가속기 수요와 이를 탑재하는 AI 서버·IT 인프라 수요를 함께 살펴보는 관계입니다.',
    sourceRefs: ['nvidia-fy2027-q1-results', 'dell-fy2027-q1-results'],
  }),
  relation({
    id: 'us-ai-nvidia-supermicro-demand', mapId: 'us-semiconductors',
    fromCompanyId: 'us-semiconductors-nvidia', toCompanyId: 'ai-datacenter-supermicro', direction: 'directed',
    relationType: 'demand-link', evidenceLevel: 'contextual', shortLabel: '고성능 서버 수요',
    explanation: 'AI 가속기 수요와 고성능 서버 시스템 수요를 함께 살펴보는 산업 관계입니다.',
    sourceRefs: ['nvidia-fy2027-q1-results', 'ir-supermicro-2026-supermicro-announces-pricing-of-equity-and-equity-lin-f33c9243'],
  }),
  relation({
    id: 'us-ai-nvidia-arista-demand', mapId: 'us-semiconductors',
    fromCompanyId: 'us-semiconductors-nvidia', toCompanyId: 'ai-datacenter-arista', direction: 'directed',
    relationType: 'demand-link', evidenceLevel: 'contextual', shortLabel: '네트워크 수요',
    explanation: 'AI 서버가 늘어날 때 서버 사이의 데이터를 옮기는 고속 네트워크 수요를 함께 살펴보는 관계입니다.',
    sourceRefs: ['iea-energy-and-ai-2025', 'nvidia-fy2027-q1-results'],
  }),
  relation({
    id: 'us-ai-nvidia-marvell-official-supply', mapId: 'us-semiconductors',
    fromCompanyId: 'us-semiconductors-nvidia', toCompanyId: 'ai-datacenter-marvell', direction: 'directed',
    relationType: 'official-supply', evidenceLevel: 'confirmed', shortLabel: 'NVLink Fusion 협력',
    explanation: 'NVIDIA와 Marvell이 NVLink Fusion 기반 맞춤형 XPU·네트워킹 협력을 공식 발표한 관계입니다.',
    caution: '공식 자료에서 협력과 제공 역할이 확인됐습니다. 다만 특정 구매계약 금액이나 고객별 매출을 의미하지 않습니다.',
    sourceRefs: ['marvell-company-newsroom-nvidia-ai-ecosystem-expands-marvell-joins-force-8761be8f', 'investor-nvidia-2025-nvidia-unveils-nvlink-fusion-for-industry-to-build-cc4f6311'],
  }),
  relation({
    id: 'us-ai-asml-tsmc-production', mapId: 'us-semiconductors',
    fromCompanyId: 'ai-datacenter-asml', toCompanyId: 'ai-datacenter-tsmc', direction: 'directed',
    relationType: 'production-link', evidenceLevel: 'contextual', shortLabel: 'EUV·파운드리',
    explanation: '첨단 파운드리 생산과 EUV 노광장비 역할을 같은 생산 과정에서 살펴보는 관계입니다.',
    sourceRefs: ['semi-memory-fab-outlook-q2-2026'],
  }),
  relation({
    id: 'us-ai-asml-samsung-production', mapId: 'us-semiconductors',
    fromCompanyId: 'ai-datacenter-asml', toCompanyId: 'ai-datacenter-samsung', direction: 'directed',
    relationType: 'production-link', evidenceLevel: 'contextual', shortLabel: 'EUV·첨단 공정',
    explanation: '첨단 메모리·파운드리 투자와 EUV 노광장비 역할을 함께 살펴보는 생산 관계입니다.',
    sourceRefs: ['semi-memory-fab-outlook-q2-2026', 'samsung-electronics-earnings-releases'],
  }),
  relation({
    id: 'us-ai-asml-intel-production', mapId: 'us-semiconductors',
    fromCompanyId: 'ai-datacenter-asml', toCompanyId: 'ai-datacenter-intel', direction: 'directed',
    relationType: 'production-link', evidenceLevel: 'contextual', shortLabel: 'EUV·첨단 제조',
    explanation: '첨단 반도체 제조 투자와 EUV 노광장비 역할을 함께 살펴보는 생산 관계입니다.',
    sourceRefs: ['semi-memory-fab-outlook-q2-2026'],
  }),
  relation({
    id: 'us-ai-hanmi-sk-hynix-production', mapId: 'us-semiconductors',
    fromCompanyId: 'ai-datacenter-hanmi', toCompanyId: 'ai-datacenter-sk-hynix', direction: 'directed',
    relationType: 'production-link', evidenceLevel: 'contextual', shortLabel: 'HBM 후공정',
    explanation: 'HBM 생산 확대와 적층·본딩을 포함한 후공정 장비 수요를 함께 살펴보는 관계입니다.',
    sourceRefs: ['sk-hynix-hbm4-production-2025', 'semi-memory-fab-outlook-q2-2026'],
  }),
  relation({
    id: 'us-ai-leeno-nvidia-production-review', mapId: 'us-semiconductors',
    fromCompanyId: 'ai-datacenter-leeno', toCompanyId: 'us-semiconductors-nvidia', direction: 'contextual',
    relationType: 'market-context', evidenceLevel: 'review-needed', shortLabel: '테스트 부품 후보',
    explanation: '고성능 AI 칩 생산과 테스트 소켓·핀 역할의 연결을 추가 검토하는 관계입니다.',
    sourceRefs: ['nvidia-fy2027-q1-results'],
  }),
  relation({
    id: 'us-ai-isc-nvidia-production-review', mapId: 'us-semiconductors',
    fromCompanyId: 'ai-datacenter-isc', toCompanyId: 'us-semiconductors-nvidia', direction: 'contextual',
    relationType: 'market-context', evidenceLevel: 'review-needed', shortLabel: '테스트 소켓 후보',
    explanation: '고성능 AI 칩 생산과 테스트 소켓 역할의 연결을 추가 검토하는 관계입니다.',
    sourceRefs: ['nvidia-fy2027-q1-results'],
  }),
  relation({
    id: 'us-ai-wonik-samsung-production-review', mapId: 'us-semiconductors',
    fromCompanyId: 'ai-datacenter-wonikips', toCompanyId: 'ai-datacenter-samsung', direction: 'contextual',
    relationType: 'market-context', evidenceLevel: 'review-needed', shortLabel: '공정 장비 후보',
    explanation: '반도체 설비투자와 증착·공정 장비 역할의 연결을 추가 검토하는 관계입니다.',
    sourceRefs: ['samsung-electronics-2026-q1-dart-report', 'semi-memory-fab-outlook-q2-2026'],
  }),
  relation({
    id: 'us-ai-soulbrain-samsung-production-review', mapId: 'us-semiconductors',
    fromCompanyId: 'ai-datacenter-soulbrain', toCompanyId: 'ai-datacenter-samsung', direction: 'contextual',
    relationType: 'market-context', evidenceLevel: 'review-needed', shortLabel: '공정 소재 후보',
    explanation: '반도체 생산과 공정 소재 역할의 연결을 추가 검토하는 관계입니다.',
    sourceRefs: ['samsung-electronics-2026-q1-dart-report', 'semi-memory-fab-outlook-q2-2026'],
  }),
  relation({
    id: 'us-ai-microsoft-nvidia-demand', mapId: 'us-semiconductors',
    fromCompanyId: 'ai-datacenter-microsoft', toCompanyId: 'us-semiconductors-nvidia', direction: 'directed',
    relationType: 'demand-link', evidenceLevel: 'contextual', shortLabel: '클라우드 AI 수요',
    explanation: '클라우드 AI 서비스 확대와 가속기·서버 인프라 수요를 함께 살펴보는 산업 관계입니다.',
    sourceRefs: ['iea-energy-and-ai-2025', 'nvidia-fy2027-q1-results'],
  }),
  relation({
    id: 'us-ai-amazon-nvidia-demand', mapId: 'us-semiconductors',
    fromCompanyId: 'ai-datacenter-amazon', toCompanyId: 'us-semiconductors-nvidia', direction: 'directed',
    relationType: 'demand-link', evidenceLevel: 'contextual', shortLabel: '클라우드 AI 수요',
    explanation: '클라우드 AI 인프라 확대와 가속기·데이터센터 수요를 함께 살펴보는 산업 관계입니다.',
    sourceRefs: ['iea-energy-and-ai-2025', 'nvidia-fy2027-q1-results'],
  }),

  relation({
    id: 'datacenter-vertiv-eaton-context', mapId: 'datacenter-power-cooling',
    fromCompanyId: 'datacenter-power-vertiv', toCompanyId: 'datacenter-power-eaton', direction: 'contextual',
    relationType: 'market-context', evidenceLevel: 'contextual', shortLabel: '전력 관리 비교',
    explanation: '데이터센터 전력 안정성과 배전·전력 관리 수요에 노출된 기업을 비교하는 관계입니다.',
    sourceRefs: ['iea-energy-and-ai-2025', 'eaton-q1-2026-results'],
  }),
  relation({
    id: 'datacenter-vertiv-schneider-context', mapId: 'datacenter-power-cooling',
    fromCompanyId: 'datacenter-power-vertiv', toCompanyId: 'datacenter-power-schneider', direction: 'contextual',
    relationType: 'market-context', evidenceLevel: 'contextual', shortLabel: '에너지 관리 비교',
    explanation: '데이터센터 전력 안정성과 에너지 관리·자동화 역할을 비교하는 관계입니다.',
    sourceRefs: ['iea-energy-and-ai-2025'],
  }),
  relation({
    id: 'datacenter-vertiv-lg-infrastructure', mapId: 'datacenter-power-cooling',
    fromCompanyId: 'datacenter-power-vertiv', toCompanyId: 'datacenter-power-lg-electronics', direction: 'directed',
    relationType: 'infrastructure-link', evidenceLevel: 'contextual', shortLabel: '냉각 인프라',
    explanation: 'AI 서버 발열이 커질 때 데이터센터 열 관리와 HVAC 역할을 함께 살펴보는 관계입니다.',
    sourceRefs: ['iea-energy-and-ai-2025', 'lg-news-eco-solution-lg-electronics-showcases-ai-data-center-cooling-sol-6f61b0d8'],
  }),
  relation({
    id: 'datacenter-eaton-schneider-context', mapId: 'datacenter-power-cooling',
    fromCompanyId: 'datacenter-power-eaton', toCompanyId: 'datacenter-power-schneider', direction: 'contextual',
    relationType: 'market-context', evidenceLevel: 'contextual', shortLabel: '배전·자동화 비교',
    explanation: '배전 장비와 에너지 관리·자동화가 데이터센터 전력 흐름에서 맡는 역할을 비교합니다.',
    sourceRefs: ['iea-energy-and-ai-2025', 'eaton-q1-2026-results'],
  }),
  relation({
    id: 'datacenter-schneider-lg-infrastructure', mapId: 'datacenter-power-cooling',
    fromCompanyId: 'datacenter-power-schneider', toCompanyId: 'datacenter-power-lg-electronics', direction: 'directed',
    relationType: 'infrastructure-link', evidenceLevel: 'contextual', shortLabel: '운영 효율 인프라',
    explanation: '데이터센터 운영에서 전력 효율과 냉각 효율이 함께 요구되는 인프라 관계입니다.',
    sourceRefs: ['iea-energy-and-ai-2025', 'lg-news-eco-solution-lg-electronics-showcases-ai-data-center-cooling-sol-6f61b0d8'],
  }),

  relation({
    id: 'reconstruction-hyundai-samsung-context', mapId: 'reconstruction-infrastructure',
    fromCompanyId: 'reconstruction-hyundai-ec', toCompanyId: 'reconstruction-samsung-ct', direction: 'contextual',
    relationType: 'market-context', evidenceLevel: 'contextual', shortLabel: '대형 EPC 비교',
    explanation: '대형 인프라 발주와 EPC 역량을 비교하기 위해 함께 살펴보는 시장 관계입니다.',
    sourceRefs: ['world-bank-infrastructure-foundations-2026'],
  }),
  relation({
    id: 'reconstruction-hyundai-daewoo-context', mapId: 'reconstruction-infrastructure',
    fromCompanyId: 'reconstruction-hyundai-ec', toCompanyId: 'reconstruction-daewoo-ec', direction: 'contextual',
    relationType: 'market-context', evidenceLevel: 'contextual', shortLabel: '해외 수주 비교',
    explanation: '해외 건설·플랜트 발주와 EPC 역량을 비교하기 위해 함께 살펴보는 시장 관계입니다.',
    sourceRefs: ['world-bank-infrastructure-foundations-2026'],
  }),
  relation({
    id: 'reconstruction-hyundai-hd-infrastructure', mapId: 'reconstruction-infrastructure',
    fromCompanyId: 'reconstruction-hyundai-ec', toCompanyId: 'reconstruction-hd-infracore', direction: 'directed',
    relationType: 'infrastructure-link', evidenceLevel: 'contextual', shortLabel: '착공·장비 수요',
    explanation: '인프라 프로젝트 착공과 건설장비 수요를 같은 실행 단계에서 살펴보는 관계입니다.',
    sourceRefs: ['world-bank-infrastructure-foundations-2026'],
  }),
  relation({
    id: 'reconstruction-samsung-posco-infrastructure', mapId: 'reconstruction-infrastructure',
    fromCompanyId: 'reconstruction-samsung-ct', toCompanyId: 'reconstruction-posco-holdings', direction: 'directed',
    relationType: 'infrastructure-link', evidenceLevel: 'contextual', shortLabel: '시공·소재 수요',
    explanation: '인프라 시공과 철강·건축 소재 수요를 같은 가치사슬에서 살펴보는 관계입니다.',
    sourceRefs: ['world-bank-infrastructure-foundations-2026', 'world-bank-commodity-outlook-april-2026'],
  }),
  relation({
    id: 'reconstruction-daewoo-posco-infrastructure', mapId: 'reconstruction-infrastructure',
    fromCompanyId: 'reconstruction-daewoo-ec', toCompanyId: 'reconstruction-posco-holdings', direction: 'directed',
    relationType: 'infrastructure-link', evidenceLevel: 'contextual', shortLabel: '플랜트·소재 수요',
    explanation: '플랜트 시공과 철강·인프라 소재 수요를 같은 가치사슬에서 살펴보는 관계입니다.',
    sourceRefs: ['world-bank-infrastructure-foundations-2026', 'world-bank-commodity-outlook-april-2026'],
  }),
  relation({
    id: 'reconstruction-hd-caterpillar-context', mapId: 'reconstruction-infrastructure',
    fromCompanyId: 'reconstruction-hd-infracore', toCompanyId: 'reconstruction-caterpillar', direction: 'contextual',
    relationType: 'market-context', evidenceLevel: 'contextual', shortLabel: '중장비 시장 비교',
    explanation: '글로벌 인프라 투자와 건설장비 수요에 노출된 두 기업을 비교하는 시장 관계입니다.',
    sourceRefs: ['world-bank-infrastructure-foundations-2026'],
  }),
  relation({
    id: 'reconstruction-hyundai-caterpillar-infrastructure', mapId: 'reconstruction-infrastructure',
    fromCompanyId: 'reconstruction-hyundai-ec', toCompanyId: 'reconstruction-caterpillar', direction: 'directed',
    relationType: 'infrastructure-link', evidenceLevel: 'contextual', shortLabel: '공사·중장비 수요',
    explanation: '대형 공사 착공과 글로벌 중장비 수요를 같은 인프라 흐름에서 살펴보는 관계입니다.',
    sourceRefs: ['world-bank-infrastructure-foundations-2026'],
  }),

  relation({
    id: 'cluster-hyundai-samsung-context', mapId: 'semiconductor-cluster-infrastructure',
    fromCompanyId: 'cluster-hyundai-ec', toCompanyId: 'cluster-samsung-ct', direction: 'contextual',
    relationType: 'market-context', evidenceLevel: 'contextual', shortLabel: '산업시설 EPC 비교',
    explanation: '대형 반도체·산업시설 EPC 역량을 비교하기 위해 함께 살펴보는 시장 관계입니다.',
    sourceRefs: ['semi-memory-fab-outlook-q2-2026', 'molit-work-plan-2026'],
  }),
  relation({
    id: 'cluster-hyundai-dongyang-infrastructure', mapId: 'semiconductor-cluster-infrastructure',
    fromCompanyId: 'cluster-hyundai-ec', toCompanyId: 'cluster-dongyang-pile', direction: 'directed',
    relationType: 'infrastructure-link', evidenceLevel: 'contextual', shortLabel: '기초 공사 수요',
    explanation: '산업시설 시공과 PHC 파일을 포함한 기초 공사 수요를 함께 살펴보는 관계입니다.',
    sourceRefs: ['semi-memory-fab-outlook-q2-2026', 'kind-krx-20260318002468'],
  }),
  relation({
    id: 'cluster-samsung-dongyang-infrastructure', mapId: 'semiconductor-cluster-infrastructure',
    fromCompanyId: 'cluster-samsung-ct', toCompanyId: 'cluster-dongyang-pile', direction: 'directed',
    relationType: 'infrastructure-link', evidenceLevel: 'contextual', shortLabel: '기초 공사 수요',
    explanation: '산업시설 EPC와 PHC 파일을 포함한 기초 공사 수요를 함께 살펴보는 관계입니다.',
    sourceRefs: ['semi-memory-fab-outlook-q2-2026', 'kind-krx-20260318002468'],
  }),
  relation({
    id: 'cluster-hyundai-ls-infrastructure', mapId: 'semiconductor-cluster-infrastructure',
    fromCompanyId: 'cluster-hyundai-ec', toCompanyId: 'cluster-ls-electric', direction: 'directed',
    relationType: 'infrastructure-link', evidenceLevel: 'contextual', shortLabel: '배전 설비 수요',
    explanation: '공장 건설과 배전·자동화 설비 수요를 같은 산업시설 흐름에서 살펴보는 관계입니다.',
    sourceRefs: ['semi-memory-fab-outlook-q2-2026', 'iea-electricity-2026'],
  }),
  relation({
    id: 'cluster-samsung-hyosung-infrastructure', mapId: 'semiconductor-cluster-infrastructure',
    fromCompanyId: 'cluster-samsung-ct', toCompanyId: 'cluster-hyosung-heavy', direction: 'directed',
    relationType: 'infrastructure-link', evidenceLevel: 'contextual', shortLabel: '전력망 설비 수요',
    explanation: '산업시설 건설과 변압기·전력망 설비 수요를 같은 기반시설 흐름에서 살펴보는 관계입니다.',
    sourceRefs: ['semi-memory-fab-outlook-q2-2026', 'iea-electricity-2026'],
  }),
  relation({
    id: 'cluster-ls-hyosung-context', mapId: 'semiconductor-cluster-infrastructure',
    fromCompanyId: 'cluster-ls-electric', toCompanyId: 'cluster-hyosung-heavy', direction: 'contextual',
    relationType: 'market-context', evidenceLevel: 'contextual', shortLabel: '전력설비 비교',
    explanation: '배전·자동화와 변압기·전력망 설비 역할을 비교하기 위해 함께 살펴보는 시장 관계입니다.',
    sourceRefs: ['iea-electricity-2026'],
  }),
  relation({
    id: 'cluster-hyundai-kcc-infrastructure', mapId: 'semiconductor-cluster-infrastructure',
    fromCompanyId: 'cluster-hyundai-ec', toCompanyId: 'cluster-kcc', direction: 'directed',
    relationType: 'infrastructure-link', evidenceLevel: 'contextual', shortLabel: '건축 소재 수요',
    explanation: '공장 건설과 도료·실란트 등 건축 소재 수요를 같은 산업시설 흐름에서 살펴보는 관계입니다.',
    sourceRefs: ['semi-memory-fab-outlook-q2-2026', 'kind-krx-20260515001457'],
  }),
  relation({
    id: 'cluster-samsung-kcc-infrastructure', mapId: 'semiconductor-cluster-infrastructure',
    fromCompanyId: 'cluster-samsung-ct', toCompanyId: 'cluster-kcc', direction: 'directed',
    relationType: 'infrastructure-link', evidenceLevel: 'contextual', shortLabel: '산업시설 소재 수요',
    explanation: '산업시설 EPC와 건축·산업용 소재 수요를 같은 건설 흐름에서 살펴보는 관계입니다.',
    sourceRefs: ['semi-memory-fab-outlook-q2-2026', 'kind-krx-20260515001457'],
  }),
];
