import type { DailyMarketAsset } from './types.js';

export const dailyMarketAssets: DailyMarketAsset[] = [
  {
    id: 'kospi',
    symbol: '^KS11',
    label: '코스피',
    shortLabel: '코스피',
    group: 'index',
    format: 'index',
    market: 'KOSPI',
    currency: 'KRW',
    unitLabel: 'pt',
    valueDecimals: 2,
    provider: 'Yahoo Finance chart',
    sourceRef: 'yahoo-finance-chart-ks11',
    relationshipNote: '한국 대형주와 유가증권시장 전반의 방향을 보여줍니다.',
  },
  {
    id: 'kosdaq',
    symbol: '^KQ11',
    label: '코스닥',
    shortLabel: '코스닥',
    group: 'index',
    format: 'index',
    market: 'KOSDAQ',
    currency: 'KRW',
    unitLabel: 'pt',
    valueDecimals: 2,
    provider: 'Yahoo Finance chart',
    sourceRef: 'yahoo-finance-chart-kq11',
    relationshipNote: '성장주와 중소형주 투자 심리의 변화를 함께 보여줍니다.',
  },
  {
    id: 'sp500',
    symbol: '^GSPC',
    label: 'S&P 500',
    shortLabel: 'S&P 500',
    group: 'index',
    format: 'index',
    market: 'S&P',
    currency: 'USD',
    unitLabel: 'pt',
    valueDecimals: 2,
    provider: 'Yahoo Finance chart',
    sourceRef: 'yahoo-finance-chart-gspc',
    relationshipNote: '미국 대형주 시장의 넓은 흐름을 보여주는 대표 지수입니다.',
  },
  {
    id: 'nasdaq-composite',
    symbol: '^IXIC',
    label: '나스닥 종합',
    shortLabel: '나스닥',
    group: 'index',
    format: 'index',
    market: 'NASDAQ',
    currency: 'USD',
    unitLabel: 'pt',
    valueDecimals: 2,
    provider: 'Yahoo Finance chart',
    sourceRef: 'yahoo-finance-chart-ixic',
    relationshipNote: '기술주와 성장주 비중이 큰 미국 시장의 방향을 보여줍니다.',
  },
  {
    id: 'usd-krw',
    symbol: 'KRW=X',
    label: 'USD/KRW',
    shortLabel: '원·달러',
    group: 'macro',
    format: 'fx',
    market: 'FX',
    currency: 'KRW',
    unitLabel: '원',
    valueDecimals: 2,
    provider: 'Yahoo Finance chart',
    sourceRef: 'yahoo-finance-chart-krw-x',
    relationshipNote: '하락은 원화 강세 방향이며 외국인 자금 흐름과 수입 비용에 영향을 줄 수 있습니다.',
  },
  {
    id: 'us-10y',
    symbol: '^TNX',
    label: '미국 10년물 국채금리',
    shortLabel: '미국 10년물',
    group: 'macro',
    format: 'yield',
    market: 'US TREASURY',
    currency: 'PERCENT',
    unitLabel: '%',
    valueDecimals: 2,
    provider: 'Yahoo Finance chart',
    sourceRef: 'yahoo-finance-chart-tnx',
    relationshipNote: '장기 금리 상승은 성장주 할인율과 기업 자금조달 부담을 높일 수 있습니다.',
  },
  {
    id: 'gold',
    symbol: 'GC=F',
    label: '금 선물',
    shortLabel: '금',
    group: 'macro',
    format: 'commodity',
    market: 'COMEX',
    currency: 'USD',
    unitLabel: 'USD/트로이온스',
    valueDecimals: 2,
    provider: 'Yahoo Finance chart',
    sourceRef: 'yahoo-finance-chart-gc-f',
    unitSourceRef: 'cme-gold-contract-specs',
    relationshipNote: '실질금리, 달러, 안전자산 수요가 함께 작용하는 자산입니다.',
  },
  {
    id: 'copper',
    symbol: 'HG=F',
    label: '구리 선물',
    shortLabel: '구리',
    group: 'macro',
    format: 'commodity',
    market: 'COMEX',
    currency: 'USD',
    unitLabel: 'USD/파운드',
    valueDecimals: 3,
    provider: 'Yahoo Finance chart',
    sourceRef: 'yahoo-finance-chart-hg-f',
    unitSourceRef: 'cme-copper-contract-specs',
    relationshipNote: '제조업, 건설, 전력망 투자 흐름과 연결되는 산업 금속입니다.',
  },
  {
    id: 'wti',
    symbol: 'CL=F',
    label: 'WTI 원유 선물',
    shortLabel: 'WTI',
    group: 'macro',
    format: 'commodity',
    market: 'NYMEX',
    currency: 'USD',
    unitLabel: 'USD/배럴',
    valueDecimals: 2,
    provider: 'Yahoo Finance chart',
    sourceRef: 'yahoo-finance-chart-cl-f',
    unitSourceRef: 'cme-wti-contract-specs',
    relationshipNote: '에너지 기업 매출과 운송·화학 업종의 비용 부담에 함께 영향을 줄 수 있습니다.',
  },
];

export const dailyMarketAssetRegistry = Object.fromEntries(
  dailyMarketAssets.map((asset) => [asset.id, asset]),
) as Record<DailyMarketAsset['id'], DailyMarketAsset>;

export const dailyMarketSyncTargets = dailyMarketAssets.map(({ symbol, market }) => ({ ticker: symbol, market }));
