import type { EditorialSummary } from './types.js';

// 긴 상세 원고가 홈 bundle에 포함되지 않도록 게시 승인 시 별도 생성·검증합니다.
export const publishedEditorialSummaryIndex: EditorialSummary[] = [
  {
    kind: 'stock',
    id: 'stock-2026-07-18-netflix-guidance-disclosure-reset',
    slug: '2026-07-18-netflix-guidance-disclosure-reset',
    status: 'published',
    publishedAt: '2026-07-18',
    eventAsOf: '2026-07-16',
    priceAsOf: '2026-07-17',
    company: { name: 'Netflix, Inc.', ticker: 'NFLX', companySlug: 'netflix' },
    headline: '넷플릭스 -7.263%, 좋은 실적보다 약한 전망',
    priceMove: { value: -7.263, unit: 'percent', periodLabel: '2026년 7월 17일 미국 정규장 종가', sourceId: 'nflx-yahoo-price-2026-07-17', precision: 3 },
    directCatalyst: '2분기 매출은 13.4% 늘었지만 3분기 매출·EPS 전망이 시장 기대를 밑돌았습니다.',
    moveCharacter: 'mixed',
    cardCharacter: '기대치 재조정 + 밸류에이션 변화',
    confirmedItems: ['2분기 매출 +13.4%', '3분기 회사 매출 성장 전망 11.7%', '거래량 직전 20거래일 평균의 2.815배'],
    unconfirmedItems: ['3분기 둔화가 구조적인지', '시청시간 보고 축소가 실제 참여도 악화를 뜻하는지'],
    watchItems: ['3분기 전망 달성', '광고·가격·회원 기여', '시청시간 공시의 세분성'],
    comparison: {
      market: { name: 'S&P 500', value: -1.010, asOf: '2026-07-17', sourceId: 'sp500-reuters-2026-07-17', precision: 3 },
      sector: { name: 'XLC', value: -1.775, asOf: '2026-07-17', sourceId: 'xlc-yahoo-2026-07-17', precision: 3 },
    },
  },
  {
    kind: 'threeReads',
    id: 'wall-street-2026-07-18-capital-gate-premium',
    slug: '2026-07-18-capital-gate-premium',
    status: 'published',
    publishedAt: '2026-07-18',
    contentAsOf: '2026-07-18',
    title: '자본은 가장 좁은 관문에 프리미엄을 붙인다',
    centralQuestion: '정책·사모시장·AI 인프라의 좁은 관문이 실제 현금흐름보다 먼저 프리미엄을 받는다면, 무엇이 그 가격을 검증하거나 무너뜨리는가?',
    commonThread: '결제·회수·추론의 좁은 관문을 차지한 주체가 먼저 프리미엄을 받지만 실제 현금흐름은 별도의 검증을 통과해야 합니다.',
    oneLineTakeaway: '관문을 장악한 프리미엄은 크지만, 거래량·회수·가동률로 검증되지 않은 가격은 아직 현금흐름이 아닙니다.',
    relatedCompanySlugs: [],
    readHeadlines: ['PIX와 통상정책', 'VC의 회수 관문', 'Etched의 추론 프리미엄'],
    readSummaries: [
      '생활 결제의 기본 관문이 국가 간 통상 협상의 대상이 됐습니다.',
      '사모 평가액은 IPO·세컨더리와 LP 분배를 거쳐야 실현수익이 됩니다.',
      '양산 전 프리미엄은 출하·가동률·수율·총마진으로 검증돼야 합니다.',
    ],
  },
  {
    kind: 'threeReads',
    id: 'three-reads-2026-07-17-standards-set-price',
    slug: '2026-07-17-standards-set-price',
    status: 'published',
    publishedAt: '2026-07-17',
    contentAsOf: '2026-07-17',
    title: '먼저 고정한 표준이 가격을 정한다',
    centralQuestion: '누가 자본·브랜드·코드를 시장의 기준점으로 먼저 고정해 다음 가격과 협상력을 가져가는가?',
    commonThread: '자본·상품·코드를 반복 가능한 계약과 선택의 표준으로 먼저 고정하는 쪽이 협상력을 얻습니다.',
    oneLineTakeaway: '큰 숫자보다 먼저 봐야 할 것은 그 숫자를 시장의 반복 가능한 기준으로 고정하는 계약과 전환율입니다.',
    relatedCompanySlugs: [],
    readHeadlines: ['희토류 공급망', 'Burberry', 'Kimi K3'],
    readSummaries: [
      '정부금융과 장기 오프테이크가 미래 생산량을 먼저 묶습니다.',
      '브랜드 회복이 정상가 판매와 재구매로 이어지는지 확인해야 합니다.',
      '성능·가격·공개 범위가 AI 모델의 새로운 기준이 될 수 있습니다.',
    ],
  },
];
