import type { EditorialSummary } from './types.js';

// 긴 상세 원고가 홈 bundle에 포함되지 않도록 게시 승인 시 별도 생성·검증합니다.
export const publishedEditorialSummaryIndex: EditorialSummary[] = [
  {
    kind: 'stock',
    id: 'stock-2026-07-25-intel-earnings-capex-reversal',
    slug: '2026-07-25-intel-earnings-capex-reversal',
    status: 'published',
    publishedAt: '2026-07-25',
    eventAsOf: '2026-07-23',
    priceAsOf: '2026-07-24',
    company: { name: 'Intel Corporation', ticker: 'INTC' },
    headline: '인텔, 왜 -7.892% 움직였을까?',
    priceMove: { value: -7.892, unit: 'percent', periodLabel: '2026년 7월 24일 미국 정규장 종가', sourceId: 'intel-yahoo-price-2026-07-24', precision: 3 },
    directCatalyst: 'Q2 실적과 Q3 전망은 기대를 웃돌았지만 2026년 자본지출 전망이 $20B로 높아지고 Foundry 적자가 지속됐습니다.',
    moveCharacter: 'mixed',
    cardCharacter: '영업 개선 속 기대치 재조정',
    confirmedItems: ['Q2 매출 $16.128B', '2026년 자본지출 전망 $20B', 'Foundry 영업손실 $2.089B'],
    unconfirmedItems: ['14A 고객 논의의 실제 계약 전환', '투자 확대의 자본비용 초과 수익률'],
    watchItems: ['Q3 가이던스 달성', 'Foundry 손실', 'CapEx와 현금흐름'],
    comparison: {
      market: { name: 'S&P 500', value: 0.050, asOf: '2026-07-24', sourceId: 'intel-ap-market-2026-07-24', precision: 3 },
      sector: { name: 'SOXX', value: -4.396, asOf: '2026-07-24', sourceId: 'intel-soxx-price-2026-07-24', precision: 3 },
    },
  },
  {
    kind: 'threeReads',
    id: 'wall-street-2026-07-25-switching-costs',
    slug: '2026-07-25-switching-costs',
    status: 'published',
    publishedAt: '2026-07-25',
    contentAsOf: '2026-07-25',
    title: '비용을 낮추는 힘은 대체 가능성에서 나온다',
    centralQuestion: '공급·거래·모델의 대체 가능성이 커질 때 누가 가격을 낮추고, 누가 전환비용과 지연비용을 떠안는가?',
    commonThread: 'Apple의 조달, Paramount–WBD의 거래 지연, 기업 AI의 모델 라우팅은 대안이 실제 전환 가능할 때 협상력이 이동한다는 점을 보여줍니다.',
    oneLineTakeaway: '싸진 가격보다 먼저 볼 것은 실제로 갈아탈 수 있는 선택지와 그 전환비용이다.',
    relatedCompanySlugs: [],
    readHeadlines: [
      'Apple의 메모리 선택권이 미국 산업정책과 충돌했다',
      'Paramount–Warner Bros. 합병은 법정에서 시간이 비용으로 바뀌었다',
      '기업 AI 구매가 ‘최고 모델 한 개’에서 ‘업무별 라우팅’으로 이동했다',
    ],
    readSummaries: [
      '허용되는 공급사가 늘면 조달 협상력이 회복될 수 있지만 정책·인증·계약을 통과해야 합니다.',
      '거래 종결 지연은 ticking fee·자금조달 유지비·통합 지연을 통해 시너지의 현재가치를 낮춥니다.',
      '업무별 모델 라우팅은 단가를 낮출 수 있지만 재작업·보안·운영비를 포함한 완결비용으로 검증해야 합니다.',
    ],
  },
  {
    kind: 'stock',
    id: 'stock-2026-07-22-smci-orders-margin',
    slug: '2026-07-22-smci-orders-margin',
    status: 'published',
    publishedAt: '2026-07-24',
    eventAsOf: '2026-07-21',
    priceAsOf: '2026-07-22',
    company: { name: 'Super Micro Computer, Inc.', ticker: 'SMCI', companySlug: 'supermicro' },
    headline: 'SMCI +19.843%, 주문과 마진 기대의 동시 변화',
    priceMove: { value: 19.843, unit: 'percent', periodLabel: '2026년 7월 22일 미국 정규장 종가', sourceId: 'smci-yahoo-price-2026-07-22', precision: 3 },
    directCatalyst: '회사는 4분기 신규 주문 600억달러 초과와 예비 매출총이익률 15~17%를 발표했습니다.',
    moveCharacter: 'mixed',
    cardCharacter: '주문 확대 + 예비 마진 회복',
    confirmedItems: ['신규 주문 >$60B', '예비 매출총이익률 15~17%', '거래량 20일 평균의 3.919배'],
    unconfirmedItems: ['주문의 확정성과 출하 시점', '예비 마진의 최종 달성·지속성'],
    watchItems: ['8월 11일 최종 실적', '주문 확정·출하', '재고·매입채무·현금흐름'],
    comparison: {
      market: { name: 'Nasdaq Composite', value: -0.566, asOf: '2026-07-22', sourceId: 'nasdaq-yahoo-price-2026-07-22', precision: 3 },
      sector: { name: 'SOXX', value: 0.512, asOf: '2026-07-22', sourceId: 'soxx-yahoo-price-2026-07-22', precision: 3 },
    },
  },
  {
    kind: 'threeReads',
    id: 'wall-street-2026-07-23-option-cost',
    slug: '2026-07-23-option-cost',
    status: 'published',
    publishedAt: '2026-07-24',
    contentAsOf: '2026-07-23',
    title: '선택권은 공짜가 아니다',
    centralQuestion: '결정을 미루고 선택지를 남겨두는 동안 그 비용은 누구의 현금흐름에 쌓이는가?',
    commonThread: '군사적 선택, 사모자산의 매각 연기, 농축 가능성은 모두 시간을 벌지만 비용을 다른 주체의 현금흐름으로 넘깁니다.',
    oneLineTakeaway: '좋은 선택권은 퇴로가 있는 선택권이다. 퇴로 없이 결정을 미루면 선택권은 자산이 아니라 비용이 된다.',
    relatedCompanySlugs: [],
    readHeadlines: ['장기금리가 청구하는 선택 비용', '매각을 미룬 대가가 LP에 쌓인다', '농축 선택권과 검증 비용'],
    readSummaries: [
      '10년물 4.711%는 정책·전쟁 불확실성을 가계와 기업의 조달비용으로 전달합니다.',
      '오래된 사모자산은 매각을 미루는 동안 LP의 분배와 기관 유동성을 묶습니다.',
      '농축 가능성은 원전 참여 기회와 함께 검증·비확산 비용을 남깁니다.',
    ],
  },
  {
    kind: 'stock',
    id: 'stock-2026-07-18-netflix-guidance-disclosure-reset',
    slug: '2026-07-18-netflix-guidance-disclosure-reset',
    status: 'published',
    publishedAt: '2026-07-18',
    eventAsOf: '2026-07-16',
    priceAsOf: '2026-07-17',
    company: { name: 'Netflix, Inc.', ticker: 'NFLX', companySlug: 'netflix' },
    headline: '넷플릭스 -7.263%, 좋은 실적보다 약한 전망',
    priceMove: { value: -7.263, unit: 'percent', periodLabel: '2026년 7월 17일 미국 정규장 종가', sourceId: 'nflx-yahoo-price-2026-07-17', precision: 3 },
    directCatalyst: '2분기 매출은 13.4% 늘었지만 3분기 매출·EPS 전망이 시장 기대를 밑돌았습니다.',
    moveCharacter: 'mixed',
    cardCharacter: '기대치 재조정 + 밸류에이션 변화',
    confirmedItems: ['2분기 매출 +13.4%', '3분기 회사 매출 성장 전망 11.7%', '거래량 직전 20거래일 평균의 2.815배'],
    unconfirmedItems: ['3분기 둔화가 구조적인지', '시청시간 보고 축소가 실제 참여도 악화를 뜻하는지'],
    watchItems: ['3분기 전망 달성', '광고·가격·회원 기여', '시청시간 공시의 세분성'],
    comparison: {
      market: { name: 'S&P 500', value: -1.010, asOf: '2026-07-17', sourceId: 'sp500-reuters-2026-07-17', precision: 3 },
      sector: { name: 'XLC', value: -1.775, asOf: '2026-07-17', sourceId: 'xlc-yahoo-2026-07-17', precision: 3 },
    },
  },
  {
    kind: 'threeReads',
    id: 'wall-street-2026-07-18-capital-gate-premium',
    slug: '2026-07-18-capital-gate-premium',
    status: 'published',
    publishedAt: '2026-07-18',
    contentAsOf: '2026-07-18',
    title: '자본은 가장 좁은 관문에 프리미엄을 붙인다',
    centralQuestion: '정책·사모시장·AI 인프라의 좁은 관문이 실제 현금흐름보다 먼저 프리미엄을 받는다면, 무엇이 그 가격을 검증하거나 무너뜨리는가?',
    commonThread: '결제·회수·추론의 좁은 관문을 차지한 주체가 먼저 프리미엄을 받지만 실제 현금흐름은 별도의 검증을 통과해야 합니다.',
    oneLineTakeaway: '관문을 장악한 프리미엄은 크지만, 거래량·회수·가동률로 검증되지 않은 가격은 아직 현금흐름이 아닙니다.',
    relatedCompanySlugs: [],
    readHeadlines: ['PIX와 통상정책', 'VC의 회수 관문', 'Etched의 추론 프리미엄'],
    readSummaries: [
      '생활 결제의 기본 관문이 국가 간 통상 협상의 대상이 됐습니다.',
      '사모 평가액은 IPO·세컨더리와 LP 분배를 거쳐야 실현수익이 됩니다.',
      '양산 전 프리미엄은 출하·가동률·수율·총마진으로 검증돼야 합니다.',
    ],
  },
  {
    kind: 'threeReads',
    id: 'three-reads-2026-07-17-standards-set-price',
    slug: '2026-07-17-standards-set-price',
    status: 'published',
    publishedAt: '2026-07-17',
    contentAsOf: '2026-07-17',
    title: '먼저 고정한 표준이 가격을 정한다',
    centralQuestion: '누가 자본·브랜드·코드를 시장의 기준점으로 먼저 고정해 다음 가격과 협상력을 가져가는가?',
    commonThread: '자본·상품·코드를 반복 가능한 계약과 선택의 표준으로 먼저 고정하는 쪽이 협상력을 얻습니다.',
    oneLineTakeaway: '큰 숫자보다 먼저 봐야 할 것은 그 숫자를 시장의 반복 가능한 기준으로 고정하는 계약과 전환율입니다.',
    relatedCompanySlugs: [],
    readHeadlines: ['희토류 공급망', 'Burberry', 'Kimi K3'],
    readSummaries: [
      '정부금융과 장기 오프테이크가 미래 생산량을 먼저 묶습니다.',
      '브랜드 회복이 정상가 판매와 재구매로 이어지는지 확인해야 합니다.',
      '성능·가격·공개 범위가 AI 모델의 새로운 기준이 될 수 있습니다.',
    ],
  },
];
