import type { StockAutopsyPick } from '../../data.js';

export const stockAutopsyPickEntries: StockAutopsyPick[] = [
  {
    id: 'pick-dongyang-pile-semiconductor-cluster-infrastructure',
    pickId: 'pick-dongyang-pile-semiconductor-cluster-infrastructure',
    title: '반도체 회사가 아닌데 동양파일은 왜 상한가를 갔을까요?',
    companyName: '동양파일',
    ticker: '228340.KQ',
    market: 'KR',
    movementDirection: 'up',
    movementLabel: '호남권 반도체 클러스터 기대 / 6월 26일 +29.91%',
    reasonSummary: '동양파일은 2026년 6월 26일 공개 차트 종가 기준 2,845원으로 전일 대비 29.91% 올랐습니다. 시장은 호남권 반도체 클러스터 추진 보도와 산업단지 인프라 기대를 PHC 파일 업체인 동양파일에 연결해 봤지만, 예산·착공·공급계약이 확정된 직접 수주로 보기는 어렵습니다.',
    beginnerSummary: '반도체 회사가 아니라, 반도체 공장과 산업단지를 짓기 전에 땅속 기초를 받치는 콘크리트 파일 기대가 붙은 사례입니다.',
    sector: 'KOSDAQ · 정책 기대 / 산업단지 인프라',
    flowLabel: '반도체 클러스터 / 인프라 기대',
    flowStage: 'PHC 파일 / 기초공사',
    valueChainPosition: 'materials',
    connectedLeaders: ['정부·지자체 정책', '산업단지 인프라', '건설 발주'],
    relatedCompanies: ['공장 건설', '토목·기초공사', 'PHC 파일 수요'],
    relatedTradeTags: ['PHC 파일', '산업단지 인프라', '정책 기대'],
    oneLineConclusion: '반도체 칩이 생산되기 전에 공장을 받칠 콘크리트 파일이 먼저 필요하다는 기대가 붙은 것입니다.',
    beginnerExplanation: '동양파일은 반도체를 만드는 회사가 아닙니다. 회사 공시와 사업 설명에서 확인되는 핵심은 건설공사의 기초자재인 PHC 파일입니다. 공장, 대형 건축물, 산업단지 같은 프로젝트가 실제 발주되고 착공돼야 파일 수요가 매출과 이익으로 연결될 수 있습니다.',
    watchMetrics: [
      { label: '정책 확정', note: '호남권 반도체 클러스터가 정부·지자체 공식 계획과 예산으로 구체화되는지 봅니다.' },
      { label: '착공 일정', note: '산업단지, 공장, 도로, 전력 인프라의 일정과 발주 방식이 정해지는지 확인합니다.' },
      { label: '공급계약', note: '동양파일이 실제 PHC 파일 공급계약을 따냈는지 공시와 원문으로 확인합니다.' },
    ],
    goodSignals: [
      '공식 계획, 예산, 착공 일정이 구체화',
      '동양파일의 직접 공급계약이나 수주 공시 확인',
      'PHC 파일 수요가 매출과 영업이익으로 연결',
    ],
    cautionSignals: [
      '정책 기대가 보도와 시장 해석에 머무름',
      '직접 수주 없이 테마성 과열만 커짐',
      '건설 경기 둔화와 원가 부담으로 이익 연결이 지연',
    ],
    sourceLinks: [
      {
        label: '동양파일 2025 사업보고서',
        url: 'https://kind.krx.co.kr/common/disclsviewer.do?acptno=20260318002468&langTpCd=0&method=search&orgid=F&rcpno=20260318001680&tran=Y',
        note: 'KIND 공시에서 동양파일의 228340 종목 코드와 PHC 파일 사업, 건설 기초자재 성격을 확인합니다.',
        type: 'company-filing',
        publisher: '한국거래소 KIND',
      },
      {
        label: '동양파일 2026년 1분기 분기보고서',
        url: 'https://kind.krx.co.kr/common/disclsviewer.do?acptno=20260515000989&docno=&method=search&viewerhost=',
        note: '최근 분기 공시 기준으로 사업과 재무 확인에 사용합니다.',
        type: 'company-filing',
        publisher: '한국거래소 KIND',
      },
      {
        label: 'SBS Biz 호남권 반도체 클러스터 관련주 시황',
        url: 'https://v.daum.net/v/20260626094305527',
        note: '동양파일 6월 26일 상한가와 호남권 반도체 클러스터 관련 기대는 공개 보도 기준으로만 참고합니다.',
        type: 'news',
        publisher: 'SBS Biz',
      },
      {
        label: 'Yahoo Finance 228340.KQ 공개 차트',
        url: 'https://query1.finance.yahoo.com/v8/finance/chart/228340.KQ?range=5d&interval=1d',
        note: '6월 24일 2,410원(+29.92%)과 6월 26일 2,845원(+29.91%) 종가 계산에 사용한 공개 차트 데이터입니다.',
        type: 'news',
        publisher: 'Yahoo Finance',
      },
    ],
    publishedAt: '2026-06-26',
    status: 'published',
  },
  {
    id: 'pick-kcc-silicone-margin-asset-value',
    pickId: 'pick-kcc-silicone-margin-asset-value',
    title: 'KCC는 페인트 회사인데 왜 실리콘과 자산가치가 중요할까요?',
    companyName: 'KCC',
    ticker: '002380.KS',
    market: 'KR',
    movementDirection: 'up',
    movementLabel: '실적·자산가치 재평가 / 6월 25일 +11.27%',
    reasonSummary: 'KCC는 2026년 6월 25일 공개 차트 종가 기준 533,000원으로 전일 대비 11.27% 올랐습니다. 공개 보도에서는 실리콘 사업 수익성 회복, 도료 사업 이익, 투자자산 가치와 주주환원 기대가 함께 거론됐습니다.',
    beginnerSummary: 'KCC는 페인트만 보는 회사가 아니라 실리콘, 도료, 건자재와 보유 투자자산을 함께 봐야 하는 종합 소재 기업에 가깝습니다.',
    sector: 'KOSPI · 실적 회복 / 자산가치',
    flowLabel: '소재 / 실리콘 / 자산가치',
    flowStage: '실리콘·도료 이익 / 투자자산 재평가',
    valueChainPosition: 'materials',
    connectedLeaders: ['실리콘 사업', '도료 사업', '투자자산 가치'],
    relatedCompanies: ['자동차·조선 도료 수요', '건축자재 수요', '보유 투자자산'],
    relatedTradeTags: ['실리콘 마진', '도료 이익', '주주환원'],
    oneLineConclusion: '본업 회복 기대와 보유 자산가치 재평가가 동시에 주가를 끌어올린 것입니다.',
    beginnerExplanation: 'KCC는 건축용 도료 이미지가 강하지만 자동차·선박·전자·건축에 들어가는 소재 사업도 함께 운영합니다. 공개 보도에서 신한투자증권의 목표주가 75만원 신규 제시와 실리콘·도료 중심 전망이 확인되지만, 이는 증권사 전망이며 실제 실적과 현금흐름, 배당·자사주 같은 주주환원이 뒤따르는지 따로 봐야 합니다.',
    watchMetrics: [
      { label: '실리콘 마진', note: '가격 반등, 원가 안정, 고부가 제품 확대가 실제 이익으로 이어지는지 확인합니다.' },
      { label: '도료 이익', note: '자동차, 조선, 건축 수요가 도료 사업 이익을 유지하는지 봅니다.' },
      { label: '주주환원', note: '보유 투자자산 가치가 배당, 자사주 소각 등 실제 환원 정책으로 연결되는지 확인합니다.' },
    ],
    goodSignals: [
      '실리콘 사업 수익성이 분기 실적으로 회복',
      '자동차·조선·건축용 도료 이익이 유지',
      '공개된 주주환원 정책이 실제 집행',
    ],
    cautionSignals: [
      '실리콘 가격 회복이 일시적 기대에 그침',
      '보유자산 가치가 곧바로 주주가치로 연결되지 않음',
      '증권사 전망과 실제 실적 사이의 간격 확대',
    ],
    sourceLinks: [
      {
        label: 'KCC 2026년 1분기 분기보고서',
        url: 'https://kind.krx.co.kr/common/disclsviewer.do?acptno=20260515001457&docno=&method=search&viewerhost=',
        note: 'KCC의 002380 종목 코드, 사업 부문, 재무와 투자자산은 KIND 공시 기준으로 확인합니다.',
        type: 'company-filing',
        publisher: '한국거래소 KIND',
      },
      {
        label: '매일경제 KCC 실적·자산가치 보도',
        url: 'https://stock.mk.co.kr/news/view/1110153',
        note: '신한투자증권의 목표주가 75만원 신규 제시와 실리콘·도료·투자자산 가치 기대는 공개 보도 기준으로만 참고합니다.',
        type: 'news',
        publisher: '매일경제',
      },
      {
        label: '머니투데이 KCC 실리콘·도료 전망 보도',
        url: 'https://www.mt.co.kr/amp/stock/2026/06/25/2026062508592086578',
        note: '실리콘 하반기 수익성 전망과 투자자산·주주환원 기대를 보조 확인합니다.',
        type: 'news',
        publisher: '머니투데이',
      },
      {
        label: 'Yahoo Finance 002380.KS 공개 차트',
        url: 'https://query1.finance.yahoo.com/v8/finance/chart/002380.KS?range=5d&interval=1d',
        note: '6월 25일 533,000원(+11.27%)과 6월 26일 494,500원(-7.22%) 종가 계산에 사용한 공개 차트 데이터입니다.',
        type: 'news',
        publisher: 'Yahoo Finance',
      },
    ],
    publishedAt: '2026-06-25',
    status: 'published',
  },
  {
    id: 'pick-hertz-used-car-depreciation-financing',
    pickId: 'pick-hertz-used-car-depreciation-financing',
    title: '렌터카 이용객이 줄어서 Hertz가 폭락한 걸까요?',
    companyName: 'Hertz',
    ticker: 'HTZ',
    market: 'US',
    movementDirection: 'down',
    movementLabel: '자금조달·잔존가치 부담 / 6월 24일 -40.71%',
    reasonSummary: 'Hertz는 2026년 6월 24일 공개 차트 종가 기준 5.06달러에서 3.00달러로 40.71% 하락했습니다. 이번 주가를 직접 흔든 것은 PIK 채권과 주식 관련 자금조달 조건, 그리고 낮아진 실적 눈높이였습니다. 중고차 가격과 차량 잔존가치는 사업의 구조적 부담으로 따로 봅니다.',
    beginnerSummary: '렌터카 회사는 차를 빌려주는 매출뿐 아니라, 나중에 차를 되팔 때 남는 가치와 부채 비용까지 함께 봐야 합니다.',
    sector: 'NASDAQ · 감가상각 / 자금조달',
    flowLabel: '렌터카 / 차량 잔존가치 / 부채',
    flowStage: 'PIK 채권 / 주식 관련 자금조달',
    valueChainPosition: 'leader',
    connectedLeaders: ['PIK 채권', '주식 관련 자금조달', '차량 잔존가치'],
    relatedCompanies: ['중고차 가격', '차량 감가상각비', '부채 만기'],
    relatedTradeTags: ['PIK notes', 'share lending', 'depreciation'],
    oneLineConclusion: '차를 빌려주는 사업뿐 아니라 차를 되팔 때 남는 가치와 부채 비용까지 함께 봐야 합니다.',
    beginnerExplanation: 'Hertz는 6월 24일 3억 달러 규모 PIK 채권 제안과 1억 달러 규모 보통주 대여 주식 공모를 발표했고, 6월 25일에는 PIK 채권 규모를 3억5천만 달러로 키워 6.75% 조건으로 가격을 확정했습니다. 같은 공시 흐름에서 3,703만7,037주를 주당 2.70달러에 가격 확정했습니다. 이 조건은 부채 비용과 기존 주주 희석 가능성을 동시에 보게 만들었습니다.',
    watchMetrics: [
      { label: 'PIK 이자', note: '현금 이자와 PIK 이자가 부채 부담을 어떻게 키우는지 확인합니다.' },
      { label: '희석 가능성', note: '교환 가능 주식과 대여 주식 구조가 기존 주주에게 어떤 영향을 주는지 봅니다.' },
      { label: '차량 감가상각', note: '중고차 가격과 잔존가치가 차량 처분 손실과 감가상각비에 미치는 영향을 확인합니다.' },
    ],
    goodSignals: [
      '자금조달 이후 유동성 우려 완화',
      '중고차 가격과 차량 잔존가치 안정',
      '차량당 매출과 수요가 유지되며 감가상각 부담 축소',
    ],
    cautionSignals: [
      'PIK 이자와 부채 만기 부담 확대',
      '주식 또는 주식연계 조달로 희석 가능성 확대',
      '중고차 가격 약세로 차량 처분 손실과 감가상각비 부담 지속',
    ],
    sourceLinks: [
      {
        label: 'Hertz 3억 달러 PIK 채권 제안 발표',
        url: 'https://newsroom.hertz.com/press-releases/press-release-details/hertz-announces-proposed-offering-of-300-million-of-exchangeable-senior-first-lien-secured-pik-notes/',
        note: '3억 달러 PIK 채권, 2030년 만기, 보통주 교환 가능성, 19.9% 한도와 동시 주식 공모 구조를 확인합니다.',
        type: 'official-announcement',
        publisher: 'Hertz',
      },
      {
        label: 'Hertz 3억5천만 달러 PIK 채권 가격 확정',
        url: 'https://newsroom.hertz.com/press-releases/press-release-details/hertz-announces-pricing-of-upsized-350-million-of-exchangeable-senior-first-lien-secured-pik-notes/',
        note: '6.75% PIK 채권, 현금 3.375%와 PIK 3.375%, 2030년 7월 1일 만기, 최초 교환가 3.58달러를 확인합니다.',
        type: 'official-announcement',
        publisher: 'Hertz',
      },
      {
        label: 'Hertz 보통주 37,037,037주 가격 확정',
        url: 'https://newsroom.hertz.com/press-releases/press-release-details/hertz-announces-pricing-of-offering-of-37037037-shares-of-common-stock/',
        note: '주당 2.70달러, 주식 대여 구조, 회사가 공모 대금을 직접 받지 않는다는 조건을 확인합니다.',
        type: 'official-announcement',
        publisher: 'Hertz',
      },
      {
        label: 'SEC Hertz 보통주 공모 설명서',
        url: 'https://www.sec.gov/Archives/edgar/data/0001657853/000110465926077051/tm2618542-1_s3asr.htm',
        note: '1억 달러 규모 보통주 대여 공모 구조와 SEC 등록 문서를 확인합니다.',
        type: 'company-filing',
        publisher: 'SEC',
      },
      {
        label: 'Hertz 2026년 1분기 10-Q',
        url: 'https://www.sec.gov/Archives/edgar/data/1657853/000165785326000024/htzz-20260331.htm',
        note: '부채, 차량 금융, 차량 감가상각과 잔존가치 부담을 회사 공시 기준으로 확인합니다.',
        type: 'company-filing',
        publisher: 'SEC',
      },
      {
        label: 'Yahoo Finance HTZ 공개 차트',
        url: 'https://query1.finance.yahoo.com/v8/finance/chart/HTZ?range=5d&interval=1d',
        note: '6월 24일 종가 3.00달러와 전일 5.06달러 기준 -40.71% 계산에 사용한 공개 차트 데이터입니다.',
        type: 'news',
        publisher: 'Yahoo Finance',
      },
    ],
    publishedAt: '2026-06-24',
    status: 'published',
  },
  {
    id: 'pick-jeju-semiconductor-export-fabless-rally',
    pickId: 'pick-jeju-semiconductor-export-fabless-rally',
    title: '반도체가 좋아지면 삼성전자와 SK하이닉스만 오를까요?',
    companyName: '제주반도체',
    ticker: '080220.KQ',
    market: 'KR',
    movementDirection: 'up',
    movementLabel: '반도체 수출 호조 / 6월 22일 +17.24%',
    reasonSummary: '제주반도체는 2026년 6월 22일 공개 차트 종가 기준 134,000원으로 전 거래일 대비 17.24% 올랐습니다. 관세청의 6월 1~20일 반도체 수출 호조가 공개되자 시장에서는 대형 반도체주뿐 아니라 중소형 팹리스·설계 기업까지 관심이 확산된 것으로 해석했습니다.',
    beginnerSummary: '제주반도체는 직접 공장을 운영하는 회사가 아니라 모바일·IoT·전장용 저전력 메모리를 설계하고 생산은 외부에 맡기는 팹리스 기업입니다.',
    sector: 'KOSDAQ · 반도체 업황 / 팹리스',
    flowLabel: '팹리스 / 저전력 메모리',
    flowStage: '저전력 메모리 설계 / 외부 위탁생산',
    valueChainPosition: 'supplier',
    connectedLeaders: ['모바일 기기', 'IoT', '전장'],
    relatedCompanies: ['저전력 메모리', '외부 파운드리', '반도체 수출'],
    relatedTradeTags: ['팹리스', '저전력 메모리', '수출 호조'],
    oneLineConclusion: '반도체 수출이 강해지자 시장의 관심이 대형 생산업체에서 중소형 설계 기업으로 확산된 것입니다.',
    beginnerExplanation: '삼성전자와 SK하이닉스가 대형 메모리를 대량 생산하는 회사라면, 제주반도체는 특정 기기에 맞는 저전력 메모리를 설계하는 회사에 가깝습니다. 다만 수출 호조가 곧바로 제주반도체의 매출과 이익 증가를 뜻하는 것은 아니어서 실제 실적 확인이 필요합니다.',
    watchMetrics: [
      { label: '반도체 수출', note: '관세청·산업부 수출 호조가 계속 이어지는지 봅니다.' },
      { label: '제품 수요', note: '모바일, IoT, 전장용 저전력 메모리 수요가 실제 매출로 연결되는지 확인합니다.' },
      { label: '실적 검증', note: '업황 기대가 매출, 영업이익, 현금흐름에 반영되는지 봅니다.' },
    ],
    goodSignals: [
      '반도체 수출 호조와 업황 회복이 지속',
      '저전력 메모리 제품 수요가 실제 매출 증가로 연결',
      '외부 위탁생산 구조에서도 마진이 유지',
    ],
    cautionSignals: [
      '수출 호조가 개별 회사 실적으로 바로 연결되지 않음',
      '중소형 반도체주 수급이 과열',
      '모바일·IoT·전장 수요 회복이 기대보다 느림',
    ],
    sourceLinks: [
      {
        label: '제주반도체 2025 사업보고서',
        url: 'https://kind.krx.co.kr/common/disclsviewer.do?acptno=20260323001354&docno=&method=search&viewerhost=',
        note: '080220 종목 코드, 팹리스 사업 구조, 저전력 메모리 제품과 외부 위탁생산 구조를 확인합니다.',
        type: 'company-filing',
        publisher: '한국거래소 KIND',
      },
      {
        label: '관세청 2026년 6월 1~20일 수출입 현황',
        url: 'https://www.customs.go.kr/kcs/na/ntt/selectNttInfo.do?nttSn=10167371&nttSnUrl=d3dc345ca30751d2b28d06b45adfbc2b',
        note: '6월 1~20일 반도체 수출 255억 달러와 동기간 역대 최대 수치를 확인합니다.',
        type: 'official-announcement',
        publisher: '관세청',
      },
      {
        label: '제주반도체 반도체 수출 호조 보도',
        url: 'https://news.nate.com/view/20260622n11074?mid=n1101',
        note: '반도체 수출 호조와 중소형 반도체주 매수세 확산은 공개 보도 기준으로만 참고합니다.',
        type: 'news',
        publisher: '이투데이',
      },
      {
        label: 'Yahoo Finance 080220.KQ 공개 차트',
        url: 'https://query1.finance.yahoo.com/v8/finance/chart/080220.KQ?range=5d&interval=1d',
        note: '6월 22일 134,000원(+17.24%) 종가 계산에 사용한 공개 차트 데이터입니다.',
        type: 'news',
        publisher: 'Yahoo Finance',
      },
    ],
    publishedAt: '2026-06-22',
    status: 'published',
  },
  {
    id: 'pick-huntsman-olin-merger-exchange-ratio',
    pickId: 'pick-huntsman-olin-merger-exchange-ratio',
    title: 'M&A 뉴스가 나왔는데 Huntsman 주가는 왜 빠졌을까요?',
    companyName: 'Huntsman',
    ticker: 'HUN',
    market: 'US',
    movementDirection: 'down',
    movementLabel: '합병 발표 / 약 17.1% 하락',
    reasonSummary: 'Huntsman과 Olin은 2026년 6월 16일 전액 주식 교환 합병을 발표했습니다. 발표 전일 종가 기준 교환가치가 Huntsman 종가보다 낮았고, 시장은 교환비율과 승인·통합 위험을 함께 반영했습니다.',
    beginnerSummary: '합병 발표가 항상 호재는 아닙니다. 현금 인수가 아니라 상대 회사 주식을 받는 거래라면 교환비율과 상대 회사 주가가 실제 가치를 정합니다.',
    sector: 'NYSE · M&A / 합병 조건',
    flowLabel: 'M&A / 합병 조건',
    flowStage: '전액 주식 교환 / 승인 대기',
    valueChainPosition: 'leader',
    connectedLeaders: ['Olin', '주주 승인', '규제 승인'],
    relatedCompanies: ['Olin', 'Huntsman 주주', 'Olin 주주'],
    relatedTradeTags: ['0.5476주 교환', '전액 주식 합병', '2027년 상반기 종결 목표'],
    oneLineConclusion: 'M&A 뉴스는 호재가 될 수 있지만, 합병 가격과 교환 조건이 낮게 평가되면 주가는 오히려 하락할 수 있습니다.',
    beginnerExplanation: 'Huntsman 주주는 보유 1주당 Olin 0.5476주를 받습니다. 고정 현금 대가는 없고 단주에만 현금이 지급됩니다. 6월 15일 Olin 종가 25.30달러에 교환비율을 적용한 약 13.85달러는 같은 날 Huntsman 종가 15.89달러보다 약 12.8% 낮았습니다. 발표일 Huntsman 종가는 13.18달러로 약 17.1% 하락했습니다. 회사는 교환비율이 6월 12일까지의 30일 거래량가중평균가격을 기준으로 정해졌다고 설명했습니다.',
    watchMetrics: [
      { label: '교환비율 0.5476', note: 'Huntsman 1주가 Olin 0.5476주로 바뀌며, 고정 현금 대가는 없습니다.' },
      { label: '2027년 상반기', note: '양사는 주주·규제 승인 등을 전제로 이 시기 종결을 목표로 제시했습니다.' },
      { label: '발표일 약 -17.1%', note: '6월 15일 15.89달러에서 6월 16일 13.18달러로 내려간 종가 기준입니다.' },
    ],
    goodSignals: [
      '양사 주주 승인과 규제 승인이 예정대로 진행',
      '4억 달러 이상으로 제시한 비용·통합 효과가 구체화',
      '화학 업황 회복과 합병 후 현금흐름 개선',
    ],
    cautionSignals: [
      '교환 조건 변경 또는 주주 반발 확대',
      '주주·규제 승인 지연이나 거래 무산',
      '통합 비용 확대와 화학 업황 부진 지속',
    ],
    sourceLinks: [
      {
        label: 'Huntsman·Olin 공동 합병 발표',
        url: 'https://www.sec.gov/Archives/edgar/data/74303/000119312526271782/d99037dex991.htm',
        note: '발표일, 0.5476주 교환비율, 45.5%/54.5% 지분, 2027년 상반기 종결 목표와 승인 조건을 확인합니다.',
        type: 'official-announcement',
        publisher: 'Huntsman·Olin',
      },
      {
        label: 'Huntsman 합병계약 8-K',
        url: 'https://www.sec.gov/Archives/edgar/data/1307954/000110465926074683/tm2618028d1_8k.htm',
        note: '전액 주식 합병, 단주 현금 지급, 주주·규제 승인과 해지 조건을 확인합니다.',
        type: 'company-filing',
        publisher: 'SEC · Huntsman',
      },
      {
        label: 'Olin 공동 발표 8-K',
        url: 'https://www.sec.gov/Archives/edgar/data/74303/000119312526271782/d99037d8k.htm',
        note: 'Olin이 제출한 공동 발표와 투자자 자료의 SEC 공시 원문입니다.',
        type: 'company-filing',
        publisher: 'SEC · Olin',
      },
      {
        label: 'Huntsman 공개 과거 시세',
        url: 'https://www.nasdaq.com/market-activity/stocks/hun/historical',
        note: '발표 전일과 발표일 종가를 비교하는 공개 시세 자료입니다.',
        type: 'news',
        publisher: 'Nasdaq · HUN',
      },
      {
        label: 'Olin 공개 과거 시세',
        url: 'https://www.nasdaq.com/market-activity/stocks/oln/historical',
        note: '교환비율을 적용한 발표 전일의 참고 합병가치를 계산하는 공개 시세 자료입니다.',
        type: 'news',
        publisher: 'Nasdaq · OLN',
      },
    ],
    publishedAt: '2026-06-16',
    status: 'published',
  },
  {
    id: 'pick-uniqure-amt130-fda-regulatory-path',
    pickId: 'pick-uniqure-amt130-fda-regulatory-path',
    title: '신약이 승인된 것도 아닌데 uniQure 주가는 왜 급등했을까요?',
    companyName: 'uniQure',
    ticker: 'QURE',
    market: 'US',
    movementDirection: 'up',
    movementLabel: 'FDA 경로 재개 / 약 78.4% 상승',
    reasonSummary: 'uniQure는 2026년 6월 17일 FDA가 AMT-130의 3년차 1/2상 분석을 가속승인 BLA의 주된 근거로 받아들일 수 있다고 전달했다고 발표했습니다. 승인 완료가 아니라 제출과 심사로 갈 수 있는 경로가 다시 열린 뉴스입니다.',
    beginnerSummary: 'FDA가 기존 임상 데이터로 허가 신청을 검토할 수 있다고 한 단계입니다. BLA 제출, FDA 접수, 심사, 승인과 상업화는 아직 각각 남아 있습니다.',
    sector: 'NASDAQ · 바이오 / FDA 규제 경로',
    flowLabel: '바이오 / FDA 규제 경로',
    flowStage: 'BLA 제출 준비 / 가속승인 심사 전',
    valueChainPosition: 'leader',
    connectedLeaders: ['FDA', 'AMT-130', '확증시험'],
    relatedCompanies: ['FDA', '헌팅턴병 환자', '임상시험 기관'],
    relatedTradeTags: ['AMT-130', 'BLA 제출 계획', '가속승인 경로'],
    oneLineConclusion: '탈락 위기로 보였던 치료제가 FDA 재검토를 통해 다시 승인 신청 단계로 갈 가능성이 생긴 상황입니다.',
    beginnerExplanation: 'AMT-130은 헌팅턴병을 대상으로 개발 중인 유전자치료제입니다. FDA는 Type B 미팅에서 3년차 1/2상 분석을 가속승인 BLA의 주된 근거로 받아들일 수 있다고 전달했습니다. uniQure는 2026년 3분기 BLA 제출을 계획하지만, 제출 전 확증시험 설계를 FDA와 맞춰야 합니다. 아직 BLA를 제출하거나 FDA가 접수·승인한 상태는 아닙니다. 발표일 종가는 26.99달러에서 48.16달러로 약 78.4% 상승했습니다.',
    watchMetrics: [
      { label: '2026년 3분기 BLA', note: '회사가 제시한 제출 계획이며 실제 제출 여부를 확인해야 합니다.' },
      { label: 'FDA 접수·심사', note: '제출 이후 FDA가 신청을 접수하고 가속승인 심사를 진행하는지는 별도 단계입니다.' },
      { label: '확증시험 설계', note: 'BLA 제출 전 표준치료 동시대조군 등 시험 설계를 FDA와 맞춰야 합니다.' },
    ],
    goodSignals: [
      '계획한 2026년 3분기에 BLA가 실제 제출',
      'FDA가 BLA를 접수하고 가속승인 심사를 진행',
      '효과·안전성 자료와 확증시험 설계가 요구 수준을 충족',
    ],
    cautionSignals: [
      'BLA 제출 또는 FDA 접수 지연',
      '추가 임상이나 데이터 보완 요구',
      'FDA가 기존 1/2상 데이터만으로 충분하지 않다고 판단',
    ],
    sourceLinks: [
      {
        label: 'uniQure AMT-130 BLA 계획 발표',
        url: 'https://uniqure.gcs-web.com/news-releases/news-release-details/uniqure-announces-plan-bla-submission-amt-130-huntingtons',
        note: 'FDA Type B 미팅 결과, 3년차 1/2상 데이터, 2026년 3분기 BLA 계획과 확증시험 조건을 확인합니다.',
        type: 'official-announcement',
        publisher: 'uniQure',
      },
      {
        label: 'uniQure AMT-130 FDA 8-K',
        url: 'https://www.sec.gov/Archives/edgar/data/1590560/000110465926074853/tm2618105d1_8k.htm',
        note: 'BLA 제출 계획과 FDA가 전달한 규제 경로의 SEC 공시 원문입니다.',
        type: 'company-filing',
        publisher: 'SEC · uniQure',
      },
      {
        label: 'FDA 가속승인 프로그램 안내',
        url: 'https://www.fda.gov/drugs/nda-and-bla-approvals/accelerated-approval-program',
        note: '가속승인은 BLA 제출 계획이나 지정만으로 확정되지 않는다는 절차 문맥을 확인합니다.',
        type: 'official-announcement',
        publisher: 'FDA',
      },
      {
        label: 'uniQure 공개 과거 시세',
        url: 'https://www.nasdaq.com/market-activity/stocks/qure/historical',
        note: '발표 전일과 발표일 종가를 비교하는 공개 시세 자료입니다.',
        type: 'news',
        publisher: 'Nasdaq · QURE',
      },
    ],
    publishedAt: '2026-06-17',
    status: 'published',
  },
  {
    id: 'pick-marvell-nvlink-fusion-ai-interconnect',
    pickId: 'pick-marvell-nvlink-fusion-ai-interconnect',
    companyId: 'ai-datacenter-marvell',
    title: 'Marvell도 AI 인프라 수혜주로 봐야 할까?',
    companyName: 'Marvell Technology',
    ticker: 'MRVL',
    market: 'US',
    movementDirection: 'up',
    movementLabel: 'AI 연결 반도체 기대',
    reasonSummary: 'AI 수혜주를 NVIDIA만 보고 있었다면, 이번 주는 Marvell도 함께 봐야 합니다. AI 서버가 늘수록 서버와 서버를 잇는 네트워크·인터커넥트 반도체가 중요해집니다.',
    beginnerSummary: 'NVIDIA가 AI의 두뇌라면, Marvell은 그 두뇌들이 서로 말하게 해주는 통신망 쪽에 가까운 회사입니다.',
    sector: 'AI 인프라 연결 반도체',
    flowId: 'us-semiconductors',
    flowLabel: 'AI 반도체 & 데이터센터',
    flowStage: '네트워크 / 인터커넥트 반도체',
    valueChainPosition: 'supplier',
    connectedLeaders: ['NVIDIA', 'Broadcom', 'Arista Networks'],
    relatedCompanies: ['NVIDIA', 'Broadcom', 'Arista Networks'],
    relatedCompanyIds: ['us-semiconductors-nvidia', 'ai-datacenter-broadcom', 'ai-datacenter-arista'],
    relatedSupplyChainId: 'us-semiconductors',
    relatedCompanyId: 'ai-datacenter-marvell',
    relatedTradeTags: ['NVLink Fusion', 'AI 데이터센터', '인터커넥트'],
    oneLineConclusion: 'NVIDIA가 AI의 두뇌라면, Marvell은 그 두뇌들이 서로 말하게 해주는 통신망입니다.',
    beginnerExplanation: 'AI 데이터센터가 커질수록 GPU 자체만큼 서버끼리 빠르게 데이터를 주고받는 네트워크와 인터커넥트가 중요해집니다. Marvell은 맞춤형 실리콘, 광통신, 고속 연결 반도체 흐름에서 함께 확인할 참고 기업입니다.',
    watchMetrics: [
      { label: 'AI 커스텀 반도체 매출', note: 'NVIDIA 생태계 기대가 실제 고객 주문과 매출로 이어지는지 봅니다.' },
      { label: '광통신 / 인터커넥트 수요', note: 'AI 서버 증가가 데이터 이동 병목을 키우며 관련 수요로 연결되는지 확인합니다.' },
      { label: '실적 연결 여부', note: '파트너십 기대가 다음 실적 설명과 가이던스에 어떻게 반영되는지 봅니다.' },
    ],
    goodSignals: [
      '맞춤형 반도체와 데이터센터 매출 설명이 강화됨',
      '광통신·인터커넥트 수요가 실제 주문으로 연결',
      'NVIDIA 생태계 기대가 실적 가이던스에 반영',
    ],
    cautionSignals: [
      '파트너십 기대가 매출로 확인되기까지 시간이 걸림',
      '고객 집중도와 경쟁 ASIC 업체 부담',
      'AI 인프라 투자 속도 둔화',
    ],
    sourceLinks: [
      {
        label: 'Marvell·NVIDIA NVLink Fusion 발표',
        url: 'https://www.marvell.com/company/newsroom/nvidia-ai-ecosystem-expands-marvell-joins-forces-through-nvlink-fusion.html',
        note: '전략적 파트너십, NVLink Fusion, 광인터커넥트 협력은 회사 발표 기준으로 확인합니다.',
      },
      {
        label: 'NVIDIA NVLink Fusion 발표',
        url: 'https://investor.nvidia.com/news/press-release-details/2025/NVIDIA-Unveils-NVLink-Fusion-for-Industry-to-Build-Semi-Custom-AI-Infrastructure-With-NVIDIA-Partner-Ecosystem/default.aspx',
        note: 'NVLink Fusion 파트너 생태계 문맥을 확인하는 보조 원문입니다.',
      },
    ],
    publishedAt: '2026-06-08',
    status: 'archived',
  },
  {
    id: 'pick-lg-electronics-ai-datacenter-cooling',
    pickId: 'pick-lg-electronics-ai-datacenter-cooling',
    title: 'LG전자는 왜 AI 냉각 흐름에 묶였을까?',
    companyName: 'LG전자',
    ticker: '066570.KS',
    market: 'KR',
    movementDirection: 'down',
    movementLabel: 'AI 냉각 기대 / 변동성',
    reasonSummary: 'AI 서버가 늘어나면 반도체만 필요한 것이 아니라 전력, 냉각, 공조 인프라도 중요해집니다. 단기 급등 뒤에는 차익실현 흐름으로 해석될 수 있습니다.',
    beginnerSummary: 'NVIDIA가 AI의 두뇌를 만든다면, LG전자는 그 두뇌가 과열되지 않도록 식혀주는 쪽에 기대감이 붙은 회사입니다.',
    sector: 'AI 데이터센터 냉각/HVAC',
    flowLabel: 'AI 데이터센터 냉각/HVAC',
    flowStage: '냉각 / 공조 인프라',
    valueChainPosition: 'supplier',
    connectedLeaders: ['Vertiv', 'Schneider Electric', 'Eaton'],
    relatedCompanies: ['데이터센터 운영사', '전력 인프라 기업', '냉각 장비 기업'],
    relatedTradeTags: ['AI 데이터센터', 'HVAC', '냉각 인프라'],
    oneLineConclusion: 'AI 서버가 늘면 GPU만이 아니라 열을 빼내는 냉각·공조 인프라도 같이 봐야 합니다.',
    beginnerExplanation: '고성능 AI 서버는 많은 전력을 쓰고 열도 많이 냅니다. 그래서 데이터센터 냉각, 칠러, 공조, 전력 효율은 AI 인프라 투자에서 함께 확인할 영역입니다. 다만 단기 주가 움직임은 테마 기대와 차익실현이 섞일 수 있어 이유를 단정하지 않습니다.',
    watchMetrics: [
      { label: 'AI 인프라 수주', note: '기대가 실제 데이터센터 냉각·HVAC 수주로 이어지는지 봅니다.' },
      { label: 'HVAC / 냉각 실적', note: '관련 사업이 매출과 이익에 의미 있게 찍히는지 확인합니다.' },
      { label: '밸류 부담', note: '단기 테마성 급등 이후 기대와 실적 사이의 간격이 줄어드는지 봅니다.' },
    ],
    goodSignals: [
      'AI 데이터센터 냉각 수주가 추가로 확인',
      'HVAC 사업 매출과 마진 기여가 커짐',
      '전력·냉각 효율 경쟁력이 고객 채택으로 연결',
    ],
    cautionSignals: [
      '단기 급등 뒤 차익실현 흐름이 이어짐',
      '수주 기대가 실제 실적으로 찍히는 시점이 늦어짐',
      '테마 기대가 밸류에이션 부담으로 바뀜',
    ],
    sourceLinks: [
      {
        label: 'LG전자 완주 AI 데이터센터 HVAC 협약',
        url: 'https://www.lge.co.kr/story/newsroom/235685',
        note: 'AI 데이터센터 토털 HVAC 솔루션 공급 추진과 수주 확대 문맥은 LG전자 뉴스룸 기준으로 확인합니다.',
        type: 'official-announcement',
        publisher: 'LG전자',
      },
      {
        label: 'LG AI 데이터센터 냉각 솔루션',
        url: 'https://www.lg.com/global/newsroom/news/eco-solution/lg-electronics-showcases-ai-data-center-cooling-solutions-at-data-center-world-2026/',
        note: 'Data Center World 2026에서 공개한 냉각 포트폴리오 문맥을 확인합니다.',
        type: 'official-announcement',
        publisher: 'LG전자',
      },
    ],
    publishedAt: '2026-06-08',
    status: 'archived',
  },
  {
    id: 'pick-taylor-morrison-berkshire-acquisition',
    pickId: 'pick-taylor-morrison-berkshire-acquisition',
    title: 'Taylor Morrison은 왜 인수 프리미엄이 붙었을까?',
    companyName: 'Taylor Morrison',
    ticker: 'TMHC',
    market: 'US',
    movementDirection: 'up',
    movementLabel: 'Berkshire 현금 인수 발표',
    reasonSummary: 'AI 종목만 움직인 것이 아니라 Taylor Morrison은 Berkshire Hathaway의 현금 인수 발표로 움직인 사례입니다.',
    beginnerSummary: '집을 산 게 아니라 집을 짓는 회사를 통째로 산 것입니다. 그래서 주택경기와 인수 승인 여부를 같이 봅니다.',
    sector: '주택건설 / 인수 프리미엄',
    flowLabel: 'Berkshire 인수 프리미엄',
    flowStage: '주택건설 / M&A',
    valueChainPosition: 'leader',
    connectedLeaders: ['Berkshire Hathaway', 'Clayton Homes', '미국 주택경기'],
    relatedCompanies: ['Berkshire Hathaway', 'Clayton Homes', '미국 주택건설사'],
    relatedTradeTags: ['M&A', '주택경기', 'Berkshire Hathaway'],
    oneLineConclusion: '집을 산 게 아니라 집을 짓는 회사를 통째로 산 인수 프리미엄 사례입니다.',
    beginnerExplanation: 'Berkshire Hathaway가 Taylor Morrison을 현금으로 인수하겠다고 발표하면서, 시장은 인수 가격과 승인 가능성을 먼저 반영했습니다. 이 흐름은 AI 테마와 별개로 M&A 프리미엄, 금리 부담, 주택경기를 함께 보는 사례입니다.',
    watchMetrics: [
      { label: '인수 승인 여부', note: '주주 승인과 규제 승인 등 최종 종결 조건을 확인합니다.' },
      { label: '주택경기와 금리', note: '주택 수요가 금리 부담을 이겨내는지 봅니다.' },
      { label: 'Berkshire 주택 사업 시너지', note: '기존 주택·건축자재 사업과 함께 운영될 여지가 있는지 확인합니다.' },
    ],
    goodSignals: [
      '인수 절차가 예정대로 진행',
      '주택 수요와 주문 흐름이 금리 부담을 흡수',
      'Berkshire의 기존 주택 관련 사업과 운영 시너지 확인',
    ],
    cautionSignals: [
      '승인 절차 지연 또는 조건 변경',
      '금리 부담으로 신규 주택 수요 둔화',
      '인수 프리미엄 이후 추가 상승 여력 제한',
    ],
    sourceLinks: [
      {
        label: 'Taylor Morrison·Berkshire 인수 발표',
        url: 'https://s27.q4cdn.com/448041563/files/doc_news/Berkshire-Hathaway-to-Acquire-Taylor-Morrison-Home-Corporation-for-8-5-Billion-2026.pdf',
        note: '주당 72.50달러 현금 인수 조건, 승인 절차, 종결 예상 시점은 공동 발표 원문 기준으로만 확인합니다.',
      },
    ],
    publishedAt: '2026-06-08',
    status: 'archived',
  },
  {
    id: 'pick-smci-ai-server-funding-dilution',
    pickId: 'pick-smci-ai-server-funding-dilution',
    companyId: 'ai-datacenter-supermicro',
    title: 'AI 서버 주문은 많은데, 왜 SMCI는 흔들렸을까?',
    companyName: 'Super Micro Computer',
    ticker: 'SMCI',
    market: 'US',
    movementDirection: 'down',
    movementLabel: 'AI 서버 자금조달 부담',
    reasonSummary: 'AI 서버 주문은 많았지만, 그 주문을 감당하기 위한 대규모 자금조달 계획이 희석 부담으로 해석됐습니다.',
    beginnerSummary: '주문이 많아도 먼저 부품을 사고 생산해야 합니다. 시장은 성장 자금과 기존 주주 부담을 함께 봤습니다.',
    sector: 'AI 서버 / 데이터센터',
    flowId: 'us-semiconductors',
    flowLabel: 'AI 반도체 & 데이터센터',
    flowStage: 'AI 서버 조립 / 랙 서버',
    valueChainPosition: 'supplier',
    connectedLeaders: ['NVIDIA', 'Micron', 'SK하이닉스', 'Vertiv'],
    relatedCompanies: ['NVIDIA', 'Micron', 'SK하이닉스', 'Vertiv'],
    relatedCompanyIds: ['us-semiconductors-nvidia', 'ai-datacenter-micron', 'ai-datacenter-sk-hynix', 'ai-datacenter-vertiv'],
    relatedSupplyChainId: 'us-semiconductors',
    relatedCompanyId: 'ai-datacenter-supermicro',
    relatedTradeTags: ['AI 서버', '자금조달', '희석 부담'],
    oneLineConclusion: 'AI 서버 수요는 강했지만, 그 수요를 감당할 돈을 마련하는 방식이 주가를 눌렀습니다.',
    beginnerExplanation: 'AI 서버를 만들려면 GPU, 메모리, 전력, 냉각, 부품 재고가 먼저 필요합니다. 주문이 바로 매출이 되는 것이 아니라 부품 구매, 생산, 납품 과정을 거치므로 자금조달 방식과 현금흐름을 같이 확인해야 합니다.',
    watchMetrics: [
      { label: '주문 -> 매출 전환', note: '최근 주문이 실제 매출로 찍히는지 봅니다.' },
      { label: '마진', note: '서버를 많이 팔아도 부품 원가를 빼고 이익이 남는지 확인합니다.' },
      { label: '영업현금흐름', note: '재고와 부품 구매 부담 이후 현금흐름이 회복되는지 봅니다.' },
      { label: '희석 부담', note: '자금조달 이후 기존 주주의 지분 희석 가능성을 확인합니다.' },
    ],
    goodSignals: [
      'AI 서버 주문이 실제 매출로 전환',
      '매출 증가와 함께 마진 유지',
      '재고 부담 완화와 영업현금흐름 회복',
    ],
    cautionSignals: [
      '자금조달 이후 희석 부담 확대',
      '부품 선구매로 현금흐름 악화',
      '매출은 늘지만 마진이 낮아짐',
    ],
    sourceLinks: [
      {
        label: 'Supermicro 자금조달 발표',
        url: 'https://ir.supermicro.com/news/news-details/2026/Supermicro-Announces-Proposed-7-0-Billion-of-Equity-and-Equity-linked-Financing-Transactions-To-Fund-AI-Orders/default.aspx',
        note: 'AI 서버 주문을 충족하기 위한 70억 달러 규모 자금조달 계획은 회사 발표 기준으로 확인합니다.',
        type: 'company-ir',
        publisher: 'Super Micro Computer',
      },
      {
        label: 'Supermicro 자금조달 가격 확정',
        url: 'https://ir.supermicro.com/news/news-details/2026/Supermicro-Announces-Pricing-of-Equity-and-Equity-Linked-Financing-Transactions-To-Fund-AI-Orders/default.aspx',
        note: '보통주, 의무전환우선주, ATM 프로그램 조건은 회사 발표 기준으로 확인합니다.',
        type: 'company-ir',
        publisher: 'Super Micro Computer',
      },
    ],
    publishedAt: '2026-06-12',
    status: 'published',
  },
  {
    id: 'pick-hyundai-engineering-reconstruction-expectation',
    pickId: 'pick-hyundai-engineering-reconstruction-expectation',
    title: '종전 기대감이 커지면 시장은 왜 건설주를 볼까?',
    companyName: '현대건설',
    ticker: '000720.KS',
    market: 'KR',
    movementDirection: 'up',
    movementLabel: '중동 재건 기대',
    reasonSummary: '미국·이란 종전 기대감이 커지며 시장은 전쟁 이후 복구와 인프라 발주 가능성을 먼저 봤습니다.',
    beginnerSummary: '전쟁이 멈출 수 있다는 기대가 도로, 플랜트, 주택, 항만처럼 다시 지어야 하는 영역으로 관심을 옮겼습니다.',
    sector: '재건 / 인프라 / 해외수주',
    flowLabel: '재건 / 인프라',
    flowStage: '해외수주 / 인프라 복구',
    valueChainPosition: 'leader',
    connectedLeaders: ['삼성물산', 'GS건설', '대우건설'],
    relatedCompanies: ['삼성물산', 'GS건설', '대우건설'],
    relatedTradeTags: ['중동 재건', '해외수주', '인프라'],
    oneLineConclusion: '전쟁이 멈출 수 있다는 기대가 시장을 먼저 다시 짓는 회사로 움직였습니다.',
    beginnerExplanation: '도로, 플랜트, 주택, 항만 같은 인프라는 전쟁 이후 복구 과정에서 다시 발주될 수 있는 영역입니다. 다만 기대가 실제 발주와 수주, 매출과 이익으로 이어지는지는 별도로 확인해야 합니다.',
    watchMetrics: [
      { label: '재건 발주', note: '종전 기대가 실제 인프라 발주로 이어지는지 봅니다.' },
      { label: '수주', note: '현대건설이 실제 수주를 따내는지 확인합니다.' },
      { label: '매출과 이익', note: '수주가 매출과 이익으로 연결되는지 봅니다.' },
      { label: '테마 과열', note: '단기 기대와 실제 수주 사이의 간격을 확인합니다.' },
    ],
    goodSignals: [
      '재건 관련 실제 발주 확인',
      '현대건설의 해외 수주 공시 또는 계약 확인',
      '수주가 매출과 이익으로 연결',
    ],
    cautionSignals: [
      '종전 기대가 실제 발주로 이어지지 않음',
      '수주 경쟁 심화 또는 마진 부담',
      '단기 테마 과열 이후 변동성 확대',
    ],
    sourceLinks: [
      {
        label: '연합뉴스 재건주 급등 보도',
        url: 'https://www.yna.co.kr/view/AKR20260612043100008',
        note: '미국·이란 종전 기대와 현대건설을 포함한 재건 관련주 움직임은 보도 기준으로 확인합니다.',
        type: 'news',
        publisher: '연합뉴스',
      },
      {
        label: '현대건설 회사 소개',
        url: 'https://www.hdec.kr/en/main.aspx',
        note: '해외 인프라와 건설 사업 회사 맥락을 확인하는 보조 원문입니다.',
        type: 'official-announcement',
        publisher: '현대건설',
      },
    ],
    publishedAt: '2026-06-12',
    status: 'published',
  },
  {
    id: 'pick-draftkings-sports-prediction-platform',
    pickId: 'pick-draftkings-sports-prediction-platform',
    title: 'DraftKings는 스포츠 관심을 어떻게 돈이 도는 플랫폼으로 바꿀까?',
    companyName: 'DraftKings',
    ticker: 'DKNG',
    market: 'US',
    movementDirection: 'up',
    movementLabel: '예측 플랫폼 성장',
    reasonSummary: 'DraftKings는 스포츠 베팅 앱을 넘어 이용자의 예측 수요를 거래와 재방문으로 바꾸는 플랫폼으로 주목받았습니다.',
    beginnerSummary: '경기 결과를 맞히고 싶어 하는 관심을 베팅, 거래, 결제, 재방문으로 연결하는 구조를 봅니다.',
    sector: '스포츠 베팅 / 예측 플랫폼',
    flowLabel: '스포츠·예측 플랫폼',
    flowStage: '이용자 예측 수요 / 거래 플랫폼',
    valueChainPosition: 'leader',
    connectedLeaders: ['FanDuel', 'Kalshi', 'Polymarket'],
    relatedCompanies: ['FanDuel', 'Kalshi', 'Polymarket'],
    relatedTradeTags: ['스포츠 베팅', '예측시장', '플랫폼'],
    oneLineConclusion: 'DraftKings는 경기장 밖에서 스포츠 관심을 돈이 도는 플랫폼으로 바꾸는 회사입니다.',
    beginnerExplanation: '스포츠 경기가 열리면 이용자는 승패와 결과를 예측합니다. DraftKings는 이 예측 수요를 베팅, 거래, 결제, 재방문으로 연결하려는 플랫폼입니다. 규제와 주별 확장, 상품 확장 여부를 함께 봅니다.',
    watchMetrics: [
      { label: '이용자 증가', note: '예측 상품과 스포츠 베팅 이용자가 계속 늘어나는지 봅니다.' },
      { label: '마진 구조', note: '거래와 베팅이 실제로 남는 구조인지 확인합니다.' },
      { label: '신규 주 / 상품 확장', note: '규제와 상품 확장이 이어지는지 봅니다.' },
    ],
    goodSignals: [
      '예측 상품 이용량 증가',
      '스포츠 베팅과 예측 상품의 교차 사용 확대',
      '규제 명확성과 상품 확장',
    ],
    cautionSignals: [
      '예측시장 규제 불확실성',
      '이용자 증가 대비 낮은 수익성',
      '경쟁 플랫폼과 마케팅 비용 부담',
    ],
    sourceLinks: [
      {
        label: 'DraftKings SEC 8-K',
        url: 'https://www.sec.gov/Archives/edgar/data/1883685/000110465926071581/tm2617134d1_8k.htm',
        note: 'Predictions offering의 월간 증가율과 거래량은 회사 8-K 기준으로 확인합니다.',
      },
      {
        label: 'Barron’s DraftKings 예측시장 보도',
        url: 'https://www.barrons.com/articles/draftkings-stock-prediction-market-trading-volume-e9754687',
        note: '주가 반응과 예측시장 경쟁 구도는 보도 기준으로만 참고합니다.',
      },
    ],
    publishedAt: '2026-06-12',
    status: 'published',
  },
  {
    id: 'pick-micron-ai-memory-hbm-demand',
    pickId: 'pick-micron-ai-memory-hbm-demand',
    companyId: 'ai-datacenter-micron',
    title: 'AI 서버가 늘면 왜 Micron도 같이 봐야 할까?',
    companyName: 'Micron',
    ticker: 'MU',
    market: 'US',
    movementDirection: 'up',
    movementLabel: 'AI 메모리 반등',
    reasonSummary: '반도체주 반등 속에서 AI 서버에 필요한 HBM, DRAM, NAND 같은 고성능 메모리 수요가 다시 주목받았습니다.',
    beginnerSummary: 'GPU가 AI의 계산을 맡는다면, Micron의 메모리는 그 계산에 필요한 데이터를 빠르게 저장하고 불러오는 공간입니다.',
    sector: 'AI 메모리 / HBM',
    flowId: 'us-semiconductors',
    flowLabel: 'AI 반도체 & 데이터센터',
    flowStage: 'HBM / DRAM 메모리',
    valueChainPosition: 'supplier',
    connectedLeaders: ['NVIDIA', 'SK하이닉스', '삼성전자', 'TSMC'],
    relatedCompanies: ['NVIDIA', 'SK하이닉스', '삼성전자', 'TSMC'],
    relatedCompanyIds: ['us-semiconductors-nvidia', 'ai-datacenter-sk-hynix', 'ai-datacenter-samsung', 'ai-datacenter-tsmc'],
    relatedSupplyChainId: 'us-semiconductors',
    relatedCompanyId: 'ai-datacenter-micron',
    relatedTradeTags: ['HBM', 'DRAM', 'AI 서버'],
    oneLineConclusion: '엔비디아가 AI의 두뇌라면 Micron은 그 두뇌가 기억하는 공간입니다.',
    beginnerExplanation: 'AI 서버가 늘어나면 GPU뿐 아니라 데이터를 빠르게 저장하고 불러올 고성능 메모리도 필요합니다. HBM, DRAM, NAND 가격과 출하량이 실제 매출과 현금흐름으로 이어지는지 확인합니다.',
    watchMetrics: [
      { label: 'HBM 매출', note: 'AI 서버용 고성능 메모리 매출이 실제로 커지는지 봅니다.' },
      { label: 'DRAM / NAND 가격', note: '메모리 가격 회복이 실적에 반영되는지 확인합니다.' },
      { label: '실적 재평가 여부', note: '단순 섹터 반등인지 실적 전망 변화인지 봅니다.' },
    ],
    goodSignals: [
      'HBM과 데이터센터 메모리 수요 확대',
      'DRAM·NAND 가격 회복',
      '매출 증가와 현금흐름 개선',
    ],
    cautionSignals: [
      '메모리 가격 사이클 둔화',
      'HBM 공급 경쟁 심화',
      '섹터 반등이 실적 확인 없이 앞서감',
    ],
    sourceLinks: [
      {
        label: 'Micron FY26 2Q 실적 발표',
        url: 'https://investors.micron.com/news-releases/news-release-details/micron-technology-inc-reports-results-second-quarter-fiscal-2026',
        note: 'AI 시대 메모리 수요, 매출, 현금흐름 설명은 회사 발표 기준으로 확인합니다.',
        type: 'company-ir',
        publisher: 'Micron',
      },
      {
        label: 'MarketWatch 메모리주 반등 보도',
        url: 'https://www.marketwatch.com/story/microns-stock-bounces-back-in-a-big-way-the-memory-trade-is-alive-and-well-3466929f',
        note: '메모리 업종 반등과 HBM/DRAM 수요 해석은 보도 기준으로 참고합니다.',
        type: 'news',
        publisher: 'MarketWatch',
        accessType: 'restricted',
      },
    ],
    publishedAt: '2026-06-12',
    status: 'published',
  },
  {
    id: 'pick-dell-ai-server-earnings-check',
    pickId: 'pick-dell-ai-server-earnings-check',
    companyId: 'ai-datacenter-dell',
    title: 'Dell은 왜 또 급등했을까?',
    companyName: 'Dell Technologies',
    ticker: 'DELL',
    market: 'US',
    movementDirection: 'up',
    movementLabel: '실적 / 급등',
    reasonSummary: '지난번엔 기대감, 이번엔 숫자 확인. AI 서버 기대감이 주문·매출·가이던스 숫자로 확인됐습니다.',
    beginnerSummary: 'AI 뉴스는 먼저 기대감을 만들고, 이후 주문·매출·가이던스가 그 기대를 확인하는지 봅니다.',
    sector: 'AI 서버',
    flowId: 'us-semiconductors',
    flowLabel: 'AI 반도체 & 데이터센터',
    flowStage: 'AI 서버 / 데이터센터 인프라',
    valueChainPosition: 'supplier',
    connectedLeaders: ['NVIDIA', 'Super Micro', 'Vertiv'],
    relatedCompanies: ['NVIDIA', 'Super Micro', 'Vertiv'],
    relatedCompanyIds: ['us-semiconductors-nvidia', 'ai-datacenter-supermicro', 'ai-datacenter-vertiv'],
    relatedSupplyChainId: 'us-semiconductors',
    relatedCompanyId: 'ai-datacenter-dell',
    relatedTradeTags: ['AI 서버', '실적', 'SEC'],
    oneLineConclusion: 'AI 뉴스는 기대감을 만들고, 주문·매출·가이던스가 주가를 검증합니다.',
    beginnerExplanation: 'Dell은 AI 서버와 인프라를 기업에 공급하는 단계에 있습니다. 이번 후속편에서는 AI 서버 수요가 실제 주문, 매출, 다음 전망으로 이어지는지를 확인합니다.',
    watchMetrics: [
      { label: '매출', note: 'AI 서버 수요가 전체 판매 흐름에 반영되는지 봅니다.' },
      { label: 'AI 서버 주문 / 백로그', note: '들어온 주문이 쌓이고, 이후 매출로 이어지는지 확인합니다.' },
      { label: '가이던스', note: '회사가 다음 기간 수요를 어떻게 설명하는지 봅니다. 자동 API 숫자와 섞지 않습니다.' },
    ],
    goodSignals: [
      'AI 서버 마진이 남는지',
      '백로그가 매출로 이어지는지',
      '다음 가이던스가 더 올라가는지',
    ],
    cautionSignals: [
      '서버 매출은 늘지만 이익률이 낮아짐',
      '백로그가 실제 매출로 늦게 전환됨',
      '가이던스가 기대보다 보수적으로 바뀜',
    ],
    sourceLinks: [
      {
        label: 'Dell 실적 발표 원문 확인',
        note: '주문, 백로그, 가이던스 수치는 회사 발표 원문에서 별도로 확인합니다.',
      },
    ],
    publishedAt: '2026-05-30',
    status: 'published',
  },
  {
    id: 'pick-snowflake-ai-data-platform',
    pickId: 'pick-snowflake-ai-data-platform',
    title: 'Snowflake는 왜 폭등했을까?',
    companyName: 'Snowflake',
    ticker: 'SNOW',
    market: 'US',
    movementDirection: 'up',
    movementLabel: '실적 / 급등',
    reasonSummary: 'AI 기능이 기업 데이터 정리와 실제 사용량 증가로 이어지는지 보려는 기대가 커졌습니다.',
    beginnerSummary: 'AI는 반도체만 필요한 게 아니라 데이터를 정리하고 연결하는 플랫폼도 필요합니다.',
    sector: 'AI 데이터 플랫폼',
    flowId: 'us-ai-cloud-datacenter',
    flowLabel: 'AI 데이터 플랫폼',
    flowStage: '데이터 플랫폼 / 클라우드',
    valueChainPosition: 'supplier',
    connectedLeaders: ['Amazon / AWS', 'Microsoft', 'Datadog'],
    relatedCompanies: ['Amazon / AWS', 'Microsoft', 'Datadog', 'MongoDB'],
    relatedCompanyIds: ['ai-datacenter-amazon', 'ai-datacenter-microsoft'],
    relatedSupplyChainId: 'us-semiconductors',
    relatedTradeTags: ['AI 데이터 플랫폼', '클라우드', 'AI 워크로드'],
    oneLineConclusion: 'AI 데이터 뉴스는 기대감을 만들고, 사용량과 마진이 주가를 검증합니다.',
    beginnerExplanation: 'Snowflake는 기업 데이터가 AI에 쓰일 수 있도록 모으고 정리하는 쪽에 있습니다. AI 기능이 실제 사용량 증가와 대기업 고객 지출로 이어지는지 확인합니다.',
    watchMetrics: [
      { label: '매출', note: '데이터 플랫폼 사용이 실제 판매 증가로 이어지는지 봅니다.' },
      { label: '제품 매출 가이던스', note: '회사가 다음 수요를 어떻게 설명하는지 보는 참고 포인트입니다. 자동 API와 연결하지 않습니다.' },
      { label: '대형 고객 / 사용량', note: 'AI 기능이 실제 사용량과 큰 고객 지출로 이어지는지 확인합니다.' },
    ],
    goodSignals: [
      'AI 기능이 실제 사용량 증가로 이어지는지',
      '대기업 고객 지출이 유지되는지',
      '클라우드 비용보다 수익성이 좋아지는지',
    ],
    cautionSignals: [
      'AI 기대가 실제 사용량으로 늦게 이어짐',
      '대형 고객 지출 둔화',
      '클라우드 비용 부담으로 수익성 개선이 늦어짐',
    ],
    sourceLinks: [
      {
        label: 'Snowflake 공식 데이터 연결 필요',
        note: '매출, 제품 매출 가이던스, 대형 고객·사용량은 다음 단계에서 공식 자료 기준으로 연결합니다.',
      },
    ],
    publishedAt: '2026-05-30',
    status: 'published',
  },
  {
    id: 'pick-dell-ai-server-demand',
    pickId: 'pick-dell-ai-server-demand',
    companyId: 'ai-datacenter-dell',
    title: 'Dell AI 서버 수요 해부',
    companyName: 'Dell Technologies',
    ticker: 'DELL',
    market: 'US',
    movementDirection: 'up',
    movementLabel: 'AI 서버 수요 기대',
    reasonSummary: 'Dell 주가는 AI 서버 수요 기대감으로 움직였습니다. 시장은 서버 주문과 매출, 마진이 같이 확인되는지 보고 있습니다.',
    beginnerSummary: 'Dell은 AI 칩을 직접 설계하는 회사는 아니지만, AI 서버를 구축하는 과정에서 수요가 연결되는 인프라 기업입니다.',
    sector: 'AI 서버·데이터센터 인프라',
    flowId: 'us-semiconductors',
    flowLabel: 'AI 반도체 & 데이터센터',
    flowStage: 'AI 서버 / 데이터센터 인프라',
    valueChainPosition: 'supplier',
    connectedLeaders: ['NVIDIA', 'Super Micro', 'Vertiv'],
    relatedCompanies: ['NVIDIA', 'Super Micro', 'Vertiv'],
    relatedCompanyIds: ['us-semiconductors-nvidia', 'ai-datacenter-supermicro', 'ai-datacenter-vertiv'],
    relatedSupplyChainId: 'us-semiconductors',
    relatedCompanyId: 'ai-datacenter-dell',
    relatedTradeTags: ['AI 서버', '데이터센터', 'SEC'],
    oneLineConclusion: 'AI 서버 수요가 Dell의 매출과 수주잔고로 이어지는지가 핵심입니다.',
    beginnerExplanation: 'Dell은 AI 칩을 직접 설계하는 회사는 아니지만, NVIDIA GPU 같은 고성능 부품을 서버 형태로 고객에게 공급하는 쪽에 가깝습니다. 클라우드, 기업, 데이터센터 고객의 AI 인프라 투자가 실제 매출과 현금흐름으로 이어지는지 확인해야 합니다.',
    watchMetrics: [
      { label: '서버/인프라 매출', note: 'AI 서버 수요가 실제 매출로 이어지는지 확인합니다.' },
      { label: '영업이익 또는 영업이익률', note: '서버를 많이 팔아도 이익이 남는지 봅니다.' },
      { label: '영업현금흐름 또는 FCF', note: '수주와 매출이 실제 현금흐름으로 이어지는지 확인합니다.' },
    ],
    goodSignals: [
      'AI 서버 주문과 수주잔고 증가',
      '서버 매출 증가가 실제 실적으로 연결',
      '영업이익률 또는 현금흐름 유지',
      '데이터센터 고객 수요 지속',
    ],
    cautionSignals: [
      'AI 서버 매출은 늘지만 마진이 낮아짐',
      'GPU·메모리 등 부품 원가 부담 증가',
      '수주잔고가 실제 매출로 전환되는 속도 둔화',
      '특정 대형 고객 의존도 확대',
    ],
    sourceLinks: [
      {
        label: 'Dell 공식 FY26 실적 발표',
        url: 'https://www.dell.com/en-us/dt/corporate/newsroom/announcements/detailpage.press-releases~usa~2026~2~dell-technologies-delivers-fourth-quarter-and-full-year-fiscal-2026-results.htm',
        note: 'AI 최적화 서버 주문, 매출, 수주잔고는 회사 발표 기준으로 확인합니다.',
      },
      {
        label: 'SEC 10-K 원문',
        url: 'https://www.sec.gov/Archives/edgar/data/1571996/000157199626000008/dell-20260130.htm',
        note: '재무제표와 MD&A는 SEC 원문 기준으로 확인합니다.',
      },
    ],
    publishedAt: '2026-05-25',
    status: 'archived',
  },
  {
    id: 'pick-nvidia-ai-demand',
    pickId: 'pick-nvidia-ai-demand',
    companyId: 'us-semiconductors-nvidia',
    title: 'NVIDIA AI 서버 수요 해부',
    companyName: 'NVIDIA',
    ticker: 'NVDA',
    market: 'US',
    movementDirection: 'up',
    movementLabel: '실적 기대감',
    reasonSummary: 'AI 데이터센터 수요 기대가 다음 분기 실적 눈높이를 높였습니다.',
    beginnerSummary: 'AI 서버가 늘수록 GPU, 메모리, 장비 기업을 함께 봐야 합니다.',
    sector: 'AI 반도체',
    flowId: 'us-semiconductors',
    flowLabel: 'AI 반도체 & 데이터센터',
    flowStage: 'AI 칩 / GPU',
    valueChainPosition: 'leader',
    connectedLeaders: ['TSMC', 'SK하이닉스', 'ASML', 'AMD'],
    relatedCompanies: ['TSMC', 'SK하이닉스', 'ASML', 'AMD'],
    relatedCompanyIds: ['ai-datacenter-tsmc', 'ai-datacenter-sk-hynix', 'ai-datacenter-asml', 'ai-datacenter-amd', 'ai-datacenter-vertiv'],
    relatedSupplyChainId: 'us-semiconductors',
    relatedCompanyId: 'us-semiconductors-nvidia',
    relatedTradeTags: ['13F', 'AI 데이터센터', 'GPU'],
    oneLineConclusion: 'NVIDIA는 AI 서버 수요의 중심에 있는 AI 칩 기업으로, GPU와 CUDA 생태계가 핵심 경쟁력입니다.',
    beginnerExplanation: 'AI 서버 투자가 늘면 NVIDIA의 GPU 수요가 커질 수 있습니다. GPU 수요가 커지면 HBM, 파운드리, 서버, 전력·냉각 기업도 함께 관심을 받을 수 있습니다.',
    watchMetrics: [
      { label: '데이터센터 매출 성장률', note: 'AI 서버 수요가 실제 매출로 이어지는지 봅니다.' },
      { label: '영업이익률', note: '고성능 칩 경쟁력이 이익으로 남는지 확인합니다.' },
      { label: '잉여현금흐름 / R&D 투자', note: '생태계와 기술 우위를 유지할 현금과 투자를 같이 봅니다.' },
    ],
    goodSignals: ['데이터센터 매출 성장 지속', '높은 영업이익률 유지', '현금흐름과 생태계 투자 확대'],
    cautionSignals: ['고객 투자 둔화', 'ASIC·AMD와 경쟁 심화', '규제나 제품 전환에 따른 재고 부담'],
    sourceLinks: [{ label: 'SEC 원문 보고서', url: 'https://www.sec.gov/Archives/edgar/data/1045810/000104581026000021/nvda-20260125.htm', note: '실적과 MD&A는 원문 기준으로 확인합니다.' }],
    publishedAt: '2026-05-17',
    status: 'published',
  },
  {
    id: 'pick-samsung-hbm-foundry',
    pickId: 'pick-samsung-hbm-foundry',
    companyId: 'ai-datacenter-samsung',
    title: '삼성전자 HBM·파운드리 흐름 해부',
    companyName: '삼성전자',
    ticker: '005930.KS',
    market: 'KR',
    movementDirection: 'up',
    movementLabel: 'HBM·파운드리 확인',
    reasonSummary: 'AI 반도체 수요가 메모리와 파운드리 경쟁력 확인으로 이어졌습니다.',
    beginnerSummary: '삼성전자는 메모리와 파운드리를 함께 봐야 하는 대표 한국 상장기업입니다.',
    sector: 'AI 반도체',
    flowId: 'us-semiconductors',
    flowLabel: 'AI 반도체 & 데이터센터',
    flowStage: 'HBM / 메모리 · 파운드리',
    valueChainPosition: 'supplier',
    connectedLeaders: ['NVIDIA', 'SK하이닉스', 'TSMC', 'ASML'],
    relatedCompanies: ['SK하이닉스', '한미반도체', '원익IPS', '솔브레인'],
    relatedCompanyIds: ['us-semiconductors-nvidia', 'ai-datacenter-sk-hynix', 'ai-datacenter-tsmc', 'ai-datacenter-asml', 'ai-datacenter-hanmi'],
    relatedSupplyChainId: 'us-semiconductors',
    relatedCompanyId: 'ai-datacenter-samsung',
    relatedTradeTags: ['HBM', '파운드리', 'DART'],
    oneLineConclusion: '삼성전자는 메모리와 파운드리를 모두 가진 반도체 기업으로, HBM 경쟁력과 업황 회복이 핵심 확인 포인트입니다.',
    beginnerExplanation: 'AI 서버 수요가 늘면 HBM 같은 고성능 메모리와 첨단 칩 생산 능력을 함께 확인해야 합니다. 직접 고객과 매출 비중은 공시와 IR에서 확인해야 합니다.',
    watchMetrics: [
      { label: '영업이익률', note: '메모리 업황 회복이 이익으로 이어지는지 봅니다.' },
      { label: '재고자산', note: '제품이 쌓이는지, 수요 회복과 맞는지 확인합니다.' },
      { label: '영업현금흐름', note: '장부상 이익이 실제 현금으로 들어오는지 봅니다.' },
    ],
    goodSignals: ['HBM 경쟁력 개선', '영업이익률 회복', '현금흐름 개선'],
    cautionSignals: ['재고 증가', '파운드리 투자 부담', '고객 인증 지연'],
    publishedAt: '2026-05-17',
    status: 'published',
  },
  {
    id: 'pick-hanmi-packaging-equipment',
    pickId: 'pick-hanmi-packaging-equipment',
    companyId: 'ai-datacenter-hanmi',
    title: '한미반도체 HBM 후공정 장비 해부',
    companyName: '한미반도체',
    ticker: '042700.KS',
    market: 'KR',
    movementDirection: 'up',
    movementLabel: '후공정 장비 기대',
    reasonSummary: 'HBM 후공정 투자 기대가 장비 기업 관심으로 이어졌습니다.',
    beginnerSummary: '장비주는 수주가 매출로 잡히는 시점과 재고 변화를 같이 봐야 합니다.',
    sector: '반도체 장비',
    flowId: 'us-semiconductors',
    flowLabel: 'AI 반도체 & 데이터센터',
    flowStage: '장비 / 소재 / 후공정',
    valueChainPosition: 'equipment',
    connectedLeaders: ['삼성전자', 'SK하이닉스', 'NVIDIA', 'TSMC'],
    relatedCompanies: ['삼성전자', 'SK하이닉스', '원익IPS', '주성엔지니어링'],
    relatedCompanyIds: ['ai-datacenter-sk-hynix', 'ai-datacenter-samsung', 'us-semiconductors-nvidia', 'ai-datacenter-asml', 'ai-datacenter-wonikips'],
    relatedSupplyChainId: 'us-semiconductors',
    relatedCompanyId: 'ai-datacenter-hanmi',
    relatedTradeTags: ['DART', 'HBM', '후공정'],
    oneLineConclusion: '한미반도체는 HBM 후공정 장비 기대와 연결되는 한국 장비 기업입니다.',
    beginnerExplanation: 'HBM 생산이 늘면 후공정 장비 수요도 커질 수 있습니다. 다만 직접 고객별 매출 비중은 공시와 IR에서 확인해야 합니다.',
    watchMetrics: [
      { label: '수주 / 매출 성장률', note: '장비 주문이 실제 매출로 잡히는지 봅니다.' },
      { label: '영업이익률', note: '고부가 장비 경쟁력이 이익률로 남는지 확인합니다.' },
      { label: '영업현금흐름', note: '수주와 매출이 실제 현금 회수로 이어지는지 봅니다.' },
    ],
    goodSignals: ['수주잔고 증가', '고객 인증 확대', '설비투자가 매출로 전환'],
    cautionSignals: ['고객 투자 지연', '특정 고객 의존도 확대', '수주가 매출로 늦게 반영'],
    sourceLinks: [{ label: 'DART 원문 보고서', url: 'https://dart.fss.or.kr/dsaf001/main.do?rcpNo=20260515001572', note: '분기보고서 원문 기준으로 확인합니다.' }],
    publishedAt: '2026-05-17',
    status: 'published',
  },
  {
    id: 'pick-sk-hynix-hbm',
    pickId: 'pick-sk-hynix-hbm',
    companyId: 'ai-datacenter-sk-hynix',
    title: 'SK하이닉스 HBM 수요 해부',
    companyName: 'SK하이닉스',
    ticker: '000660.KS',
    market: 'KR',
    movementDirection: 'up',
    movementLabel: 'AI 메모리 수요',
    reasonSummary: 'AI 서버용 메모리 수요 기대가 실적 전망에 반영됐습니다.',
    beginnerSummary: '메모리는 가격과 출하량이 같이 좋아지는지 확인해야 합니다.',
    sector: 'AI 메모리',
    flowId: 'us-semiconductors',
    flowLabel: 'AI 반도체 & 데이터센터',
    flowStage: 'HBM / 메모리',
    valueChainPosition: 'supplier',
    connectedLeaders: ['NVIDIA', 'AMD', '삼성전자', 'TSMC'],
    relatedCompanies: ['한미반도체', '원익IPS', '솔브레인', '리노공업'],
    relatedCompanyIds: ['us-semiconductors-nvidia', 'ai-datacenter-hanmi', 'ai-datacenter-samsung', 'ai-datacenter-tsmc', 'ai-datacenter-micron'],
    relatedSupplyChainId: 'us-semiconductors',
    relatedCompanyId: 'ai-datacenter-sk-hynix',
    relatedTradeTags: ['HBM', '기관 수급', 'DART'],
    oneLineConclusion: 'SK하이닉스는 AI 서버에 필요한 HBM 수요와 연결된 메모리 기업입니다.',
    beginnerExplanation: 'AI GPU가 더 많이 쓰이면 함께 붙는 고성능 메모리 수요도 커질 수 있습니다. 메모리는 업황 사이클이 커서 재고와 현금흐름을 같이 봐야 합니다.',
    watchMetrics: [
      { label: '영업이익률', note: '메모리 가격과 제품 믹스가 이익으로 남는지 봅니다.' },
      { label: '재고자산', note: '팔릴 제품이 쌓이는지, 수요 회복과 맞는지 확인합니다.' },
      { label: '영업현금흐름', note: '장부상 이익이 실제 현금으로 들어오는지 봅니다.' },
    ],
    goodSignals: ['HBM 수요와 고객 인증 확대', '영업이익률 유지', '재고 회전과 현금흐름 개선'],
    cautionSignals: ['재고 증가', '매출채권 회수 지연', '메모리 가격 둔화'],
    sourceLinks: [{ label: 'DART 원문 보고서', url: 'https://dart.fss.or.kr/dsaf001/main.do?rcpNo=20260515002287', note: '분기보고서 원문 기준으로 확인합니다.' }],
    publishedAt: '2026-05-17',
    status: 'published',
  },
  {
    id: 'pick-ai-server-parts',
    pickId: 'pick-ai-server-parts',
    title: 'AI 서버 인프라 흐름 해부',
    companyName: 'AI 서버 부품업체',
    ticker: 'WATCH',
    market: 'US',
    movementDirection: 'up',
    movementLabel: '서버 투자 기대',
    reasonSummary: 'AI 서버 증설 기대가 전력, 냉각, 부품 기업 관심으로 번졌습니다.',
    beginnerSummary: '같은 밸류체인에서 함께 봐야 할 대표 기업을 먼저 확인합니다.',
    sector: 'AI 서버',
    flowId: 'us-semiconductors',
    flowLabel: 'AI 반도체 & 데이터센터',
    flowStage: '서버 / 네트워크 · 전력·냉각',
    valueChainPosition: 'supplier',
    connectedLeaders: ['NVIDIA', 'Dell', 'Super Micro', 'Vertiv'],
    relatedCompanies: ['Microsoft', 'Amazon', 'Alphabet', 'Eaton'],
    relatedCompanyIds: ['ai-datacenter-supermicro', 'ai-datacenter-dell', 'ai-datacenter-vertiv', 'ai-datacenter-eaton', 'ai-datacenter-microsoft'],
    relatedSupplyChainId: 'us-semiconductors',
    relatedTradeTags: ['AI 서버', '데이터센터', '전력·냉각'],
    oneLineConclusion: 'AI 서버 투자는 서버, 네트워크, 전력·냉각 기업까지 함께 확인해야 하는 흐름입니다.',
    beginnerExplanation: 'AI 서버가 늘면 GPU뿐 아니라 서버 조립, 네트워크, 전력 공급, 냉각 인프라 수요도 커질 수 있습니다. 직접 납품 관계는 기업별 공시와 계약 자료로 확인해야 합니다.',
    watchMetrics: [
      { label: '데이터센터 수주 / 백로그', note: 'AI 인프라 투자가 실제 주문으로 이어지는지 봅니다.' },
      { label: '매출 성장률', note: '관심이 실제 판매 증가로 이어지는지 확인합니다.' },
      { label: '잉여현금흐름', note: '프로젝트 매출이 현금으로 남는지 봅니다.' },
    ],
    goodSignals: ['데이터센터 수주 증가', '마진 유지', '현금흐름 개선'],
    cautionSignals: ['고객 투자 지연', '재고 증가', '매출 증가 대비 낮은 현금흐름'],
    publishedAt: '2026-05-17',
    status: 'published',
  },
  {
    id: 'pick-battery-materials-watch',
    pickId: 'pick-battery-materials-watch',
    title: '배터리 소재 수요 부담 해부',
    companyName: '배터리 소재업체',
    ticker: 'WATCH',
    market: 'KR',
    movementDirection: 'down',
    movementLabel: '전기차 수요 부담',
    reasonSummary: '전기차 수요 둔화와 소재 가격 변동이 투자심리에 부담으로 작용했습니다.',
    beginnerSummary: '소재 기업은 판매량뿐 아니라 원재료 가격과 고객사 투자 계획도 함께 봅니다.',
    sector: '2차전지 소재',
    flowId: 'kr-battery-materials',
    flowLabel: '2차전지 / 전기차',
    flowStage: '소재',
    valueChainPosition: 'materials',
    connectedLeaders: ['Tesla', 'BYD', 'CATL', 'LG에너지솔루션'],
    relatedCompanies: ['포스코퓨처엠', '삼성SDI', 'GM', 'Rivian'],
    relatedCompanyIds: ['kr-battery-materials-posco-futurem'],
    relatedSupplyChainId: 'kr-battery-materials',
    relatedCompanyId: 'kr-battery-materials-posco-futurem',
    relatedTradeTags: ['배터리', '소재 가격', '전기차'],
    oneLineConclusion: '배터리 소재 기업은 전기차 수요와 원재료 가격 변화가 실적 기대에 함께 영향을 줍니다.',
    beginnerExplanation: '전기차 판매가 둔화되면 소재 주문과 가격 기대가 낮아질 수 있습니다. 많이 파는지뿐 아니라 원가와 고객사 투자 계획을 함께 확인해야 합니다.',
    watchMetrics: [
      { label: '매출 성장률', note: '전기차 수요가 실제 판매 증가로 이어졌는지 봅니다.' },
      { label: '영업이익률', note: '원재료 가격 변화가 이익률을 누르는지 확인합니다.' },
      { label: '재고 / 현금흐름', note: '재고 부담과 실제 현금 회수를 함께 봅니다.' },
    ],
    goodSignals: ['고객사 투자 재개', '원재료 가격 안정', '영업현금흐름 개선'],
    cautionSignals: ['전기차 수요 둔화', '소재 가격 하락', '재고 부담 증가'],
    publishedAt: '2026-05-17',
    status: 'published',
  },
];
