import type { MacroDomainBrief } from './types.js';

export const macroDomainBriefs: MacroDomainBrief[] = [
  {
    id: 'rates-structure-brief',
    domain: 'rates',
    state: '높은 절대 금리와 플러스 장단기차',
    trend: 'stable',
    summary: '2년물과 10년물의 절대 수준, 그리고 두 금리의 차이를 함께 확인해야 합니다.',
    evidenceIndicatorIds: ['us-treasury-2y', 'us-treasury-10y', 'us-10y2y-spread'],
    sourceRefs: ['fred-series-dgs2', 'fred-series-dgs10', 'fred-series-t10y2y'],
    reportIds: ['imf-weo-april-2026', 'world-bank-gep-june-2026'],
    bottleneckIds: [],
    asOf: '2026-07-08',
    reviewedAt: '2026-07-12',
  },
  {
    id: 'financial-conditions-brief',
    domain: 'financial-conditions',
    state: '평균보다 느슨한 금융여건',
    trend: 'improving',
    summary: 'NFCI는 0 아래에서 평균보다 느슨한 구간이지만, 주간 변화 방향도 따로 봐야 합니다.',
    evidenceIndicatorIds: ['us-financial-conditions'],
    sourceRefs: ['fred-series-nfci'],
    reportIds: ['imf-weo-april-2026'],
    bottleneckIds: [],
    asOf: '2026-07-03',
    reviewedAt: '2026-07-12',
  },
  {
    id: 'liquidity-brief',
    domain: 'liquidity',
    state: '대차대조표와 통화량을 분리 확인',
    trend: 'stable',
    summary: '연준 총자산의 주간 변화와 M2의 월간 변화를 같은 유동성 신호로 단순 합산하지 않습니다.',
    evidenceIndicatorIds: ['fed-total-assets', 'us-m2-money-stock'],
    sourceRefs: ['fred-series-walcl', 'fred-series-m2sl'],
    reportIds: ['world-bank-gep-june-2026'],
    bottleneckIds: [],
    asOf: '2026-07-01',
    reviewedAt: '2026-07-12',
  },
  {
    id: 'industry-demand-brief',
    domain: 'industry-infrastructure',
    state: '생산 개선과 허가 약화가 엇갈림',
    trend: 'stable',
    summary: '산업생산·제조업 가동률·건축허가를 함께 봐야 산업과 인프라 수요의 결을 구분할 수 있습니다.',
    evidenceIndicatorIds: ['us-industrial-production', 'us-manufacturing-utilization', 'us-building-permits'],
    sourceRefs: ['fred-series-indpro', 'fred-series-cumfns', 'fred-series-permit'],
    reportIds: ['iea-electricity-2026', 'world-bank-commodity-outlook-april-2026'],
    bottleneckIds: ['grid-transformers-high-voltage', 'data-center-power-cooling', 'gas-turbine-capacity', 'copper-grid-metals', 'semiconductor-fab-infrastructure'],
    asOf: '2026-05-01',
    reviewedAt: '2026-07-12',
  },
];
