import type { MacroIndicatorDefinition } from './types.js';

const board = 'Board of Governors of the Federal Reserve System (US)';

export const macroIndicatorDefinitions: MacroIndicatorDefinition[] = [
  {
    id: 'us-treasury-2y',
    seriesId: 'DGS2',
    label: '미국 2년물 국채금리',
    shortLabel: '2년물',
    officialTitle: 'Market Yield on U.S. Treasury Securities at 2-Year Constant Maturity, Quoted on an Investment Basis',
    domain: 'rates',
    frequency: 'daily',
    unitKind: 'percent',
    displayUnit: '%',
    changeMode: 'basis-points',
    historyLimit: 60,
    sourceInstitution: board,
    sourceRef: 'fred-series-dgs2',
    interpretation: '통화정책 기대와 가까운 만기의 국채 수익률로, 단기 자금조달 환경을 볼 때 확인합니다.',
    higherMeaning: '단기 금리 부담이 높아지는 방향',
    lowerMeaning: '단기 금리 부담이 낮아지는 방향',
    caution: '단일 금리 변화만으로 경기나 자산 가격의 방향을 확정하지 않습니다.',
  },
  {
    id: 'us-treasury-10y',
    seriesId: 'DGS10',
    label: '미국 10년물 국채금리',
    shortLabel: '10년물',
    officialTitle: 'Market Yield on U.S. Treasury Securities at 10-Year Constant Maturity, Quoted on an Investment Basis',
    domain: 'rates',
    frequency: 'daily',
    unitKind: 'percent',
    displayUnit: '%',
    changeMode: 'basis-points',
    historyLimit: 60,
    sourceInstitution: board,
    sourceRef: 'fred-series-dgs10',
    interpretation: '장기 성장·물가·기간 프리미엄 기대가 함께 반영되는 미국 장기금리 기준입니다.',
    higherMeaning: '장기 할인율과 자금조달 부담이 높아지는 방향',
    lowerMeaning: '장기 할인율과 자금조달 부담이 낮아지는 방향',
    caution: '오늘 시장 브리핑의 Yahoo ^TNX와 공급자·기준 시각·용도가 다른 공식 일별 관측값입니다.',
  },
  {
    id: 'us-10y2y-spread',
    seriesId: 'T10Y2Y',
    label: '미국 10년물 - 2년물 금리차',
    shortLabel: '10년-2년 금리차',
    officialTitle: '10-Year Treasury Constant Maturity Minus 2-Year Treasury Constant Maturity',
    domain: 'rates',
    frequency: 'daily',
    unitKind: 'percent',
    displayUnit: '%',
    changeMode: 'basis-points',
    historyLimit: 60,
    sourceInstitution: 'Federal Reserve Bank of St. Louis',
    sourceRef: 'fred-series-t10y2y',
    interpretation: '장기금리와 단기금리의 상대적 위치를 보여주는 수익률곡선 지표입니다.',
    higherMeaning: '장단기 금리차가 확대되는 방향',
    lowerMeaning: '장단기 금리차가 축소되는 방향',
    caution: '금리차가 양수라는 이유만으로 경기 확장을 확정하지 않습니다.',
  },
  {
    id: 'us-financial-conditions',
    seriesId: 'NFCI',
    label: 'Chicago Fed 금융여건지수',
    shortLabel: '금융여건',
    officialTitle: 'Chicago Fed National Financial Conditions Index',
    domain: 'financial-conditions',
    frequency: 'weekly',
    unitKind: 'index',
    displayUnit: 'index',
    changeMode: 'absolute',
    historyLimit: 52,
    sourceInstitution: 'Federal Reserve Bank of Chicago',
    sourceRef: 'fred-series-nfci',
    interpretation: '미국 자금·채권·주식·은행 시장 전반의 금융여건을 평균과 비교하는 주간 지표입니다.',
    higherMeaning: '금융여건이 더 타이트해지는 방향',
    lowerMeaning: '금융여건이 더 느슨해지는 방향',
    caution: '0보다 높으면 평균보다 타이트하고, 0보다 낮으면 평균보다 느슨합니다.',
  },
  {
    id: 'fed-total-assets',
    seriesId: 'WALCL',
    label: '연준 총자산',
    shortLabel: '연준 총자산',
    officialTitle: 'Assets: Total Assets: Total Assets (Less Eliminations from Consolidation): Wednesday Level',
    domain: 'liquidity',
    frequency: 'weekly',
    unitKind: 'millions-usd',
    displayUnit: '조 달러',
    changeMode: 'absolute',
    historyLimit: 52,
    sourceInstitution: board,
    sourceRef: 'fred-series-walcl',
    interpretation: '연준 대차대조표 규모를 보여주는 주간 관측값으로 정책 유동성 배경을 확인합니다.',
    higherMeaning: '연준 대차대조표가 확대되는 방향',
    lowerMeaning: '연준 대차대조표가 축소되는 방향',
    caution: '총자산 증가를 즉시 시장 유동성 증가와 동일시하지 않습니다.',
  },
  {
    id: 'us-m2-money-stock',
    seriesId: 'M2SL',
    label: '미국 M2 통화량',
    shortLabel: 'M2',
    officialTitle: 'M2',
    domain: 'liquidity',
    frequency: 'monthly',
    unitKind: 'billions-usd',
    displayUnit: '조 달러',
    changeMode: 'percentage',
    historyLimit: 24,
    sourceInstitution: board,
    sourceRef: 'fred-series-m2sl',
    interpretation: '현금·예금·소매 머니마켓펀드 등을 포괄하는 광의 통화량의 월간 흐름입니다.',
    higherMeaning: '광의 통화량이 늘어나는 방향',
    lowerMeaning: '광의 통화량이 줄어드는 방향',
    caution: '통화량 변화와 실제 신용 공급·자산시장 반응 사이에는 시차가 있을 수 있습니다.',
  },
  {
    id: 'us-industrial-production',
    seriesId: 'INDPRO',
    label: '미국 산업생산지수',
    shortLabel: '산업생산',
    officialTitle: 'Industrial Production: Total Index',
    domain: 'industry-infrastructure',
    frequency: 'monthly',
    unitKind: 'index',
    displayUnit: 'index',
    changeMode: 'percentage',
    historyLimit: 24,
    sourceInstitution: board,
    sourceRef: 'fred-series-indpro',
    interpretation: '미국 제조업·광업·전기·가스 부문의 실질 생산량을 보여주는 월간 지표입니다.',
    higherMeaning: '산업 생산이 늘어나는 방향',
    lowerMeaning: '산업 생산이 줄어드는 방향',
    caution: '전체 지수와 개별 공급망의 생산능력·수요는 다를 수 있습니다.',
  },
  {
    id: 'us-manufacturing-utilization',
    seriesId: 'CUMFNS',
    label: '미국 제조업 가동률',
    shortLabel: '제조업 가동률',
    officialTitle: 'Capacity Utilization: Manufacturing (SIC)',
    domain: 'industry-infrastructure',
    frequency: 'monthly',
    unitKind: 'percent',
    displayUnit: '%',
    changeMode: 'percentage-points',
    historyLimit: 24,
    sourceInstitution: board,
    sourceRef: 'fred-series-cumfns',
    interpretation: '미국 제조업의 지속 가능한 최대 생산능력 대비 실제 가동 수준을 보여줍니다.',
    higherMeaning: '제조 설비 활용도가 높아지는 방향',
    lowerMeaning: '제조 설비 활용도가 낮아지는 방향',
    caution: '산업별 가동률 차이와 신규 증설 계획은 별도로 확인해야 합니다.',
  },
  {
    id: 'us-building-permits',
    seriesId: 'PERMIT',
    label: '미국 민간 건축허가',
    shortLabel: '민간 건축허가',
    officialTitle: 'New Privately-Owned Housing Units Authorized in Permit-Issuing Places: Total Units',
    domain: 'industry-infrastructure',
    frequency: 'monthly',
    unitKind: 'thousands-saar',
    displayUnit: '천 호, SAAR',
    changeMode: 'percentage',
    historyLimit: 24,
    sourceInstitution: 'U.S. Census Bureau and U.S. Department of Housing and Urban Development',
    sourceRef: 'fred-series-permit',
    interpretation: '미국 민간 주택 건설의 선행 허가 흐름을 계절조정 연율로 보여줍니다.',
    higherMeaning: '향후 주택 건설 파이프라인이 늘어나는 방향',
    lowerMeaning: '향후 주택 건설 파이프라인이 줄어드는 방향',
    caution: '허가가 실제 착공·완공으로 모두 이어지는 것은 아닙니다.',
  },
];
