import type { CompanyProfileEntry } from './types.js';

const commonCaution = '공식 발표와 산업 흐름 설명은 향후 실적이나 시장 가격을 보장하지 않습니다. 관련 기업은 산업 맥락을 설명하며 직접 계약을 뜻하지 않습니다.';

export const companyProfiles: CompanyProfileEntry[] = [
  {
    id: 'profile-sk-hynix',
    companyId: 'ai-datacenter-sk-hynix',
    slug: 'sk-hynix',
    order: 1,
    englishName: 'SK hynix',
    stockCode: '000660',
    exchange: 'KRX',
    industry: '반도체',
    searchDescription: 'DRAM·NAND·HBM을 생산하는 메모리 반도체 기업입니다.',
    aliases: ['하이닉스'],
    beginnerSummary: 'AI 서버에서 GPU가 빠르게 계산할 수 있도록 HBM과 DRAM을 공급하는 메모리 기업입니다.',
    businessDescription: 'HBM, DRAM, NAND 같은 메모리 반도체를 개발하고 생산합니다. AI 인프라에서는 GPU 옆에서 대량의 데이터를 빠르게 전달하는 HBM 역할을 함께 확인합니다.',
    primaryRole: '메모리·HBM 공급',
    keyQuestions: ['HBM 출하가 실제 매출로 이어지는가', '신규 생산기반이 계획대로 가동되는가', '재고·가격·현금흐름이 함께 개선되는가'],
    caution: commonCaution,
    sourceRefs: ['sk-hynix-q1-2026-results'],
    reviewedAt: '2026-07-14',
  },
  {
    id: 'profile-lg-electronics',
    companyId: 'datacenter-power-lg-electronics',
    slug: 'lg-electronics',
    order: 2,
    englishName: 'LG Electronics',
    stockCode: '066570',
    exchange: 'KRX',
    industry: '데이터센터 냉각',
    searchDescription: '가전과 HVAC·칠러 등 냉각 솔루션을 공급합니다.',
    aliases: ['LG'],
    beginnerSummary: 'HVAC, 칠러와 액체냉각 기술로 데이터센터의 열을 관리하는 기업입니다.',
    businessDescription: '가전뿐 아니라 상업용 HVAC와 데이터센터 냉각 솔루션을 공급합니다. AI 서버 밀도가 높아질수록 전력 사용과 함께 늘어나는 열을 어떻게 식히는지 확인합니다.',
    primaryRole: '데이터센터 냉각·HVAC',
    keyQuestions: ['협약이 실제 본계약과 납품으로 이어지는가', '칠러·액체냉각 매출이 구분돼 확인되는가', '냉각 수요가 마진과 현금흐름으로 이어지는가'],
    caution: commonCaution,
    sourceRefs: ['lge-story-newsroom-235685-63746d17'],
    reviewedAt: '2026-07-14',
  },
  {
    id: 'profile-nvidia',
    companyId: 'us-semiconductors-nvidia',
    slug: 'nvidia',
    order: 3,
    englishName: 'NVIDIA Corporation',
    exchange: 'NASDAQ',
    industry: '반도체',
    searchDescription: 'AI 연산에 필요한 GPU와 데이터센터 컴퓨팅 플랫폼을 제공합니다.',
    aliases: ['엔비디아'],
    beginnerSummary: 'AI 계산에 쓰이는 GPU와 가속 컴퓨팅 플랫폼을 설계하는 기업입니다.',
    businessDescription: 'AI GPU, 가속기, 네트워킹과 소프트웨어 플랫폼을 제공합니다. 클라우드·AI 서비스 수요가 GPU와 HBM, 파운드리, 서버, 전력·냉각 수요로 이어지는 출발점 중 하나입니다.',
    primaryRole: 'AI GPU·가속 컴퓨팅',
    keyQuestions: ['데이터센터 수요가 출하와 매출로 이어지는가', '신제품 전환과 공급 일정이 계획대로 진행되는가', '고객 투자와 마진·현금흐름이 함께 유지되는가'],
    caution: commonCaution,
    sourceRefs: ['nvidia-fy2027-q1-results'],
    reviewedAt: '2026-07-14',
  },
  {
    id: 'profile-micron',
    companyId: 'ai-datacenter-micron',
    slug: 'micron',
    order: 4,
    englishName: 'Micron Technology',
    exchange: 'NASDAQ',
    industry: '반도체',
    searchDescription: 'DRAM·NAND·HBM을 생산하는 메모리 반도체 기업입니다.',
    aliases: ['마이크론'],
    beginnerSummary: 'DRAM, NAND와 HBM을 생산하며 AI 서버와 범용 메모리 사이클에 연결되는 기업입니다.',
    businessDescription: '서버·PC·모바일에 쓰이는 DRAM과 NAND, AI 가속기에 쓰이는 HBM을 생산합니다. AI 수요와 범용 메모리 가격·재고 변화를 나눠 확인해야 합니다.',
    primaryRole: '메모리·HBM 생산',
    keyQuestions: ['HBM과 범용 메모리 매출을 구분해 볼 수 있는가', '생산능력 확대가 인증과 출하로 이어지는가', '재고·가격·CAPEX와 현금흐름이 균형을 이루는가'],
    caution: commonCaution,
    sourceRefs: ['micron-fy2026-q3-results'],
    reviewedAt: '2026-07-14',
  },
  {
    id: 'profile-dell',
    companyId: 'ai-datacenter-dell',
    slug: 'dell',
    order: 5,
    englishName: 'Dell Technologies',
    exchange: 'NYSE',
    industry: '서버·IT 인프라',
    searchDescription: '기업용 서버·스토리지와 IT 인프라를 공급합니다.',
    aliases: ['델'],
    beginnerSummary: 'GPU와 메모리, 네트워크를 조합해 기업용 AI 서버와 IT 인프라를 공급하는 기업입니다.',
    businessDescription: '서버, 스토리지와 기업용 IT 인프라를 공급합니다. AI 인프라에서는 주문과 수주잔고가 실제 서버 출하·매출·마진으로 바뀌는 속도를 확인합니다.',
    primaryRole: 'AI 서버·IT 인프라',
    keyQuestions: ['AI 서버 주문이 취소 없이 매출로 전환되는가', 'GPU·메모리 조달과 재고가 안정적인가', '높은 매출이 마진과 현금흐름으로 이어지는가'],
    caution: commonCaution,
    sourceRefs: ['dell-fy2027-q1-results'],
    reviewedAt: '2026-07-14',
  },
  {
    id: 'profile-eaton',
    companyId: 'ai-datacenter-eaton',
    slug: 'eaton',
    order: 6,
    englishName: 'Eaton Corporation',
    exchange: 'NYSE',
    industry: '전력 장비',
    searchDescription: '전력 관리 장비와 배전·전기 시스템을 공급합니다.',
    aliases: ['이튼'],
    beginnerSummary: '데이터센터와 전력망에 필요한 배전·전력관리 장비를 공급하는 기업입니다.',
    businessDescription: '배전, 전력관리와 전기 인프라 장비를 제공합니다. 데이터센터와 전력망 투자가 수주잔고에 쌓인 뒤 생산·납품·매출로 전환되는 과정을 확인합니다.',
    primaryRole: '배전·전력관리 인프라',
    keyQuestions: ['수주잔고가 실제 매출로 전환되는가', '생산능력 확대가 리드타임을 줄이는가', '데이터센터와 전력망 수요를 구분해 확인할 수 있는가'],
    caution: commonCaution,
    sourceRefs: ['eaton-q1-2026-results'],
    reviewedAt: '2026-07-14',
  },
  {
    id: 'profile-meta',
    companyId: 'meta-platforms',
    slug: 'meta',
    order: 7,
    englishName: 'Meta Platforms',
    exchange: 'NASDAQ',
    industry: '디지털 광고·플랫폼',
    searchDescription: '소셜·메시징 서비스를 운영하고 디지털 광고를 판매합니다.',
    aliases: ['메타', 'Facebook', '페이스북'],
    beginnerSummary: '디지털 서비스를 운영하며 이를 뒷받침하는 AI 컴퓨팅과 데이터센터에 대규모로 투자하는 기업입니다.',
    businessDescription: '소셜·메시징 서비스를 운영하고 광고를 주요 사업으로 삼습니다. 이 페이지에서는 서비스 자체보다 AI 모델과 서비스를 운영하기 위한 데이터센터 투자와 자금조달 변화를 함께 봅니다.',
    primaryRole: 'AI 서비스 수요·데이터센터 투자',
    keyQuestions: ['설비투자 계획이 실제 집행과 가동으로 이어지는가', 'AI 인프라 비용이 현금흐름과 어떻게 연결되는가', '자금조달과 장기 투자 부담이 어떻게 변하는가'],
    caution: commonCaution,
    sourceRefs: ['meta-q1-2026-results'],
    reviewedAt: '2026-07-14',
  },
  {
    id: 'profile-supermicro',
    companyId: 'ai-datacenter-supermicro',
    slug: 'supermicro',
    order: 8,
    englishName: 'Super Micro Computer',
    exchange: 'NASDAQ',
    industry: 'AI 서버',
    searchDescription: 'AI 서버와 고성능 서버·랙 시스템을 공급합니다.',
    aliases: ['Super Micro', '슈퍼마이크로'],
    beginnerSummary: 'GPU와 네트워크·냉각 부품을 조합해 AI 서버와 랙 단위 시스템을 공급하는 기업입니다.',
    businessDescription: 'AI 서버, 고성능 서버와 랙 솔루션을 공급합니다. AI 시스템 수요가 주문·출하로 이어지는 과정과 부품 조달, 운전자본, 자금조달을 함께 확인합니다.',
    primaryRole: 'AI 서버·랙 솔루션',
    keyQuestions: ['AI 서버 수요가 실제 출하와 매출로 이어지는가', 'GPU·네트워크·냉각 부품 조달이 안정적인가', '자금조달이 생산능력과 현금흐름에 어떻게 반영되는가'],
    caution: commonCaution,
    sourceRefs: ['ir-supermicro-2026-supermicro-announces-pricing-of-equity-and-equity-lin-f33c9243'],
    reviewedAt: '2026-07-14',
  },
  {
    id: 'profile-netflix',
    companyId: 'netflix',
    slug: 'netflix',
    order: 9,
    englishName: 'Netflix, Inc.',
    exchange: 'NASDAQ',
    industry: '글로벌 스트리밍·광고',
    searchDescription: '유료 스트리밍 구독과 광고 요금제로 영화·시리즈·라이브 콘텐츠를 제공합니다.',
    aliases: ['넷플릭스', 'NFLX'],
    beginnerSummary: '전 세계 이용자에게 영상 콘텐츠를 제공하고 구독료와 광고로 수익을 얻는 스트리밍 기업입니다.',
    businessDescription: '영화·시리즈·라이브 콘텐츠를 전 세계 회원에게 제공하고 구독료를 받으며, 광고 포함 요금제에서는 광고 매출도 얻습니다. 콘텐츠 투자와 이용자 참여가 가격·회원·광고 성장으로 이어지는지를 함께 확인합니다.',
    primaryRole: '글로벌 스트리밍 구독·광고',
    keyQuestions: ['가격 인상과 회원 증가가 매출 성장으로 이어지는가', '콘텐츠 투자가 시청시간·유지율·광고 매출로 회수되는가', '성장률과 정보 가시성 변화가 현금흐름에 어떻게 반영되는가'],
    caution: commonCaution,
    sourceRefs: ['netflix-q2-2026-10q', 'netflix-q2-2026-letter'],
    reviewedAt: '2026-07-18',
  },
];

export const companyProfileCanonicalAliases: Record<string, string> = {
  'kr-semiconductors-sk-hynix': 'ai-datacenter-sk-hynix',
  'datacenter-power-eaton': 'ai-datacenter-eaton',
  'us-energy-grid-eaton': 'ai-datacenter-eaton',
  'ai-datacenter-smci': 'ai-datacenter-supermicro',
};
