import type { IndustryReport } from './types.js';

export const industryReports: IndustryReport[] = [
  {
    id: 'imf-weo-april-2026',
    slug: 'imf-weo-april-2026',
    title: 'World Economic Outlook, April 2026: Global Economy in the Shadow of War',
    titleKo: '전쟁의 그림자 아래 놓인 세계 경제',
    publisher: 'IMF',
    publishedAt: '2026-04-14',
    category: 'macro',
    sourceType: 'public-institution',
    access: 'public-full',
    summary: [
      'IMF는 무역·지정학 충격 속에서도 세계 경제가 완만한 성장세를 이어갈 것으로 봅니다.',
      '2026년과 2027년 성장률 전망의 차이는 충격 흡수 속도가 빠르지 않다는 점을 보여줍니다.',
      '금리·환율·원자재 가격을 기업 실적과 연결할 때 쓰는 글로벌 기준 시나리오입니다.',
    ],
    keyMetrics: [
      { label: '2026 세계 성장률', value: '3.1%', context: 'IMF 기준 전망', kind: 'forecast', asOf: '2026-04' },
      { label: '2027 세계 성장률', value: '3.2%', context: 'IMF 기준 전망', kind: 'forecast', asOf: '2026-04' },
    ],
    sourceRefs: ['imf-weo-april-2026'],
    marketMapIds: ['us-semiconductors', 'datacenter-power-cooling'],
    companyIds: ['us-semiconductors-nvidia', 'ai-datacenter-tsmc'],
    pickIds: ['pick-micron-ai-memory-hbm-demand'],
    tags: ['세계성장', '금리', '교역'],
    howToUse: ['실적 가이던스가 전제한 성장률과 비교합니다.', '환율과 장기금리 변화가 수요·마진에 미칠 경로를 점검합니다.'],
  },
  {
    id: 'world-bank-gep-june-2026',
    slug: 'world-bank-gep-june-2026',
    title: 'Global Economic Prospects, June 2026',
    titleKo: '세계 경제 전망: 성장의 하방 압력과 회복 경로',
    publisher: 'World Bank',
    publishedAt: '2026-06-16',
    category: 'macro',
    sourceType: 'public-institution',
    access: 'public-full',
    summary: [
      '세계은행은 2026년 글로벌 성장률이 둔화한 뒤 2027년에 일부 회복할 것으로 전망합니다.',
      '신흥국의 재정 여력과 무역 환경 차이가 지역별 투자 속도를 가를 수 있습니다.',
      '인프라·원자재·수출 기업을 볼 때 국가별 수요의 바닥을 확인하는 자료입니다.',
    ],
    keyMetrics: [
      { label: '2026 세계 성장률', value: '2.5%', context: '세계은행 기준 전망', kind: 'forecast', asOf: '2026-06' },
      { label: '2027 세계 성장률', value: '2.8%', context: '세계은행 기준 전망', kind: 'forecast', asOf: '2026-06' },
    ],
    sourceRefs: ['world-bank-gep-june-2026'],
    marketMapIds: ['reconstruction-infrastructure'],
    companyIds: ['reconstruction-caterpillar', 'reconstruction-hyundai-ec'],
    pickIds: ['pick-hyundai-engineering-reconstruction-expectation'],
    tags: ['세계성장', '신흥국', '인프라'],
    howToUse: ['국가별 성장률과 기업의 지역 매출 비중을 함께 봅니다.', '인프라 발주가 성장 전망보다 선행하는지 확인합니다.'],
  },
  {
    id: 'oecd-economic-outlook-june-2026',
    slug: 'oecd-economic-outlook-june-2026',
    title: 'OECD Economic Outlook, Volume 2026 Issue 1',
    titleKo: '압력 속의 세계 경제와 물가 경로',
    publisher: 'OECD',
    publishedAt: '2026-06-03',
    category: 'macro',
    sourceType: 'public-institution',
    access: 'public-full',
    summary: [
      'OECD는 2026년 성장 둔화와 여전히 높은 물가를 동시에 경계합니다.',
      '2027년 성장 회복 전망은 통화·재정 여건과 교역 정상화에 달려 있습니다.',
      '장기금리와 소비·설비투자 민감도를 함께 점검할 수 있는 거시 기준표입니다.',
    ],
    keyMetrics: [
      { label: '2026 세계 성장률', value: '2.8%', context: 'OECD 기준 전망', kind: 'forecast', asOf: '2026-06' },
      { label: '2027 세계 성장률', value: '3.1%', context: 'OECD 기준 전망', kind: 'forecast', asOf: '2026-06' },
      { label: '2026 G20 물가', value: '4.0%', context: 'G20 소비자물가 전망', kind: 'forecast', asOf: '2026-06' },
    ],
    sourceRefs: ['oecd-economic-outlook-june-2026'],
    marketMapIds: ['us-semiconductors', 'reconstruction-infrastructure'],
    companyIds: ['us-semiconductors-nvidia', 'reconstruction-caterpillar'],
    pickIds: ['pick-micron-ai-memory-hbm-demand'],
    tags: ['물가', '성장', '장기금리'],
    howToUse: ['성장과 물가가 같은 방향인지 먼저 확인합니다.', '밸류에이션보다 금리에 민감한 기업의 현금흐름을 우선 점검합니다.'],
  },
  {
    id: 'nvidia-fy2027-q1',
    slug: 'nvidia-fy2027-q1',
    title: 'NVIDIA Announces Financial Results for First Quarter Fiscal 2027',
    titleKo: 'AI 컴퓨팅 수요를 확인하는 NVIDIA 분기 실적',
    publisher: 'NVIDIA',
    publishedAt: '2026-05-20',
    category: 'semiconductors-ai',
    sourceType: 'company-ir',
    access: 'public-full',
    summary: [
      'NVIDIA의 분기 매출과 데이터센터 매출은 AI 인프라 투자 강도를 직접 보여줍니다.',
      '데이터센터 성장률은 GPU뿐 아니라 HBM·파운드리·전력·냉각 수요의 선행 신호가 될 수 있습니다.',
      '수요 강세를 공급망 전체의 확정 매출로 해석하지 않고 각 기업 공시로 다시 검증해야 합니다.',
    ],
    keyMetrics: [
      { label: '분기 매출', value: '$81.6B', context: 'FY2027 1분기 실제', kind: 'actual', asOf: '2026-04-26' },
      { label: '데이터센터 매출', value: '$75.2B', context: 'FY2027 1분기 실제', kind: 'actual', asOf: '2026-04-26' },
      { label: '데이터센터 성장률', value: '+92% YoY', context: '전년 동기 대비', kind: 'actual', asOf: '2026-04-26' },
    ],
    sourceRefs: ['nvidia-fy2027-q1-results'],
    marketMapIds: ['us-semiconductors', 'datacenter-power-cooling'],
    companyIds: ['us-semiconductors-nvidia', 'ai-datacenter-tsmc', 'ai-datacenter-sk-hynix', 'ai-datacenter-micron'],
    pickIds: ['pick-micron-ai-memory-hbm-demand', 'pick-lg-electronics-ai-datacenter-cooling'],
    tags: ['GPU', 'AI', '데이터센터'],
    howToUse: ['데이터센터 매출 성장과 HBM·파운드리 공급사의 실적을 교차 확인합니다.', '전력·냉각 기업의 수주잔고가 같은 속도로 늘었는지 봅니다.'],
  },
  {
    id: 'micron-fy2026-q3',
    slug: 'micron-fy2026-q3',
    title: 'Micron Technology Reports Results for the Third Quarter of Fiscal 2026',
    titleKo: 'HBM과 메모리 업황을 확인하는 Micron 분기 실적',
    publisher: 'Micron Technology',
    publishedAt: '2026-06-24',
    category: 'semiconductors-ai',
    sourceType: 'company-ir',
    access: 'public-full',
    summary: [
      'Micron의 매출과 현금흐름은 AI 메모리 수요가 실제 실적으로 전환되는 속도를 보여줍니다.',
      '다음 분기 가이던스는 HBM과 범용 메모리 가격·물량의 단기 기준점입니다.',
      'AI 수요와 메모리 사이클을 분리해 재고·CAPEX·현금흐름까지 함께 봐야 합니다.',
    ],
    keyMetrics: [
      { label: '분기 매출', value: '$41.46B', context: 'FY2026 3분기 실제', kind: 'actual' },
      { label: '영업현금흐름', value: '$25.39B', context: 'FY2026 3분기 실제', kind: 'actual' },
      { label: '다음 분기 매출 가이던스', value: '$50B ± $1B', context: 'FY2026 4분기 전망', kind: 'forecast' },
    ],
    sourceRefs: ['micron-fy2026-q3-results'],
    marketMapIds: ['us-semiconductors'],
    companyIds: ['ai-datacenter-micron', 'ai-datacenter-sk-hynix', 'ai-datacenter-samsung', 'ai-datacenter-asml'],
    pickIds: ['pick-micron-ai-memory-hbm-demand'],
    tags: ['HBM', '메모리', '현금흐름'],
    howToUse: ['가이던스와 동종 메모리 기업의 출하·가격을 비교합니다.', '영업현금흐름이 CAPEX를 감당하는지 확인합니다.'],
  },
  {
    id: 'semi-300mm-memory-2026',
    slug: 'semi-300mm-memory-2026',
    title: 'SEMI Projects 300mm Memory Equipment Investment to Surpass $50 Billion in 2026',
    titleKo: '300mm 메모리 장비 투자 전망',
    publisher: 'SEMI',
    publishedAt: '2026-06-29',
    category: 'semiconductors-ai',
    sourceType: 'industry-organization',
    access: 'public-summary',
    summary: [
      'SEMI는 300mm 메모리 장비 투자가 2026년에 500억 달러를 넘어설 것으로 봅니다.',
      '2027년 투자 확대 전망은 HBM과 첨단 메모리 생산능력 증설 흐름을 반영합니다.',
      '공개 보도자료 요약이므로 세부 지역·기업 데이터는 원문 접근 범위를 확인해야 합니다.',
    ],
    keyMetrics: [
      { label: '2026 장비 투자', value: '$52B', context: '300mm 메모리 전망', kind: 'forecast' },
      { label: '2027 장비 투자', value: '$57B', context: '300mm 메모리 전망', kind: 'forecast' },
      { label: '2026 생산능력', value: '4.1M wpm', context: '월 웨이퍼 투입량 전망', kind: 'forecast' },
    ],
    sourceRefs: ['semi-memory-fab-outlook-q2-2026'],
    marketMapIds: ['us-semiconductors', 'semiconductor-cluster-infrastructure'],
    companyIds: ['ai-datacenter-asml', 'ai-datacenter-micron', 'ai-datacenter-sk-hynix', 'cluster-ls-electric'],
    pickIds: ['pick-micron-ai-memory-hbm-demand', 'pick-dongyang-pile-semiconductor-cluster-infrastructure'],
    tags: ['300mm', '장비투자', '생산능력'],
    howToUse: ['기업별 CAPEX 발표와 산업 전망의 방향이 같은지 봅니다.', '증설 계획을 실제 장비 수주나 공장 착공으로 단정하지 않습니다.'],
  },
  {
    id: 'iea-energy-and-ai-2025',
    slug: 'iea-energy-and-ai-2025',
    title: 'Energy and AI',
    titleKo: 'AI와 에너지 시스템의 상호작용',
    publisher: 'International Energy Agency',
    publishedAt: '2025-04-10',
    category: 'power-data-centers',
    sourceType: 'public-institution',
    access: 'public-full',
    summary: [
      'IEA는 데이터센터 전력 사용이 2030년까지 두 배 이상 늘어날 수 있다고 전망합니다.',
      'AI 확산은 발전뿐 아니라 송배전·변압기·냉각 설비의 병목을 함께 만듭니다.',
      '전력 수요 전망을 개별 기업 수혜로 바로 연결하지 않고 수주·CAPEX로 검증해야 합니다.',
    ],
    keyMetrics: [
      { label: '2030 데이터센터 전력', value: '945 TWh', context: '세계 전력소비 전망', kind: 'forecast' },
      { label: '2024–30 연평균 성장', value: '~15%', context: '데이터센터 전력수요', kind: 'forecast' },
      { label: '비교 기준', value: '>2×', context: '2030년 전력 사용, 2024년 대비', kind: 'forecast' },
    ],
    sourceRefs: ['iea-energy-and-ai-2025'],
    marketMapIds: ['datacenter-power-cooling'],
    companyIds: ['datacenter-power-eaton', 'datacenter-power-vertiv', 'datacenter-power-schneider', 'datacenter-power-lg-electronics'],
    pickIds: ['pick-lg-electronics-ai-datacenter-cooling'],
    tags: ['AI전력', '데이터센터', '냉각'],
    howToUse: ['지역별 전력 인입 지연과 기업 수주잔고를 함께 확인합니다.', '전력 소비 전망과 실제 데이터센터 착공 시점을 구분합니다.'],
  },
  {
    id: 'iea-electricity-2026',
    slug: 'iea-electricity-2026',
    title: 'Electricity 2026',
    titleKo: '2026–2030 세계 전력시장 전망',
    publisher: 'International Energy Agency',
    publishedAt: '2026-02-06',
    category: 'power-data-centers',
    sourceType: 'public-institution',
    access: 'public-full',
    featured: true,
    summary: [
      'IEA는 2030년까지 세계 전력 수요가 빠르게 늘고 전력망 투자가 더 확대돼야 한다고 봅니다.',
      '데이터센터·산업 전기화·냉방 수요가 발전과 송배전 투자를 동시에 요구합니다.',
      '전력망 병목은 변압기·배전·냉각 기업을 볼 때 수주와 납기까지 확인해야 하는 이유입니다.',
    ],
    keyMetrics: [
      { label: '2026–30 수요 성장', value: '3.6% CAGR', context: '세계 전력수요 전망', kind: 'forecast' },
      { label: '2030 전력수요', value: '33,600 TWh', context: '세계 전력수요 전망', kind: 'forecast' },
      { label: '필요 전력망 투자', value: '+50%', context: '연간 약 $400B 대비 2030년', kind: 'forecast' },
    ],
    sourceRefs: ['iea-electricity-2026'],
    marketMapIds: ['datacenter-power-cooling', 'semiconductor-cluster-infrastructure'],
    companyIds: ['datacenter-power-eaton', 'datacenter-power-vertiv', 'datacenter-power-schneider', 'cluster-ls-electric', 'cluster-hyosung-heavy'],
    pickIds: ['pick-lg-electronics-ai-datacenter-cooling', 'pick-dongyang-pile-semiconductor-cluster-infrastructure'],
    tags: ['전력수요', '전력망', '변압기'],
    howToUse: ['기업의 전력 부문 수주잔고와 납기를 확인합니다.', '발전량 증가와 송배전 병목을 별도로 분석합니다.'],
  },
  {
    id: 'eaton-q1-2026',
    slug: 'eaton-q1-2026',
    title: 'Eaton Reports Record First Quarter 2026 Results',
    titleKo: '전력 인프라 수요를 확인하는 Eaton 분기 실적',
    publisher: 'Eaton',
    publishedAt: '2026-04-30',
    category: 'power-data-centers',
    sourceType: 'company-ir',
    access: 'public-full',
    summary: [
      'Eaton의 매출과 전기 부문 수주잔고는 전력 인프라 수요가 기업 실적으로 전환되는 속도를 보여줍니다.',
      'Electrical Americas 매출은 북미 데이터센터·유틸리티·산업 투자 노출을 확인하는 지표입니다.',
      '수주잔고 증가율과 매출 전환·마진·납기를 함께 봐야 공급 병목의 질을 판단할 수 있습니다.',
    ],
    keyMetrics: [
      { label: '분기 매출', value: '$7.5B', context: '2026년 1분기 실제', kind: 'actual' },
      { label: 'Electrical 수주잔고', value: '+48%', context: '전년 대비', kind: 'actual' },
      { label: 'Electrical Americas 매출', value: '$3.6B', context: '2026년 1분기 실제', kind: 'actual' },
    ],
    sourceRefs: ['eaton-q1-2026-results'],
    marketMapIds: ['datacenter-power-cooling'],
    companyIds: ['datacenter-power-eaton', 'datacenter-power-vertiv', 'datacenter-power-schneider'],
    pickIds: ['pick-lg-electronics-ai-datacenter-cooling'],
    tags: ['배전', '수주잔고', '데이터센터'],
    howToUse: ['수주잔고가 매출과 현금흐름으로 전환되는 속도를 봅니다.', '동종 전력·냉각 기업의 유기적 성장률과 비교합니다.'],
  },
  {
    id: 'eia-steo-july-2026',
    slug: 'eia-steo-july-2026',
    title: 'Short-Term Energy Outlook, July 2026',
    titleKo: '단기 에너지 가격과 미국 원유 생산 전망',
    publisher: 'U.S. Energy Information Administration',
    publishedAt: '2026-07-07',
    category: 'energy-commodities',
    sourceType: 'public-institution',
    access: 'public-full',
    summary: [
      'EIA는 지정학적 불확실성을 반영해 2026년 유가 전망을 제시합니다.',
      '2027년 유가 하락 전망은 공급·재고 정상화 시나리오를 전제로 합니다.',
      '에너지 비용에 민감한 제조·운송·건설 기업의 마진 시나리오를 점검하는 월간 기준표입니다.',
    ],
    keyMetrics: [
      { label: '2026 Brent', value: '$82/b', context: '연평균 가격 전망', kind: 'forecast' },
      { label: '2027 Brent', value: '$65/b', context: '연평균 가격 전망', kind: 'forecast' },
      { label: '2026 미국 원유 생산', value: '13.8 mb/d', context: '연평균 생산 전망', kind: 'forecast' },
    ],
    sourceRefs: ['eia-steo-july-2026'],
    marketMapIds: ['reconstruction-infrastructure'],
    companyIds: ['reconstruction-caterpillar', 'reconstruction-hd-infracore'],
    pickIds: ['pick-hyundai-engineering-reconstruction-expectation'],
    tags: ['유가', '원유생산', '에너지비용'],
    howToUse: ['기업 가이던스의 연료·운송비 전제와 비교합니다.', '월별 전망 변경 폭이 큰 경우 단일 숫자로 고정하지 않습니다.'],
  },
  {
    id: 'world-bank-commodity-outlook-april-2026',
    slug: 'world-bank-commodity-outlook-april-2026',
    title: 'Commodity Markets Outlook, April 2026',
    titleKo: '에너지 충격과 원자재 가격 전망',
    publisher: 'World Bank',
    publishedAt: '2026-04-28',
    category: 'energy-commodities',
    sourceType: 'public-institution',
    access: 'public-full',
    summary: [
      '세계은행은 에너지 가격 상승이 2026년 전체 원자재 가격을 끌어올릴 것으로 전망합니다.',
      '원자재별 수급 차이가 커 단일 지수보다 기업의 실제 투입 원재료를 봐야 합니다.',
      '건설·전력·반도체 공급망의 비용 압력을 비교하는 공통 기준입니다.',
    ],
    keyMetrics: [
      { label: '2026 에너지 가격', value: '+24%', context: '연간 전망', kind: 'forecast' },
      { label: '2026 원자재 가격', value: '+16%', context: '전체 지수 연간 전망', kind: 'forecast' },
      { label: '대상 원자재', value: '46개', context: '전망 범위', kind: 'scope' },
    ],
    sourceRefs: ['world-bank-commodity-outlook-april-2026'],
    marketMapIds: ['datacenter-power-cooling', 'reconstruction-infrastructure'],
    companyIds: ['datacenter-power-eaton', 'reconstruction-posco-holdings', 'reconstruction-caterpillar'],
    pickIds: ['pick-hyundai-engineering-reconstruction-expectation'],
    tags: ['원자재', '에너지', '투입비용'],
    howToUse: ['기업별 원재료 구성과 가격 전가력을 함께 확인합니다.', '가격 전망을 실적 확정치로 사용하지 않습니다.'],
  },
  {
    id: 'iea-critical-minerals-outlook-2025',
    slug: 'iea-critical-minerals-outlook-2025',
    title: 'Global Critical Minerals Outlook 2025',
    titleKo: '핵심광물 수요와 공급 집중도 전망',
    publisher: 'International Energy Agency',
    publishedAt: '2025-05-21',
    category: 'energy-commodities',
    sourceType: 'public-institution',
    access: 'public-full',
    summary: [
      'IEA는 현재 프로젝트 흐름만으로는 장기 구리 수요를 충분히 충족하기 어렵다고 봅니다.',
      '전력망·데이터센터·전기화가 구리 수요를 구조적으로 늘리는 핵심 동인입니다.',
      '구리 가격 움직임을 전력설비 기업과 연결할 때 공급 부족의 기간과 투자 반응을 함께 봐야 합니다.',
    ],
    keyMetrics: [
      { label: '2035 구리 공급 부족', value: '30%', context: '현재 프로젝트 파이프라인 기준', kind: 'forecast' },
      { label: '2040 구리 수요', value: '+30%', context: '현재 대비', kind: 'forecast' },
      { label: '2040 필요 광산 투자', value: '$500B', context: 'STEPS 기준 누적', kind: 'forecast' },
    ],
    sourceRefs: ['iea-critical-minerals-outlook-2025'],
    marketMapIds: ['datacenter-power-cooling', 'semiconductor-cluster-infrastructure'],
    companyIds: ['datacenter-power-eaton', 'datacenter-power-schneider', 'cluster-ls-electric', 'cluster-hyosung-heavy'],
    pickIds: ['pick-lg-electronics-ai-datacenter-cooling'],
    tags: ['구리', '핵심광물', '전력망'],
    howToUse: ['구리 가격과 전력 기업의 마진을 반대 방향 비용 요인으로도 봅니다.', '장기 부족 전망과 단기 재고·광산 공급을 분리합니다.'],
  },
  {
    id: 'world-bank-infrastructure-foundations-2026',
    slug: 'world-bank-infrastructure-foundations-2026',
    title: 'Infrastructure Foundations: From Current Assets to Future Growth',
    titleKo: '기존 인프라 자산에서 미래 성장으로',
    publisher: 'World Bank',
    publishedAt: '2026-04-24',
    category: 'construction-infrastructure',
    sourceType: 'public-institution',
    access: 'public-full',
    summary: [
      '세계은행은 인프라의 양뿐 아니라 서비스 품질·회복력·재정 지속가능성을 함께 평가합니다.',
      '국가별 진단 도구는 투자 부족과 운영 병목을 구분하는 데 쓰입니다.',
      '재건 기대를 실제 발주로 연결하기 전에 제도·재원·기존 자산 상태를 확인하는 기준입니다.',
    ],
    keyMetrics: [
      { label: '국가 범위', value: '150+개국', context: '인프라 데이터·진단 범위', kind: 'scope' },
      { label: '핵심 진단 도구', value: '2개', context: 'SRR·IER', kind: 'scope' },
    ],
    sourceRefs: ['world-bank-infrastructure-foundations-2026'],
    marketMapIds: ['reconstruction-infrastructure'],
    companyIds: ['reconstruction-hyundai-ec', 'reconstruction-samsung-ct', 'reconstruction-caterpillar'],
    pickIds: ['pick-hyundai-engineering-reconstruction-expectation'],
    tags: ['인프라', '재건', '재정'],
    howToUse: ['정책 발표와 예산·발주·착공 단계를 구분합니다.', '기존 자산 운영 개선과 신규 건설 수요를 분리합니다.'],
  },
  {
    id: 'molit-work-plan-2026',
    slug: 'molit-work-plan-2026',
    title: '2026 Ministry of Land, Infrastructure and Transport Work Plan',
    titleKo: '2026 국토교통부 업무계획: 교통·주택·인프라',
    publisher: '국토교통부',
    publishedAt: '2025-12-12',
    category: 'construction-infrastructure',
    sourceType: 'public-institution',
    access: 'public-full',
    summary: [
      '국토교통부는 광역교통망 확대와 주택 공급을 2026년 주요 실행 과제로 제시합니다.',
      '철도·고속도로 계획은 건설 수요의 방향을 보여주지만 예산·입찰·착공 확인이 필요합니다.',
      '국내 건설·전력·기초자재 기업을 볼 때 정책에서 실적으로 넘어가는 단계를 추적하는 자료입니다.',
    ],
    keyMetrics: [
      { label: '고속철도 수혜 지역', value: '41% → 53%', context: '인구 기준 확대 목표', kind: 'forecast' },
      { label: '고속도로 사업', value: '12개·311km', context: '2030년까지 개통 계획', kind: 'forecast' },
      { label: '공공주택 공급', value: '110만 호', context: '5년 계획', kind: 'forecast' },
    ],
    sourceRefs: ['molit-work-plan-2026'],
    marketMapIds: ['semiconductor-cluster-infrastructure', 'reconstruction-infrastructure'],
    companyIds: ['cluster-dongyang-pile', 'cluster-hyundai-ec', 'cluster-samsung-ct', 'cluster-ls-electric'],
    pickIds: ['pick-dongyang-pile-semiconductor-cluster-infrastructure', 'pick-kcc-silicone-margin-asset-value'],
    tags: ['국토교통', '주택', 'SOC'],
    howToUse: ['업무계획을 수주 확정으로 해석하지 않고 후속 예산·입찰 공고를 확인합니다.', '지역·공종별 매출 노출을 기업 공시에서 교차 검증합니다.'],
  },
  {
    id: 'us-census-construction-spending-may-2026',
    slug: 'us-census-construction-spending-may-2026',
    title: 'Construction Spending, May 2026',
    titleKo: '미국 건설지출: 민간·공공·도로 투자 현황',
    publisher: 'U.S. Census Bureau',
    publishedAt: '2026-07-01',
    category: 'construction-infrastructure',
    sourceType: 'public-institution',
    access: 'public-full',
    summary: [
      '미국 건설지출은 민간과 공공 투자의 실제 집행 속도를 월별로 보여줍니다.',
      '공공·도로 지출은 인프라 장비·자재 수요의 동행 지표로 활용할 수 있습니다.',
      '계절조정 연율이므로 월간 변동을 기업 매출과 직접 동일시하지 않아야 합니다.',
    ],
    keyMetrics: [
      { label: '전체 건설지출', value: '$2,210.2B', context: '계절조정 연율', kind: 'actual', asOf: '2026-05' },
      { label: '공공 건설지출', value: '$541.2B', context: '계절조정 연율', kind: 'actual', asOf: '2026-05' },
      { label: '고속도로 지출', value: '$150.6B', context: '계절조정 연율', kind: 'actual', asOf: '2026-05' },
    ],
    sourceRefs: ['us-census-construction-spending-may-2026'],
    marketMapIds: ['reconstruction-infrastructure'],
    companyIds: ['reconstruction-caterpillar', 'reconstruction-hd-infracore', 'reconstruction-posco-holdings'],
    pickIds: ['pick-hyundai-engineering-reconstruction-expectation'],
    tags: ['건설지출', '도로', '공공투자'],
    howToUse: ['계절조정 연율과 실제 기업 분기 매출의 기준 차이를 확인합니다.', '민간·공공·공종별 방향을 장비 주문과 비교합니다.'],
  },
];
