import type { RelationDefinition } from './types.js';

export const relationDefinitions: RelationDefinition[] = [
  {
    id: 'rates-nasdaq',
    title: '금리 부담 완화와 나스닥',
    shortTitle: '금리 부담과 나스닥',
    beginnerQuestion: '금리 부담이 줄어들 때 나스닥도 올랐나요?',
    macroSeriesId: 'DGS10',
    macroLabel: '미국 10년물 국채금리',
    macroComparisonLabel: '금리 부담 완화 방향',
    macroUnit: '%',
    marketSymbol: '^IXIC',
    marketLabel: 'NASDAQ Composite',
    marketCurrency: 'USD',
    frequency: 'daily',
    macroOrientation: 'inverse',
    defaultWindow: '3m',
    availableWindows: ['3m', '6m', '1y'],
    interpretation: '금리 하락 방향과 나스닥의 일별 수익률이 최근 같은 방향으로 움직였는지 비교합니다.',
    comparisonDescription: '미국 10년물 금리의 하락 방향과 나스닥의 일별 수익률을 비교했습니다.',
    whyDifferent: '기업 실적, 정책, 환율, 투자심리 등 다른 요인도 나스닥에 영향을 주기 때문에 항상 같게 움직이지는 않습니다.',
    caveats: ['원본 금리는 그대로 두고, 변화값만 금리 부담 완화 방향이 양수가 되도록 뒤집습니다.'],
    sourceRefs: ['fred-series-dgs10', 'yahoo-finance-chart-ixic'],
    reportIds: ['imf-weo-april-2026', 'oecd-economic-outlook-june-2026'],
    marketMapIds: ['us-semiconductors'],
    fredLimit: 400,
    yahooRange: '2y',
  },
  {
    id: 'financial-conditions-sp500',
    title: '금융여건 완화와 S&P 500',
    shortTitle: '금융여건과 S&P 500',
    beginnerQuestion: '금융여건이 완화될 때 S&P 500도 같은 방향으로 움직였나요?',
    macroSeriesId: 'NFCI',
    macroLabel: 'Chicago Fed National Financial Conditions Index',
    macroComparisonLabel: '금융여건 완화 방향',
    macroUnit: '지수',
    marketSymbol: '^GSPC',
    marketLabel: 'S&P 500',
    marketCurrency: 'USD',
    frequency: 'weekly',
    macroOrientation: 'inverse',
    defaultWindow: '3m',
    availableWindows: ['3m', '6m', '1y'],
    interpretation: 'NFCI의 완화 방향과 S&P 500의 주간 수익률이 최근 함께 움직였는지 비교합니다.',
    comparisonDescription: 'NFCI의 주간 하락 방향과 같은 날 또는 직전 거래일의 S&P 500 주간 수익률을 비교했습니다.',
    whyDifferent: '금융여건 외에도 실적 전망, 물가, 정책 기대와 시장 심리가 주가에 영향을 주므로 매주 같은 방향이 되지는 않습니다.',
    caveats: ['NFCI는 값이 내려갈수록 완화 방향이며, 비교 화면에서는 완화 방향을 양수로 변환합니다.'],
    sourceRefs: ['fred-series-nfci', 'yahoo-finance-chart-gspc'],
    reportIds: ['imf-weo-april-2026', 'oecd-economic-outlook-june-2026'],
    marketMapIds: ['us-semiconductors'],
    fredLimit: 80,
    yahooRange: '2y',
  },
  {
    id: 'industrial-production-copper',
    title: '산업생산과 구리 가격',
    shortTitle: '산업생산과 구리',
    beginnerQuestion: '산업생산과 구리 가격은 최근 함께 움직였나요?',
    macroSeriesId: 'INDPRO',
    macroLabel: '미국 산업생산지수',
    macroComparisonLabel: '산업생산 전월 대비 변화',
    macroUnit: '지수',
    marketSymbol: 'HG=F',
    marketLabel: '구리 선물',
    marketCurrency: 'USD',
    frequency: 'monthly',
    macroOrientation: 'raw',
    defaultWindow: '1y',
    availableWindows: ['1y', '2y'],
    interpretation: '산업생산의 전월 대비 변화율과 월말 구리 가격의 전월 대비 수익률을 비교합니다.',
    comparisonDescription: '미국 산업생산의 전월 대비 변화율과 같은 달 마지막 유효 구리 종가의 전월 대비 수익률을 비교했습니다.',
    whyDifferent: '구리 가격에는 광산 공급, 재고, 환율과 중국 수요도 영향을 주므로 산업생산 증가의 직접 결과로 볼 수 없습니다.',
    caveats: ['구리 가격 상승을 산업생산 증가의 직접 결과로 단정하지 않습니다.'],
    sourceRefs: ['fred-series-indpro', 'yahoo-finance-chart-hg-f'],
    reportIds: ['world-bank-commodity-outlook-april-2026', 'iea-critical-minerals-outlook-2025'],
    marketMapIds: ['datacenter-power-cooling'],
    fredLimit: 30,
    yahooRange: '3y',
  },
];
