import type { CompanyEvent, CompanyEventCompany } from './types.js';

export const companyEventCompanies: CompanyEventCompany[] = [
  { id: 'ai-datacenter-sk-hynix', name: 'SK하이닉스', country: 'KR', countryLabel: '한국', ticker: '000660.KS' },
  { id: 'datacenter-power-lg-electronics', name: 'LG전자', country: 'KR', countryLabel: '한국', ticker: '066570.KS' },
  { id: 'us-semiconductors-nvidia', name: 'NVIDIA', country: 'US', countryLabel: '미국', ticker: 'NVDA' },
  { id: 'ai-datacenter-micron', name: 'Micron', country: 'US', countryLabel: '미국', ticker: 'MU' },
  { id: 'ai-datacenter-dell', name: 'Dell', country: 'US', countryLabel: '미국', ticker: 'DELL' },
  { id: 'ai-datacenter-eaton', name: 'Eaton', country: 'US', countryLabel: '미국', ticker: 'ETN' },
  { id: 'meta-platforms', name: 'Meta', country: 'US', countryLabel: '미국', ticker: 'META' },
  { id: 'ai-datacenter-supermicro', name: 'Supermicro', country: 'US', countryLabel: '미국', ticker: 'SMCI' },
  { id: 'netflix', name: 'Netflix', country: 'US', countryLabel: '미국', ticker: 'NFLX' },
];

const standardCaution = '공식 발표 한 건이 향후 실적이나 시장 가격을 보장하지 않으며, 산업 전체의 상태를 자동으로 바꾸지도 않습니다.';

export const companyEvents: CompanyEvent[] = [
  {
    id: 'sk-hynix-q1-2026-results',
    companyId: 'ai-datacenter-sk-hynix',
    eventDate: '2026-04-23',
    reviewedAt: '2026-07-12',
    group: 'earnings-guidance',
    eventType: 'earnings',
    stage: 'reported',
    title: '1분기 실적과 AI 메모리 투자 방향 발표',
    factualSummary: 'SK하이닉스는 2026년 1분기 매출 52조5,763억원과 영업이익 37조6,103억원을 발표하고, M15X 가동 준비와 용인 클러스터 인프라에 투자를 집중하겠다고 밝혔습니다.',
    whyItMatters: 'HBM 수요가 실제 실적과 생산기반 투자로 함께 이어지는지를 확인할 수 있는 회사 발표입니다.',
    nextCheckpoints: ['M15X 양산 일정', '용인 클러스터 투자 집행', 'HBM 출하와 재고 변화'],
    sourceRefs: ['sk-hynix-q1-2026-results'],
    bottleneckIds: ['semiconductor-fab-infrastructure'],
    demandSupplyIds: ['semiconductor-fab-infrastructure-demand-supply'],
    marketMapIds: ['us-semiconductors'],
    reportIds: ['micron-fy2026-q3'],
    pickIds: ['pick-sk-hynix-ai-overbuild-selloff', 'pick-sk-hynix-hbm'],
    caution: standardCaution,
  },
  {
    id: 'sk-hynix-hbm4-production-ready-2025',
    companyId: 'ai-datacenter-sk-hynix',
    eventDate: '2025-09-12',
    reviewedAt: '2026-07-12',
    group: 'capex-capacity',
    eventType: 'capacity-expansion',
    stage: 'completed',
    title: 'HBM4 개발 완료와 양산 체계 준비 발표',
    factualSummary: 'SK하이닉스는 HBM4 개발을 완료하고 양산 준비를 마쳤으며, 고객 일정에 맞춰 제품을 공급할 준비가 됐다고 발표했습니다.',
    whyItMatters: '제품 개발 완료와 실제 양산·고객 공급 사이의 다음 단계를 구분해서 볼 수 있습니다.',
    nextCheckpoints: ['고객 인증 완료', '실제 양산 출하', '초기 수율과 공급량'],
    sourceRefs: ['sk-hynix-hbm4-production-2025'],
    bottleneckIds: ['semiconductor-fab-infrastructure'],
    demandSupplyIds: ['semiconductor-fab-infrastructure-demand-supply'],
    marketMapIds: ['us-semiconductors'],
    reportIds: ['micron-fy2026-q3'],
    pickIds: ['pick-sk-hynix-hbm'],
    caution: standardCaution,
  },
  {
    id: 'lg-electronics-wanju-hvac-mou-2026',
    companyId: 'datacenter-power-lg-electronics',
    eventDate: '2026-03-04',
    reviewedAt: '2026-07-12',
    group: 'orders-contracts',
    eventType: 'supply-agreement',
    stage: 'planned',
    title: '완주 AI 데이터센터 HVAC 공급 협약',
    factualSummary: 'LG전자는 완주군·테크노그린·한전KDN과 20MW급 AI 데이터센터 구축 MOU를 체결하고 칠러·CRAH·액체냉각 솔루션 공급을 추진한다고 발표했습니다.',
    whyItMatters: '냉각 장비 수요가 구체적인 프로젝트 협약으로 이어졌지만 아직 최종 매출과 설치 완료를 뜻하지는 않습니다.',
    nextCheckpoints: ['본계약 체결', '장비 공급 규모', '2029년까지 구축 일정'],
    sourceRefs: ['lge-story-newsroom-235685-63746d17'],
    bottleneckIds: ['data-center-power-cooling'],
    demandSupplyIds: ['data-center-power-cooling-demand-supply'],
    marketMapIds: ['datacenter-power-cooling'],
    reportIds: ['iea-energy-and-ai-2025'],
    pickIds: ['pick-lg-electronics-ai-datacenter-cooling'],
    caution: standardCaution,
  },
  {
    id: 'nvidia-fy2027-q1-results',
    companyId: 'us-semiconductors-nvidia',
    eventDate: '2026-05-20',
    reviewedAt: '2026-07-12',
    group: 'earnings-guidance',
    eventType: 'earnings',
    stage: 'reported',
    title: 'FY2027 1분기 데이터센터 실적 발표',
    factualSummary: 'NVIDIA는 FY2027 1분기 매출 816억달러와 데이터센터 매출 752억달러를 발표했습니다.',
    whyItMatters: 'AI 컴퓨팅 수요가 GPU뿐 아니라 메모리·전력·냉각 수요 배경과 연결되는지 교차 확인하는 기준입니다.',
    nextCheckpoints: ['다음 분기 데이터센터 매출', '신제품 공급 일정', '고객별 투자 집행'],
    sourceRefs: ['nvidia-fy2027-q1-results'],
    bottleneckIds: ['data-center-power-cooling', 'semiconductor-fab-infrastructure'],
    demandSupplyIds: ['data-center-power-cooling-demand-supply', 'semiconductor-fab-infrastructure-demand-supply'],
    marketMapIds: ['us-semiconductors', 'datacenter-power-cooling'],
    reportIds: ['nvidia-fy2027-q1'],
    pickIds: ['pick-nvidia-ai-demand'],
    caution: standardCaution,
  },
  {
    id: 'micron-fy2026-q3-results',
    companyId: 'ai-datacenter-micron',
    eventDate: '2026-06-24',
    reviewedAt: '2026-07-12',
    group: 'earnings-guidance',
    eventType: 'earnings',
    stage: 'reported',
    title: 'FY2026 3분기 메모리 실적 발표',
    factualSummary: 'Micron은 FY2026 3분기 실적과 HBM·DRAM·NAND 수요 및 다음 분기 전망을 공식 발표했습니다.',
    whyItMatters: '메모리 가격과 출하, HBM 공급 확대가 실제 매출과 현금흐름에 반영되는지 확인할 수 있습니다.',
    nextCheckpoints: ['HBM 매출 비중', '재고와 가격 변화', '다음 분기 설비투자'],
    sourceRefs: ['micron-fy2026-q3-results'],
    bottleneckIds: ['semiconductor-fab-infrastructure'],
    demandSupplyIds: ['semiconductor-fab-infrastructure-demand-supply'],
    marketMapIds: ['us-semiconductors'],
    reportIds: ['micron-fy2026-q3'],
    pickIds: ['pick-micron-ai-memory-hbm-demand'],
    caution: standardCaution,
  },
  {
    id: 'micron-virginia-capacity-2026',
    companyId: 'ai-datacenter-micron',
    eventDate: '2026-05-22',
    reviewedAt: '2026-07-12',
    group: 'capex-capacity',
    eventType: 'capacity-expansion',
    stage: 'in-progress',
    title: '버지니아 DRAM 생산 확대 시작',
    factualSummary: 'Micron은 버지니아 Manassas 팹에서 1α DRAM 생산을 시작했으며, 20억달러가 넘는 투자로 해당 팹의 DDR4 웨이퍼 공급능력을 네 배로 늘릴 계획이라고 발표했습니다.',
    whyItMatters: '발표된 설비투자가 실제 생산 시작과 공급능력 확대로 전환되는 과정을 보여줍니다.',
    nextCheckpoints: ['2026년 말 제품 인증', '웨이퍼 공급능력 증가', '투자 집행과 양산 수율'],
    sourceRefs: ['micron-virginia-expansion-2026'],
    bottleneckIds: ['semiconductor-fab-infrastructure'],
    demandSupplyIds: ['semiconductor-fab-infrastructure-demand-supply'],
    marketMapIds: ['us-semiconductors'],
    reportIds: ['micron-fy2026-q3'],
    pickIds: ['pick-micron-ai-memory-hbm-demand'],
    caution: standardCaution,
  },
  {
    id: 'dell-fy2027-q1-ai-orders',
    companyId: 'ai-datacenter-dell',
    eventDate: '2026-05-28',
    reviewedAt: '2026-07-12',
    group: 'orders-contracts',
    eventType: 'order',
    stage: 'reported',
    title: 'AI 서버 주문 244억달러 발표',
    factualSummary: 'Dell은 FY2027 1분기에 AI 주문 244억달러를 확보하고 AI 서버 매출 161억달러를 인식했으며, 연간 AI 서버 매출 전망을 600억달러로 높였다고 발표했습니다.',
    whyItMatters: '서버 주문이 매출로 전환되는 속도와 GPU·메모리·전력·냉각 수요를 함께 확인할 수 있습니다.',
    nextCheckpoints: ['주문 취소·변경 여부', '서버 매출 전환', 'AI 서버 부문 마진'],
    sourceRefs: ['dell-fy2027-q1-results'],
    bottleneckIds: ['data-center-power-cooling'],
    demandSupplyIds: ['data-center-power-cooling-demand-supply'],
    marketMapIds: ['us-semiconductors', 'datacenter-power-cooling'],
    reportIds: ['nvidia-fy2027-q1'],
    pickIds: ['pick-dell-ai-server-demand', 'pick-dell-ai-server-earnings-check'],
    caution: standardCaution,
  },
  {
    id: 'dell-fy2026-full-year-results',
    companyId: 'ai-datacenter-dell',
    eventDate: '2026-02-26',
    reviewedAt: '2026-07-12',
    group: 'earnings-guidance',
    eventType: 'guidance',
    stage: 'reported',
    title: 'FY2026 실적과 FY2027 전망 발표',
    factualSummary: 'Dell은 FY2026 매출 1,135억달러와 연간 AI 최적화 서버 주문 640억달러 이상, 기말 수주잔고 430억달러를 발표했습니다.',
    whyItMatters: '한 분기의 주문이 아니라 연간 주문·출하·수주잔고가 어떻게 이어졌는지 비교할 수 있습니다.',
    nextCheckpoints: ['기말 수주잔고 전환', 'FY2027 매출 전망 달성', '현금흐름과 재고'],
    sourceRefs: ['dell-technologies-delivers-fourth-quarter-and-full-year-fiscal-2026-results'],
    bottleneckIds: ['data-center-power-cooling'],
    demandSupplyIds: ['data-center-power-cooling-demand-supply'],
    marketMapIds: ['us-semiconductors'],
    reportIds: ['nvidia-fy2027-q1'],
    pickIds: ['pick-dell-ai-server-earnings-check', 'pick-dell-ai-server-demand'],
    caution: standardCaution,
  },
  {
    id: 'eaton-q1-2026-backlog',
    companyId: 'ai-datacenter-eaton',
    eventDate: '2026-04-30',
    reviewedAt: '2026-07-12',
    group: 'orders-contracts',
    eventType: 'backlog',
    stage: 'reported',
    title: '전기 부문 수주잔고 증가 발표',
    factualSummary: 'Eaton은 2026년 1분기 Electrical 부문 수주잔고가 전년 대비 48% 늘었고 Electrical Americas의 12개월 평균 주문이 42% 증가했다고 발표했습니다.',
    whyItMatters: '전력기기 수요가 공급사의 수주잔고에 쌓이는 속도와 생산능력 확대 필요성을 함께 볼 수 있습니다.',
    nextCheckpoints: ['수주잔고 매출 전환', '리드타임 변화', '생산능력 투자 집행'],
    sourceRefs: ['eaton-q1-2026-results'],
    bottleneckIds: ['grid-transformers-high-voltage', 'data-center-power-cooling'],
    demandSupplyIds: ['grid-equipment-demand-supply', 'data-center-power-cooling-demand-supply'],
    marketMapIds: ['datacenter-power-cooling'],
    reportIds: ['eaton-q1-2026'],
    pickIds: [],
    caution: standardCaution,
  },
  {
    id: 'meta-q1-2026-capex-revised',
    companyId: 'meta-platforms',
    eventDate: '2026-04-29',
    reviewedAt: '2026-07-12',
    group: 'capex-capacity',
    eventType: 'capex',
    stage: 'revised',
    title: '2026년 설비투자 전망 상향',
    factualSummary: 'Meta는 2026년 설비투자 전망을 기존 1,150억~1,350억달러에서 1,250억~1,450억달러로 높였으며, 부품 가격과 향후 데이터센터 용량 비용을 이유로 설명했습니다.',
    whyItMatters: 'AI 인프라 수요 배경이 실제 설비투자 전망 변경으로 나타났지만 집행 완료와는 구분해야 합니다.',
    nextCheckpoints: ['분기별 실제 설비투자', '데이터센터 가동 일정', '영업현금흐름 대비 투자 규모'],
    sourceRefs: ['meta-q1-2026-results'],
    bottleneckIds: ['data-center-power-cooling'],
    demandSupplyIds: ['data-center-power-cooling-demand-supply'],
    marketMapIds: ['datacenter-power-cooling'],
    reportIds: ['iea-energy-and-ai-2025'],
    pickIds: ['pick-meta-ai-compute-cloud-option'],
    caution: standardCaution,
  },
  {
    id: 'meta-senior-notes-2025',
    companyId: 'meta-platforms',
    eventDate: '2025-11-03',
    reviewedAt: '2026-07-12',
    group: 'financing-structure',
    eventType: 'debt',
    stage: 'completed',
    title: '300억달러 선순위 채권 발행 완료',
    factualSummary: 'Meta는 2030년부터 2065년까지 만기가 나뉜 선순위 채권 여섯 종류를 합계 300억달러 규모로 발행 완료했다고 SEC 8-K에서 밝혔습니다.',
    whyItMatters: '대규모 장기 투자와 함께 부채 만기·이자비용·현금흐름 구조가 어떻게 달라지는지 확인할 수 있습니다.',
    nextCheckpoints: ['분기 이자비용', '순현금과 총부채 변화', '조달자금 사용 내역'],
    sourceRefs: ['meta-2025-senior-notes-8k'],
    officialFiling: { jurisdiction: 'us', form: '8-K', itemCodes: ['8.01'], accessionNumber: '0001193125-25-262593' },
    bottleneckIds: [],
    demandSupplyIds: [],
    marketMapIds: ['datacenter-power-cooling'],
    reportIds: [],
    pickIds: ['pick-meta-ai-compute-cloud-option'],
    caution: standardCaution,
  },
  {
    id: 'supermicro-equity-financing-2026',
    companyId: 'ai-datacenter-supermicro',
    eventDate: '2026-06-11',
    reviewedAt: '2026-07-12',
    group: 'financing-structure',
    eventType: 'equity-financing',
    stage: 'in-progress',
    title: 'AI 서버 주문 대응 자금조달 조건 확정',
    factualSummary: 'Supermicro는 보통주·의무전환우선주·ATM을 합친 잠재적 자금조달 규모를 최대 70억달러로 제시하고, 최근 받은 약 390억달러의 AI 서버 주문 대응 부품 구매 등에 사용할 계획이라고 발표했습니다.',
    whyItMatters: '주문 확대와 운전자금 필요가 주식 관련 자금조달로 이어진 구조를 확인할 수 있습니다.',
    nextCheckpoints: ['공모 거래 종결', 'ATM 실제 사용액', '390억달러 주문의 매출 전환'],
    sourceRefs: ['ir-supermicro-2026-supermicro-announces-pricing-of-equity-and-equity-lin-f33c9243'],
    bottleneckIds: ['data-center-power-cooling'],
    demandSupplyIds: ['data-center-power-cooling-demand-supply'],
    marketMapIds: ['us-semiconductors'],
    reportIds: ['nvidia-fy2027-q1'],
    pickIds: ['pick-smci-ai-server-funding-dilution'],
    caution: standardCaution,
  },
  {
    id: 'netflix-q2-2026-guidance-disclosure',
    companyId: 'netflix',
    eventDate: '2026-07-16',
    reviewedAt: '2026-07-18',
    group: 'earnings-guidance',
    eventType: 'guidance',
    stage: 'reported',
    title: '2분기 실적과 3분기 전망·시청시간 공시 빈도 변경',
    factualSummary: 'Netflix는 2분기 매출 125억5,994만달러와 영업이익 41억9,261만달러를 발표하고, 3분기 매출 128억6,000만달러와 희석 EPS 0.82달러를 전망했습니다. 2027년부터 종합 시청시간 보고는 연 1회로 전환하되 주간 Top 10은 유지한다고 밝혔습니다.',
    whyItMatters: '실적의 절대 수준과 다음 분기 성장 기대, 투자자가 성장의 질을 확인할 수 있는 정보 빈도가 동시에 달라진 사건입니다.',
    nextCheckpoints: ['3분기 매출·영업이익률 전망 달성', '광고·가격·회원 증가의 기여', '연 1회 시청시간 보고의 범위와 세분성'],
    sourceRefs: ['netflix-q2-2026-8k', 'netflix-q2-2026-letter'],
    officialFiling: { jurisdiction: 'us', form: '8-K', itemCodes: ['2.02', '9.01'], accessionNumber: '0001065280-26-000211' },
    bottleneckIds: [],
    demandSupplyIds: [],
    marketMapIds: [],
    reportIds: [],
    pickIds: [],
    caution: standardCaution,
  },
];
