import type { DemandSupplyEntry } from './types.js';

export const demandSupplyEntries: DemandSupplyEntry[] = [
  {
    id: 'grid-equipment-demand-supply',
    title: '변압기·고압 전력기기',
    shortTitle: '전력기기',
    beginnerQuestion: '산업·건설 배경과 전력기기 공급 부족을 함께 보면 어떤가요?',
    bottleneckId: 'grid-transformers-high-voltage',
    macroIndicatorIds: ['us-industrial-production', 'us-manufacturing-utilization', 'us-building-permits'],
    reportIds: ['iea-electricity-2026', 'eaton-q1-2026'],
    marketMapIds: ['datacenter-power-cooling'],
    demandContext: '산업생산·가동률·건설 활동은 전력기기 수요를 이해할 때 함께 보는 배경입니다.',
    supplyContext: '기존 전력기기 병목의 공식 근거와 편집 검토 상태를 그대로 확인합니다.',
    caution: '개별 변압기 주문량을 직접 나타내는 거시지표는 아닙니다.',
  },
  {
    id: 'data-center-power-cooling-demand-supply',
    title: '데이터센터 전력·냉각',
    shortTitle: '데이터센터 인프라',
    beginnerQuestion: '산업 활동 배경과 데이터센터 전력·냉각 공급 부족을 함께 보면 어떤가요?',
    bottleneckId: 'data-center-power-cooling',
    macroIndicatorIds: ['us-industrial-production', 'us-manufacturing-utilization'],
    reportIds: ['iea-energy-and-ai-2025', 'iea-electricity-2026'],
    marketMapIds: ['datacenter-power-cooling'],
    demandContext: '산업생산과 제조업 가동률은 데이터센터 인프라 수요를 둘러싼 넓은 산업 활동 배경입니다.',
    supplyContext: '전력 인입·배전·냉각 설비의 기존 병목 상태와 완화 신호를 함께 봅니다.',
    caution: 'FRED 거시지표만으로 데이터센터 전력 수요를 직접 측정하지 않습니다.',
  },
  {
    id: 'copper-grid-metals-demand-supply',
    title: '구리·전력망 핵심 금속',
    shortTitle: '구리·핵심 금속',
    beginnerQuestion: '산업·건설 배경과 구리 공급 관찰 상태를 함께 보면 어떤가요?',
    bottleneckId: 'copper-grid-metals',
    macroIndicatorIds: ['us-industrial-production', 'us-building-permits'],
    relationIds: ['industrial-production-copper'],
    reportIds: ['world-bank-commodity-outlook-april-2026', 'iea-critical-minerals-outlook-2025'],
    marketMapIds: ['datacenter-power-cooling'],
    demandContext: '산업생산과 건축허가는 전력망·건설에 쓰이는 금속 수요를 이해하는 배경입니다.',
    supplyContext: '장기 공급 부족 전망과 단기 불확실성을 함께 반영한 기존 관찰 상태를 사용합니다.',
    caution: '구리 가격이나 물리적 주문량을 이 페이지에서 새로 계산하지 않습니다.',
  },
  {
    id: 'semiconductor-fab-infrastructure-demand-supply',
    title: '반도체 팹 인프라',
    shortTitle: '팹 인프라',
    beginnerQuestion: '제조·건설 배경과 반도체 팹 인프라 공급 상태를 함께 보면 어떤가요?',
    bottleneckId: 'semiconductor-fab-infrastructure',
    macroIndicatorIds: ['us-manufacturing-utilization', 'us-building-permits', 'us-industrial-production'],
    reportIds: ['semi-300mm-memory-2026', 'iea-electricity-2026'],
    marketMapIds: ['semiconductor-cluster-infrastructure'],
    demandContext: '가동률·건축허가·산업생산은 팹 기반시설 수요를 이해하는 넓은 배경입니다.',
    supplyContext: '팹 전력·건설 인프라의 기존 관찰 상태와 제한적 신뢰도를 그대로 표시합니다.',
    caution: '반도체 생산량이나 개별 팹 투자액을 직접 측정하는 지표라고 해석하지 않습니다.',
  },
];
