import type { ContentSource } from './types.js';

export const contentSources: ContentSource[] = [
  {
    id: 'kind-krx-20260318002468',
    kind: 'kind-filing',
    title: '동양파일 2025 사업보고서',
    publisher: '한국거래소 KIND',
    url: 'https://kind.krx.co.kr/common/disclsviewer.do?acptno=20260318002468&langTpCd=0&method=search&orgid=F&rcpno=20260318001680&tran=Y',
  },
  {
    id: 'kind-krx-20260515000989',
    kind: 'kind-filing',
    title: '동양파일 2026년 1분기 분기보고서',
    publisher: '한국거래소 KIND',
    url: 'https://kind.krx.co.kr/common/disclsviewer.do?acptno=20260515000989&docno=&method=search&viewerhost=',
  },
  {
    id: 'v-daum-v-20260626094305527-19a14080',
    kind: 'news',
    title: 'SBS Biz 호남권 반도체 클러스터 관련주 시황',
    publisher: 'SBS Biz',
    url: 'https://v.daum.net/v/20260626094305527',
  },
  {
    id: 'yahoo-finance-chart-228340-kq',
    kind: 'market-data',
    title: 'Yahoo Finance 228340.KQ 공개 차트',
    publisher: 'Yahoo Finance',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/228340.KQ?range=5d&interval=1d',
  },
  {
    id: 'samsung-electronics-2026-q1-dart-report',
    kind: 'dart-filing',
    title: '삼성전자 2026년 1분기 분기보고서',
    publisher: 'DART',
    url: 'https://dart.fss.or.kr/dsaf001/main.do?rcpNo=20260515002181',
  },
  {
    id: 'samsung-electronics-earnings-releases',
    kind: 'company-ir',
    title: 'Samsung Electronics Earnings Releases',
    publisher: 'Samsung Electronics',
    url: 'https://www.samsung.com/global/ir/financial-information/earnings-release/',
  },
  {
    id: 'dell-technologies-fy2026-q1-results',
    kind: 'company-release',
    title: 'Dell Technologies Delivers First Quarter Fiscal 2026 Financial Results',
    publisher: 'Dell Technologies',
    url: 'https://www.dell.com/en-us/dt/corporate/newsroom/announcements/detailpage.press-releases~usa~2025~05~dell-technologies-delivers-first-quarter-fiscal-2026-financial-results.htm',
    publishedAt: '2025-05-29',
  },
  {
    id: 'sec-gov-nvda-20260125',
    kind: 'sec-filing',
    title: 'SEC 원문 보고서',
    publisher: 'SEC',
    url: 'https://www.sec.gov/Archives/edgar/data/1045810/000104581026000021/nvda-20260125.htm',
  },
  {
    id: 'posco-future-m-ir-reference',
    kind: 'company-ir',
    title: '포스코퓨처엠 IR 자료실',
    publisher: 'POSCO Future M',
    url: 'https://www.poscofuturem.com/ir/reference.do',
  },
  {
    id: 'iea-global-ev-outlook-2025',
    kind: 'industry-data',
    title: 'Global EV Outlook 2025',
    publisher: 'IEA',
    url: 'https://www.iea.org/reports/global-ev-outlook-2025',
  },
  {
    id: 'kind-krx-20260515001457',
    kind: 'kind-filing',
    title: 'KCC 2026년 1분기 분기보고서',
    publisher: '한국거래소 KIND',
    url: 'https://kind.krx.co.kr/common/disclsviewer.do?acptno=20260515001457&docno=&method=search&viewerhost=',
  },
  {
    id: 'stock-mk-news-view-1110153-99ac0782',
    kind: 'news',
    title: '매일경제 KCC 실적·자산가치 보도',
    publisher: '매일경제',
    url: 'https://stock.mk.co.kr/news/view/1110153',
  },
  {
    id: 'mt-06-25-2026062508592086578-81e25849',
    kind: 'news',
    title: '머니투데이 KCC 실리콘·도료 전망 보도',
    publisher: '머니투데이',
    url: 'https://www.mt.co.kr/amp/stock/2026/06/25/2026062508592086578',
  },
  {
    id: 'yahoo-finance-chart-002380-ks',
    kind: 'market-data',
    title: 'Yahoo Finance 002380.KS 공개 차트',
    publisher: 'Yahoo Finance',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/002380.KS?range=5d&interval=1d',
  },
  {
    id: 'newsroom-hertz-press-releases-press-release-details-hertz-announces-prop-379e936c',
    kind: 'company-release',
    title: 'Hertz 3억 달러 PIK 채권 제안 발표',
    publisher: 'Hertz',
    url: 'https://newsroom.hertz.com/press-releases/press-release-details/hertz-announces-proposed-offering-of-300-million-of-exchangeable-senior-first-lien-secured-pik-notes/',
  },
  {
    id: 'newsroom-hertz-press-releases-press-release-details-hertz-announces-pric-95a9f82b',
    kind: 'company-release',
    title: 'Hertz 3억5천만 달러 PIK 채권 가격 확정',
    publisher: 'Hertz',
    url: 'https://newsroom.hertz.com/press-releases/press-release-details/hertz-announces-pricing-of-upsized-350-million-of-exchangeable-senior-first-lien-secured-pik-notes/',
  },
  {
    id: 'newsroom-hertz-press-releases-press-release-details-hertz-announces-pric-89198328',
    kind: 'company-release',
    title: 'Hertz 보통주 37,037,037주 가격 확정',
    publisher: 'Hertz',
    url: 'https://newsroom.hertz.com/press-releases/press-release-details/hertz-announces-pricing-of-offering-of-37037037-shares-of-common-stock/',
  },
  {
    id: 'sec-gov-tm2618542-1-s3asr',
    kind: 'sec-filing',
    title: 'SEC Hertz 보통주 공모 설명서',
    publisher: 'SEC',
    url: 'https://www.sec.gov/Archives/edgar/data/0001657853/000110465926077051/tm2618542-1_s3asr.htm',
  },
  {
    id: 'sec-gov-htzz-20260331',
    kind: 'sec-filing',
    title: 'Hertz 2026년 1분기 10-Q',
    publisher: 'SEC',
    url: 'https://www.sec.gov/Archives/edgar/data/1657853/000165785326000024/htzz-20260331.htm',
  },
  {
    id: 'yahoo-finance-chart-htz',
    kind: 'market-data',
    title: 'Yahoo Finance HTZ 공개 차트',
    publisher: 'Yahoo Finance',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/HTZ?range=5d&interval=1d',
  },
  {
    id: 'kind-krx-20260323001354',
    kind: 'kind-filing',
    title: '제주반도체 2025 사업보고서',
    publisher: '한국거래소 KIND',
    url: 'https://kind.krx.co.kr/common/disclsviewer.do?acptno=20260323001354&docno=&method=search&viewerhost=',
  },
  {
    id: 'korea-customs-10167371',
    kind: 'government',
    title: '관세청 2026년 6월 1~20일 수출입 현황',
    publisher: '관세청',
    url: 'https://www.customs.go.kr/kcs/na/ntt/selectNttInfo.do?nttSn=10167371&nttSnUrl=d3dc345ca30751d2b28d06b45adfbc2b',
  },
  {
    id: 'news-nate-view-20260622n11074-0ec51351',
    kind: 'news',
    title: '제주반도체 반도체 수출 호조 보도',
    publisher: '이투데이',
    url: 'https://news.nate.com/view/20260622n11074?mid=n1101',
  },
  {
    id: 'yahoo-finance-chart-080220-kq',
    kind: 'market-data',
    title: 'Yahoo Finance 080220.KQ 공개 차트',
    publisher: 'Yahoo Finance',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/080220.KQ?range=5d&interval=1d',
  },
  {
    id: 'sec-gov-d99037dex991',
    kind: 'sec-filing',
    title: 'Huntsman·Olin 공동 합병 발표',
    publisher: 'Huntsman·Olin',
    url: 'https://www.sec.gov/Archives/edgar/data/74303/000119312526271782/d99037dex991.htm',
  },
  {
    id: 'sec-gov-tm2618028d1-8k',
    kind: 'sec-filing',
    title: 'Huntsman 합병계약 8-K',
    publisher: 'SEC · Huntsman',
    url: 'https://www.sec.gov/Archives/edgar/data/1307954/000110465926074683/tm2618028d1_8k.htm',
  },
  {
    id: 'sec-gov-d99037d8k',
    kind: 'sec-filing',
    title: 'Olin 공동 발표 8-K',
    publisher: 'SEC · Olin',
    url: 'https://www.sec.gov/Archives/edgar/data/74303/000119312526271782/d99037d8k.htm',
  },
  {
    id: 'nasdaq-historical-hun',
    kind: 'market-data',
    title: 'Huntsman 공개 과거 시세',
    publisher: 'Nasdaq · HUN',
    url: 'https://www.nasdaq.com/market-activity/stocks/hun/historical',
  },
  {
    id: 'nasdaq-historical-oln',
    kind: 'market-data',
    title: 'Olin 공개 과거 시세',
    publisher: 'Nasdaq · OLN',
    url: 'https://www.nasdaq.com/market-activity/stocks/oln/historical',
  },
  {
    id: 'uniqure-gcs-web-news-releases-news-release-details-uniqure-announces-pla-3cbaedf7',
    kind: 'company-release',
    title: 'uniQure AMT-130 BLA 계획 발표',
    publisher: 'uniQure',
    url: 'https://uniqure.gcs-web.com/news-releases/news-release-details/uniqure-announces-plan-bla-submission-amt-130-huntingtons',
  },
  {
    id: 'sec-gov-tm2618105d1-8k',
    kind: 'sec-filing',
    title: 'uniQure AMT-130 FDA 8-K',
    publisher: 'SEC · uniQure',
    url: 'https://www.sec.gov/Archives/edgar/data/1590560/000110465926074853/tm2618105d1_8k.htm',
  },
  {
    id: 'fda-gov-drugs-nda-and-bla-approvals-accelerated-approval-program-1610dedc',
    kind: 'government',
    title: 'FDA 가속승인 프로그램 안내',
    publisher: 'FDA',
    url: 'https://www.fda.gov/drugs/nda-and-bla-approvals/accelerated-approval-program',
  },
  {
    id: 'nasdaq-historical-qure',
    kind: 'market-data',
    title: 'uniQure 공개 과거 시세',
    publisher: 'Nasdaq · QURE',
    url: 'https://www.nasdaq.com/market-activity/stocks/qure/historical',
  },
  {
    id: 'marvell-company-newsroom-nvidia-ai-ecosystem-expands-marvell-joins-force-8761be8f',
    kind: 'company-release',
    title: 'Marvell·NVIDIA NVLink Fusion 발표',
    publisher: 'Marvell',
    url: 'https://www.marvell.com/company/newsroom/nvidia-ai-ecosystem-expands-marvell-joins-forces-through-nvlink-fusion.html',
  },
  {
    id: 'investor-nvidia-2025-nvidia-unveils-nvlink-fusion-for-industry-to-build-cc4f6311',
    kind: 'company-release',
    title: 'NVIDIA NVLink Fusion 발표',
    publisher: 'NVIDIA',
    url: 'https://investor.nvidia.com/news/press-release-details/2025/NVIDIA-Unveils-NVLink-Fusion-for-Industry-to-Build-Semi-Custom-AI-Infrastructure-With-NVIDIA-Partner-Ecosystem/default.aspx',
  },
  {
    id: 'lge-story-newsroom-235685-63746d17',
    kind: 'company-release',
    title: 'LG전자 완주 AI 데이터센터 HVAC 협약',
    publisher: 'LG전자',
    url: 'https://www.lge.co.kr/story/newsroom/235685',
  },
  {
    id: 'lg-news-eco-solution-lg-electronics-showcases-ai-data-center-cooling-sol-6f61b0d8',
    kind: 'company-release',
    title: 'LG AI 데이터센터 냉각 솔루션',
    publisher: 'LG전자',
    url: 'https://www.lg.com/global/newsroom/news/eco-solution/lg-electronics-showcases-ai-data-center-cooling-solutions-at-data-center-world-2026/',
  },
  {
    id: 's27-q4cdn-files-doc-news-berkshire-hathaway-to-acquire-taylor-morrison-h-db75cd29',
    kind: 'company-release',
    title: 'Taylor Morrison·Berkshire 인수 발표',
    publisher: 'Taylor Morrison·Berkshire',
    url: 'https://s27.q4cdn.com/448041563/files/doc_news/Berkshire-Hathaway-to-Acquire-Taylor-Morrison-Home-Corporation-for-8-5-Billion-2026.pdf',
  },
  {
    id: 'ir-supermicro-2026-supermicro-announces-proposed-7-0-billion-of-equity-a-98aa69c1',
    kind: 'company-ir',
    title: 'Supermicro 자금조달 발표',
    publisher: 'Super Micro Computer',
    url: 'https://ir.supermicro.com/news/news-details/2026/Supermicro-Announces-Proposed-7-0-Billion-of-Equity-and-Equity-linked-Financing-Transactions-To-Fund-AI-Orders/default.aspx',
  },
  {
    id: 'ir-supermicro-2026-supermicro-announces-pricing-of-equity-and-equity-lin-f33c9243',
    kind: 'company-ir',
    title: 'Supermicro 자금조달 가격 확정',
    publisher: 'Super Micro Computer',
    url: 'https://ir.supermicro.com/news/news-details/2026/Supermicro-Announces-Pricing-of-Equity-and-Equity-Linked-Financing-Transactions-To-Fund-AI-Orders/default.aspx',
  },
  {
    id: 'yna-view-akr20260612043100008-e17a6a9a',
    kind: 'news',
    title: '연합뉴스 재건주 급등 보도',
    publisher: '연합뉴스',
    url: 'https://www.yna.co.kr/view/AKR20260612043100008',
  },
  {
    id: 'hdec-en-main-aspx-2852b1b1',
    kind: 'company-release',
    title: '현대건설 회사 소개',
    publisher: '현대건설',
    url: 'https://www.hdec.kr/en/main.aspx',
  },
  {
    id: 'sec-gov-tm2617134d1-8k',
    kind: 'sec-filing',
    title: 'DraftKings SEC 8-K',
    publisher: 'SEC',
    url: 'https://www.sec.gov/Archives/edgar/data/1883685/000110465926071581/tm2617134d1_8k.htm',
  },
  {
    id: 'barrons-articles-draftkings-stock-prediction-market-trading-volume-e9754-b1aa57a6',
    kind: 'news',
    title: 'Barron’s DraftKings 예측시장 보도',
    publisher: 'Barron\'s',
    url: 'https://www.barrons.com/articles/draftkings-stock-prediction-market-trading-volume-e9754687',
  },
  {
    id: 'investors-micron-news-releases-news-release-details-micron-technology-in-b6ad01c4',
    kind: 'company-ir',
    title: 'Micron FY26 2Q 실적 발표',
    publisher: 'Micron',
    url: 'https://investors.micron.com/news-releases/news-release-details/micron-technology-inc-reports-results-second-quarter-fiscal-2026',
  },
  {
    id: 'marketwatch-story-microns-stock-bounces-back-in-a-big-way-the-memory-tra-d51e564f',
    kind: 'news',
    title: 'MarketWatch 메모리주 반등 보도',
    publisher: 'MarketWatch',
    url: 'https://www.marketwatch.com/story/microns-stock-bounces-back-in-a-big-way-the-memory-trade-is-alive-and-well-3466929f',
    accessType: 'restricted',
  },
  {
    id: 'snowflake-fy2026-q1-results',
    kind: 'company-release',
    title: 'Snowflake Reports Financial Results for the First Quarter of Fiscal 2026',
    publisher: 'Snowflake',
    url: 'https://www.snowflake.com/en/news/press-releases/snowflake-reports-financial-results-for-the-first-quarter-of-fiscal-2026/',
  },
  {
    id: 'dell-technologies-delivers-fourth-quarter-and-full-year-fiscal-2026-results',
    kind: 'company-release',
    title: 'Dell 공식 FY26 실적 발표',
    publisher: 'Dell Technologies',
    url: 'https://www.dell.com/en-us/dt/corporate/newsroom/announcements/detailpage.press-releases~usa~2026~2~dell-technologies-delivers-fourth-quarter-and-full-year-fiscal-2026-results.htm',
  },
  {
    id: 'sec-gov-dell-20260130',
    kind: 'sec-filing',
    title: 'SEC 10-K 원문',
    publisher: 'SEC',
    url: 'https://www.sec.gov/Archives/edgar/data/1571996/000157199626000008/dell-20260130.htm',
  },
  {
    id: 'dart-fss-20260515001572',
    kind: 'dart-filing',
    title: 'DART 원문 보고서',
    publisher: 'DART',
    url: 'https://dart.fss.or.kr/dsaf001/main.do?rcpNo=20260515001572',
  },
  {
    id: 'dart-fss-20260515002287',
    kind: 'dart-filing',
    title: 'DART 원문 보고서',
    publisher: 'DART',
    url: 'https://dart.fss.or.kr/dsaf001/main.do?rcpNo=20260515002287',
  },
  {
    id: 'kind-krx-20260515002501',
    kind: 'kind-filing',
    title: 'SK하이닉스 2026년 1분기 분기보고서',
    publisher: '한국거래소 KIND',
    url: 'https://kind.krx.co.kr/common/disclsviewer.do?acptno=20260515002501&docno=&method=search&viewerhost=',
    publishedAt: '2026-05-15',
  },
  {
    id: 'yonhap-daum-20260702163503246',
    kind: 'news',
    title: '연합뉴스 삼성전자·SK하이닉스 급락 보도',
    publisher: '연합뉴스',
    url: 'https://v.daum.net/v/20260702163503246',
    publishedAt: '2026-07-02',
  },
  {
    id: 'wsj-meta-cloud-ai-compute-20260701',
    kind: 'news',
    title: 'WSJ Meta AI 컴퓨팅 클라우드 보도',
    publisher: 'The Wall Street Journal',
    url: 'https://www.wsj.com/livecoverage/stock-market-today-dow-sp-500-nasdaq-07-01-2026/card/lusNzm2pjxU216rg4mIA',
    publishedAt: '2026-07-01',
    accessType: 'restricted',
  },
  {
    id: 'meta-q1-2026-results',
    kind: 'company-release',
    title: 'Meta Reports First Quarter 2026 Results',
    publisher: 'Meta Platforms',
    url: 'https://investor.atmeta.com/investor-news/press-release-details/2026/Meta-Reports-First-Quarter-2026-Results/default.aspx',
    publishedAt: '2026-04-29',
  },
  {
    id: 'yahoo-finance-chart-meta',
    kind: 'market-data',
    title: 'Yahoo Finance META 공개 차트',
    publisher: 'Yahoo Finance',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/META?range=5d&interval=1d',
  },
  {
    id: 'yahoo-finance-chart-000660-ks',
    kind: 'market-data',
    title: 'Yahoo Finance 000660.KS 공개 차트',
    publisher: 'Yahoo Finance',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/000660.KS?range=5d&interval=1d',
  },
  {
    id: 'kind-krx-20260323000305',
    kind: 'kind-filing',
    title: '에스폴리텍 2025 사업보고서',
    publisher: '한국거래소 KIND',
    url: 'https://kind.krx.co.kr/common/disclsviewer.do?acptno=20260323000305&docno=&method=search&viewerhost=',
    publishedAt: '2026-03-23',
  },
  {
    id: 'newsis-daum-20260630095203161',
    kind: 'news',
    title: '뉴시스 에스폴리텍 AI 데이터센터용 폴리카보네이트 양산 보도',
    publisher: '뉴시스',
    url: 'https://v.daum.net/v/20260630095203161',
    publishedAt: '2026-06-30',
  },
  {
    id: 'mk-market-050760-kq',
    kind: 'market-data',
    title: '매일경제 에스폴리텍 공개 시세',
    publisher: '매일경제',
    url: 'https://stock.mk.co.kr/price/chart/KR7050760008?type=weekly',
  },
  {
    id: 'yahoo-finance-chart-050760-kq',
    kind: 'market-data',
    title: 'Yahoo Finance 050760.KQ 공개 차트',
    publisher: 'Yahoo Finance',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/050760.KQ?range=5d&interval=1d',
  },
  {
    id: 'kind-krx-20260515000416',
    kind: 'kind-filing',
    title: '금호건설 2026년 1분기 분기보고서',
    publisher: '한국거래소 KIND',
    url: 'https://kind.krx.co.kr/common/disclsviewer.do?acptno=20260515000416&docno=&method=search&viewerhost=',
    publishedAt: '2026-05-15',
  },
  {
    id: 'edaily-daum-20260701092752533',
    kind: 'news',
    title: '이데일리 금호건설 호남 반도체 클러스터 관련 보도',
    publisher: '이데일리',
    url: 'https://v.daum.net/v/20260701092752533',
    publishedAt: '2026-07-01',
  },
  {
    id: 'kind-krx-20260630001269',
    kind: 'kind-filing',
    title: '금호건설 투자경고종목 지정',
    publisher: '한국거래소 KIND',
    url: 'https://kind.krx.co.kr/common/disclsviewer.do?acptno=20260630001269&method=search',
    publishedAt: '2026-06-30',
  },
  {
    id: 'kind-krx-20260702000936',
    kind: 'kind-filing',
    title: '금호건설 단기 과열 거래 제한 지정',
    publisher: '한국거래소 KIND',
    url: 'https://kind.krx.co.kr/common/disclsviewer.do?acptno=20260702000936&method=search',
    publishedAt: '2026-07-02',
  },
  {
    id: 'yahoo-finance-chart-002990-ks',
    kind: 'market-data',
    title: 'Yahoo Finance 002990.KS 공개 차트',
    publisher: 'Yahoo Finance',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/002990.KS?range=5d&interval=1d',
  }
];
