import type { ContentSource } from './types.js';

export const contentSources: ContentSource[] = [
  {
    id: 'kind-krx-20260318002468',
    kind: 'kind-filing',
    title: '동양파일 2025 사업보고서',
    publisher: '한국거래소 KIND',
    url: 'https://kind.krx.co.kr/common/disclsviewer.do?acptno=20260318002468&langTpCd=0&method=search&orgid=F&rcpno=20260318001680&tran=Y',
  },
  {
    id: 'kind-krx-20260515000989',
    kind: 'kind-filing',
    title: '동양파일 2026년 1분기 분기보고서',
    publisher: '한국거래소 KIND',
    url: 'https://kind.krx.co.kr/common/disclsviewer.do?acptno=20260515000989&docno=&method=search&viewerhost=',
  },
  {
    id: 'v-daum-v-20260626094305527-19a14080',
    kind: 'news',
    title: 'SBS Biz 호남권 반도체 클러스터 관련주 시황',
    publisher: 'SBS Biz',
    url: 'https://v.daum.net/v/20260626094305527',
  },
  {
    id: 'yahoo-finance-chart-228340-kq',
    kind: 'market-data',
    title: 'Yahoo Finance 228340.KQ 공개 차트',
    publisher: 'Yahoo Finance',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/228340.KQ?range=5d&interval=1d',
  },
  {
    id: 'samsung-electronics-2026-q1-dart-report',
    kind: 'dart-filing',
    title: '삼성전자 2026년 1분기 분기보고서',
    publisher: 'DART',
    url: 'https://dart.fss.or.kr/dsaf001/main.do?rcpNo=20260515002181',
  },
  {
    id: 'samsung-electronics-earnings-releases',
    kind: 'company-ir',
    title: 'Samsung Electronics Earnings Releases',
    publisher: 'Samsung Electronics',
    url: 'https://www.samsung.com/global/ir/financial-information/earnings-release/',
  },
  {
    id: 'dell-technologies-fy2026-q1-results',
    kind: 'company-release',
    title: 'Dell Technologies Delivers First Quarter Fiscal 2026 Financial Results',
    publisher: 'Dell Technologies',
    url: 'https://www.dell.com/en-us/dt/corporate/newsroom/announcements/detailpage.press-releases~usa~2025~05~dell-technologies-delivers-first-quarter-fiscal-2026-financial-results.htm',
    publishedAt: '2025-05-29',
  },
  {
    id: 'sec-gov-nvda-20260125',
    kind: 'sec-filing',
    title: 'SEC 원문 보고서',
    publisher: 'SEC',
    url: 'https://www.sec.gov/Archives/edgar/data/1045810/000104581026000021/nvda-20260125.htm',
  },
  {
    id: 'posco-future-m-ir-reference',
    kind: 'company-ir',
    title: '포스코퓨처엠 IR 자료실',
    publisher: 'POSCO Future M',
    url: 'https://www.poscofuturem.com/ir/reference.do',
  },
  {
    id: 'iea-global-ev-outlook-2025',
    kind: 'industry-data',
    title: 'Global EV Outlook 2025',
    publisher: 'IEA',
    url: 'https://www.iea.org/reports/global-ev-outlook-2025',
  },
  {
    id: 'kind-krx-20260515001457',
    kind: 'kind-filing',
    title: 'KCC 2026년 1분기 분기보고서',
    publisher: '한국거래소 KIND',
    url: 'https://kind.krx.co.kr/common/disclsviewer.do?acptno=20260515001457&docno=&method=search&viewerhost=',
  },
  {
    id: 'stock-mk-news-view-1110153-99ac0782',
    kind: 'news',
    title: '매일경제 KCC 실적·자산가치 보도',
    publisher: '매일경제',
    url: 'https://stock.mk.co.kr/news/view/1110153',
  },
  {
    id: 'mt-06-25-2026062508592086578-81e25849',
    kind: 'news',
    title: '머니투데이 KCC 실리콘·도료 전망 보도',
    publisher: '머니투데이',
    url: 'https://www.mt.co.kr/amp/stock/2026/06/25/2026062508592086578',
  },
  {
    id: 'yahoo-finance-chart-002380-ks',
    kind: 'market-data',
    title: 'Yahoo Finance 002380.KS 공개 차트',
    publisher: 'Yahoo Finance',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/002380.KS?range=5d&interval=1d',
  },
  {
    id: 'newsroom-hertz-press-releases-press-release-details-hertz-announces-prop-379e936c',
    kind: 'company-release',
    title: 'Hertz 3억 달러 PIK 채권 제안 발표',
    publisher: 'Hertz',
    url: 'https://newsroom.hertz.com/press-releases/press-release-details/hertz-announces-proposed-offering-of-300-million-of-exchangeable-senior-first-lien-secured-pik-notes/',
  },
  {
    id: 'newsroom-hertz-press-releases-press-release-details-hertz-announces-pric-95a9f82b',
    kind: 'company-release',
    title: 'Hertz 3억5천만 달러 PIK 채권 가격 확정',
    publisher: 'Hertz',
    url: 'https://newsroom.hertz.com/press-releases/press-release-details/hertz-announces-pricing-of-upsized-350-million-of-exchangeable-senior-first-lien-secured-pik-notes/',
  },
  {
    id: 'newsroom-hertz-press-releases-press-release-details-hertz-announces-pric-89198328',
    kind: 'company-release',
    title: 'Hertz 보통주 37,037,037주 가격 확정',
    publisher: 'Hertz',
    url: 'https://newsroom.hertz.com/press-releases/press-release-details/hertz-announces-pricing-of-offering-of-37037037-shares-of-common-stock/',
  },
  {
    id: 'sec-gov-tm2618542-1-s3asr',
    kind: 'sec-filing',
    title: 'SEC Hertz 보통주 공모 설명서',
    publisher: 'SEC',
    url: 'https://www.sec.gov/Archives/edgar/data/0001657853/000110465926077051/tm2618542-1_s3asr.htm',
  },
  {
    id: 'sec-gov-htzz-20260331',
    kind: 'sec-filing',
    title: 'Hertz 2026년 1분기 10-Q',
    publisher: 'SEC',
    url: 'https://www.sec.gov/Archives/edgar/data/1657853/000165785326000024/htzz-20260331.htm',
  },
  {
    id: 'yahoo-finance-chart-htz',
    kind: 'market-data',
    title: 'Yahoo Finance HTZ 공개 차트',
    publisher: 'Yahoo Finance',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/HTZ?range=5d&interval=1d',
  },
  {
    id: 'kind-krx-20260323001354',
    kind: 'kind-filing',
    title: '제주반도체 2025 사업보고서',
    publisher: '한국거래소 KIND',
    url: 'https://kind.krx.co.kr/common/disclsviewer.do?acptno=20260323001354&docno=&method=search&viewerhost=',
  },
  {
    id: 'kind-krx-20260515001553',
    kind: 'kind-filing',
    title: '어보브반도체 2026년 1분기 보고서',
    publisher: '한국거래소 KIND',
    url: 'https://kind.krx.co.kr/external/2026/05/15/000726/20260515001553/11013.htm',
    publishedAt: '2026-05-15',
  },
  {
    id: 'kind-krx-20260310002441',
    kind: 'kind-filing',
    title: '넥스트칩 2025 사업보고서',
    publisher: '한국거래소 KIND',
    url: 'https://kind.krx.co.kr/external/2026/03/10/001047/20260310002441/00591.htm',
    publishedAt: '2026-03-10',
  },
  {
    id: 'korea-customs-10167371',
    kind: 'government',
    title: '관세청 2026년 6월 1~20일 수출입 현황',
    publisher: '관세청',
    url: 'https://www.customs.go.kr/kcs/na/ntt/selectNttInfo.do?nttSn=10167371&nttSnUrl=d3dc345ca30751d2b28d06b45adfbc2b',
  },
  {
    id: 'news-nate-view-20260622n11074-0ec51351',
    kind: 'news',
    title: '제주반도체 반도체 수출 호조 보도',
    publisher: '이투데이',
    url: 'https://news.nate.com/view/20260622n11074?mid=n1101',
  },
  {
    id: 'yahoo-finance-chart-080220-kq',
    kind: 'market-data',
    title: 'Yahoo Finance 080220.KQ 공개 차트',
    publisher: 'Yahoo Finance',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/080220.KQ?range=5d&interval=1d',
  },
  {
    id: 'sec-gov-d99037dex991',
    kind: 'sec-filing',
    title: 'Huntsman·Olin 공동 합병 발표',
    publisher: 'Huntsman·Olin',
    url: 'https://www.sec.gov/Archives/edgar/data/74303/000119312526271782/d99037dex991.htm',
  },
  {
    id: 'sec-gov-tm2618028d1-8k',
    kind: 'sec-filing',
    title: 'Huntsman 합병계약 8-K',
    publisher: 'SEC · Huntsman',
    url: 'https://www.sec.gov/Archives/edgar/data/1307954/000110465926074683/tm2618028d1_8k.htm',
  },
  {
    id: 'sec-gov-d99037d8k',
    kind: 'sec-filing',
    title: 'Olin 공동 발표 8-K',
    publisher: 'SEC · Olin',
    url: 'https://www.sec.gov/Archives/edgar/data/74303/000119312526271782/d99037d8k.htm',
  },
  {
    id: 'nasdaq-historical-hun',
    kind: 'market-data',
    title: 'Huntsman 공개 과거 시세',
    publisher: 'Nasdaq · HUN',
    url: 'https://www.nasdaq.com/market-activity/stocks/hun/historical',
  },
  {
    id: 'nasdaq-historical-oln',
    kind: 'market-data',
    title: 'Olin 공개 과거 시세',
    publisher: 'Nasdaq · OLN',
    url: 'https://www.nasdaq.com/market-activity/stocks/oln/historical',
  },
  {
    id: 'uniqure-gcs-web-news-releases-news-release-details-uniqure-announces-pla-3cbaedf7',
    kind: 'company-release',
    title: 'uniQure AMT-130 BLA 계획 발표',
    publisher: 'uniQure',
    url: 'https://uniqure.gcs-web.com/news-releases/news-release-details/uniqure-announces-plan-bla-submission-amt-130-huntingtons',
  },
  {
    id: 'sec-gov-tm2618105d1-8k',
    kind: 'sec-filing',
    title: 'uniQure AMT-130 FDA 8-K',
    publisher: 'SEC · uniQure',
    url: 'https://www.sec.gov/Archives/edgar/data/1590560/000110465926074853/tm2618105d1_8k.htm',
  },
  {
    id: 'fda-gov-drugs-nda-and-bla-approvals-accelerated-approval-program-1610dedc',
    kind: 'government',
    title: 'FDA 가속승인 프로그램 안내',
    publisher: 'FDA',
    url: 'https://www.fda.gov/drugs/nda-and-bla-approvals/accelerated-approval-program',
  },
  {
    id: 'nasdaq-historical-qure',
    kind: 'market-data',
    title: 'uniQure 공개 과거 시세',
    publisher: 'Nasdaq · QURE',
    url: 'https://www.nasdaq.com/market-activity/stocks/qure/historical',
  },
  {
    id: 'marvell-company-newsroom-nvidia-ai-ecosystem-expands-marvell-joins-force-8761be8f',
    kind: 'company-release',
    title: 'Marvell·NVIDIA NVLink Fusion 발표',
    publisher: 'Marvell',
    url: 'https://www.marvell.com/company/newsroom/nvidia-ai-ecosystem-expands-marvell-joins-forces-through-nvlink-fusion.html',
  },
  {
    id: 'investor-nvidia-2025-nvidia-unveils-nvlink-fusion-for-industry-to-build-cc4f6311',
    kind: 'company-release',
    title: 'NVIDIA NVLink Fusion 발표',
    publisher: 'NVIDIA',
    url: 'https://investor.nvidia.com/news/press-release-details/2025/NVIDIA-Unveils-NVLink-Fusion-for-Industry-to-Build-Semi-Custom-AI-Infrastructure-With-NVIDIA-Partner-Ecosystem/default.aspx',
  },
  {
    id: 'lge-story-newsroom-235685-63746d17',
    kind: 'company-release',
    title: 'LG전자 완주 AI 데이터센터 HVAC 협약',
    publisher: 'LG전자',
    url: 'https://www.lge.co.kr/story/newsroom/235685',
  },
  {
    id: 'lg-news-eco-solution-lg-electronics-showcases-ai-data-center-cooling-sol-6f61b0d8',
    kind: 'company-release',
    title: 'LG AI 데이터센터 냉각 솔루션',
    publisher: 'LG전자',
    url: 'https://www.lg.com/global/newsroom/news/eco-solution/lg-electronics-showcases-ai-data-center-cooling-solutions-at-data-center-world-2026/',
  },
  {
    id: 's27-q4cdn-files-doc-news-berkshire-hathaway-to-acquire-taylor-morrison-h-db75cd29',
    kind: 'company-release',
    title: 'Taylor Morrison·Berkshire 인수 발표',
    publisher: 'Taylor Morrison·Berkshire',
    url: 'https://s27.q4cdn.com/448041563/files/doc_news/Berkshire-Hathaway-to-Acquire-Taylor-Morrison-Home-Corporation-for-8-5-Billion-2026.pdf',
  },
  {
    id: 'ir-supermicro-2026-supermicro-announces-proposed-7-0-billion-of-equity-a-98aa69c1',
    kind: 'company-ir',
    title: 'Supermicro 자금조달 발표',
    publisher: 'Super Micro Computer',
    url: 'https://ir.supermicro.com/news/news-details/2026/Supermicro-Announces-Proposed-7-0-Billion-of-Equity-and-Equity-linked-Financing-Transactions-To-Fund-AI-Orders/default.aspx',
  },
  {
    id: 'ir-supermicro-2026-supermicro-announces-pricing-of-equity-and-equity-lin-f33c9243',
    kind: 'company-ir',
    title: 'Supermicro 자금조달 가격 확정',
    publisher: 'Super Micro Computer',
    url: 'https://ir.supermicro.com/news/news-details/2026/Supermicro-Announces-Pricing-of-Equity-and-Equity-Linked-Financing-Transactions-To-Fund-AI-Orders/default.aspx',
  },
  {
    id: 'yna-view-akr20260612043100008-e17a6a9a',
    kind: 'news',
    title: '연합뉴스 재건주 급등 보도',
    publisher: '연합뉴스',
    url: 'https://www.yna.co.kr/view/AKR20260612043100008',
  },
  {
    id: 'hdec-en-main-aspx-2852b1b1',
    kind: 'company-release',
    title: '현대건설 회사 소개',
    publisher: '현대건설',
    url: 'https://www.hdec.kr/en/main.aspx',
  },
  {
    id: 'sec-gov-tm2617134d1-8k',
    kind: 'sec-filing',
    title: 'DraftKings SEC 8-K',
    publisher: 'SEC',
    url: 'https://www.sec.gov/Archives/edgar/data/1883685/000110465926071581/tm2617134d1_8k.htm',
  },
  {
    id: 'barrons-articles-draftkings-stock-prediction-market-trading-volume-e9754-b1aa57a6',
    kind: 'news',
    title: 'Barron’s DraftKings 예측시장 보도',
    publisher: 'Barron\'s',
    url: 'https://www.barrons.com/articles/draftkings-stock-prediction-market-trading-volume-e9754687',
  },
  {
    id: 'investors-micron-news-releases-news-release-details-micron-technology-in-b6ad01c4',
    kind: 'company-ir',
    title: 'Micron FY26 2Q 실적 발표',
    publisher: 'Micron',
    url: 'https://investors.micron.com/news-releases/news-release-details/micron-technology-inc-reports-results-second-quarter-fiscal-2026',
  },
  {
    id: 'marketwatch-story-microns-stock-bounces-back-in-a-big-way-the-memory-tra-d51e564f',
    kind: 'news',
    title: 'MarketWatch 메모리주 반등 보도',
    publisher: 'MarketWatch',
    url: 'https://www.marketwatch.com/story/microns-stock-bounces-back-in-a-big-way-the-memory-trade-is-alive-and-well-3466929f',
    accessType: 'restricted',
  },
  {
    id: 'snowflake-fy2026-q1-results',
    kind: 'company-release',
    title: 'Snowflake Reports Financial Results for the First Quarter of Fiscal 2026',
    publisher: 'Snowflake',
    url: 'https://www.snowflake.com/en/news/press-releases/snowflake-reports-financial-results-for-the-first-quarter-of-fiscal-2026/',
  },
  {
    id: 'dell-technologies-delivers-fourth-quarter-and-full-year-fiscal-2026-results',
    kind: 'company-release',
    title: 'Dell 공식 FY26 실적 발표',
    publisher: 'Dell Technologies',
    url: 'https://www.dell.com/en-us/dt/corporate/newsroom/announcements/detailpage.press-releases~usa~2026~2~dell-technologies-delivers-fourth-quarter-and-full-year-fiscal-2026-results.htm',
  },
  {
    id: 'sec-gov-dell-20260130',
    kind: 'sec-filing',
    title: 'SEC 10-K 원문',
    publisher: 'SEC',
    url: 'https://www.sec.gov/Archives/edgar/data/1571996/000157199626000008/dell-20260130.htm',
  },
  {
    id: 'dart-fss-20260515001572',
    kind: 'dart-filing',
    title: 'DART 원문 보고서',
    publisher: 'DART',
    url: 'https://dart.fss.or.kr/dsaf001/main.do?rcpNo=20260515001572',
  },
  {
    id: 'dart-fss-20260515002287',
    kind: 'dart-filing',
    title: 'DART 원문 보고서',
    publisher: 'DART',
    url: 'https://dart.fss.or.kr/dsaf001/main.do?rcpNo=20260515002287',
  },
  {
    id: 'kind-krx-20260515002501',
    kind: 'kind-filing',
    title: 'SK하이닉스 2026년 1분기 분기보고서',
    publisher: '한국거래소 KIND',
    url: 'https://kind.krx.co.kr/common/disclsviewer.do?acptno=20260515002501&docno=&method=search&viewerhost=',
    publishedAt: '2026-05-15',
  },
  {
    id: 'yonhap-daum-20260702163503246',
    kind: 'news',
    title: '연합뉴스 삼성전자·SK하이닉스 급락 보도',
    publisher: '연합뉴스',
    url: 'https://v.daum.net/v/20260702163503246',
    publishedAt: '2026-07-02',
  },
  {
    id: 'wsj-meta-cloud-ai-compute-20260701',
    kind: 'news',
    title: 'WSJ Meta AI 컴퓨팅 클라우드 보도',
    publisher: 'The Wall Street Journal',
    url: 'https://www.wsj.com/livecoverage/stock-market-today-dow-sp-500-nasdaq-07-01-2026/card/lusNzm2pjxU216rg4mIA',
    publishedAt: '2026-07-01',
    accessType: 'restricted',
  },
  {
    id: 'meta-q1-2026-results',
    kind: 'company-release',
    title: 'Meta Reports First Quarter 2026 Results',
    publisher: 'Meta Platforms',
    url: 'https://investor.atmeta.com/investor-news/press-release-details/2026/Meta-Reports-First-Quarter-2026-Results/default.aspx',
    publishedAt: '2026-04-29',
  },
  {
    id: 'yahoo-finance-chart-meta',
    kind: 'market-data',
    title: 'Yahoo Finance META 공개 차트',
    publisher: 'Yahoo Finance',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/META?range=5d&interval=1d',
  },
  {
    id: 'yahoo-finance-chart-000660-ks',
    kind: 'market-data',
    title: 'Yahoo Finance 000660.KS 공개 차트',
    publisher: 'Yahoo Finance',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/000660.KS?range=5d&interval=1d',
  },
  {
    id: 'kind-krx-20260323000305',
    kind: 'kind-filing',
    title: '에스폴리텍 2025 사업보고서',
    publisher: '한국거래소 KIND',
    url: 'https://kind.krx.co.kr/common/disclsviewer.do?acptno=20260323000305&docno=&method=search&viewerhost=',
    publishedAt: '2026-03-23',
  },
  {
    id: 'newsis-daum-20260630095203161',
    kind: 'news',
    title: '뉴시스 에스폴리텍 AI 데이터센터용 폴리카보네이트 양산 보도',
    publisher: '뉴시스',
    url: 'https://v.daum.net/v/20260630095203161',
    publishedAt: '2026-06-30',
  },
  {
    id: 'mk-market-050760-kq',
    kind: 'market-data',
    title: '매일경제 에스폴리텍 공개 시세',
    publisher: '매일경제',
    url: 'https://stock.mk.co.kr/price/chart/KR7050760008?type=weekly',
  },
  {
    id: 'yahoo-finance-chart-050760-kq',
    kind: 'market-data',
    title: 'Yahoo Finance 050760.KQ 공개 차트',
    publisher: 'Yahoo Finance',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/050760.KQ?range=5d&interval=1d',
  },
  {
    id: 'kind-krx-20260515000416',
    kind: 'kind-filing',
    title: '금호건설 2026년 1분기 분기보고서',
    publisher: '한국거래소 KIND',
    url: 'https://kind.krx.co.kr/common/disclsviewer.do?acptno=20260515000416&docno=&method=search&viewerhost=',
    publishedAt: '2026-05-15',
  },
  {
    id: 'edaily-daum-20260701092752533',
    kind: 'news',
    title: '이데일리 금호건설 호남 반도체 클러스터 관련 보도',
    publisher: '이데일리',
    url: 'https://v.daum.net/v/20260701092752533',
    publishedAt: '2026-07-01',
  },
  {
    id: 'kind-krx-20260630001269',
    kind: 'kind-filing',
    title: '금호건설 투자경고종목 지정',
    publisher: '한국거래소 KIND',
    url: 'https://kind.krx.co.kr/common/disclsviewer.do?acptno=20260630001269&method=search',
    publishedAt: '2026-06-30',
  },
  {
    id: 'kind-krx-20260702000936',
    kind: 'kind-filing',
    title: '금호건설 단기 과열 거래 제한 지정',
    publisher: '한국거래소 KIND',
    url: 'https://kind.krx.co.kr/common/disclsviewer.do?acptno=20260702000936&method=search',
    publishedAt: '2026-07-02',
  },
  {
    id: 'yahoo-finance-chart-002990-ks',
    kind: 'market-data',
    title: 'Yahoo Finance 002990.KS 공개 차트',
    publisher: 'Yahoo Finance',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/002990.KS?range=5d&interval=1d',
  },
  {
    id: 'korea-market-close-20260710',
    kind: 'news',
    title: '코스피·코스닥 7월 10일 강세 마감',
    publisher: '시대',
    url: 'https://v.daum.net/v/20260710155609669',
    publishedAt: '2026-07-10',
  },
  {
    id: 'yonhap-korea-market-20260710',
    kind: 'news',
    title: '코스피·코스닥 장중 반등과 수급 흐름',
    publisher: '연합뉴스',
    url: 'https://www.yna.co.kr/view/AKR20260710071300008',
    publishedAt: '2026-07-10',
  },
  {
    id: 'ap-us-market-20260710',
    kind: 'news',
    title: 'US stocks rise as Wall Street shows it is still hungry for AI winners',
    publisher: 'Associated Press',
    url: 'https://apnews.com/article/stocks-market-iran-war-ai-oil-45e2da56e466900ff8def70ab931387d',
    publishedAt: '2026-07-10',
  },
  {
    id: 'yahoo-finance-chart-ks11',
    kind: 'market-data',
    title: 'Yahoo Finance KOSPI 공개 차트',
    publisher: 'Yahoo Finance',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/%5EKS11?range=5d&interval=1d',
  },
  {
    id: 'yahoo-finance-chart-kq11',
    kind: 'market-data',
    title: 'Yahoo Finance KOSDAQ 공개 차트',
    publisher: 'Yahoo Finance',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/%5EKQ11?range=5d&interval=1d',
  },
  {
    id: 'yahoo-finance-chart-gspc',
    kind: 'market-data',
    title: 'Yahoo Finance S&P 500 공개 차트',
    publisher: 'Yahoo Finance',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/%5EGSPC?range=5d&interval=1d',
  },
  {
    id: 'yahoo-finance-chart-ixic',
    kind: 'market-data',
    title: 'Yahoo Finance Nasdaq Composite 공개 차트',
    publisher: 'Yahoo Finance',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/%5EIXIC?range=5d&interval=1d',
  },
  {
    id: 'yahoo-finance-chart-krw-x',
    kind: 'market-data',
    title: 'Yahoo Finance USD/KRW 공개 차트',
    publisher: 'Yahoo Finance',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/KRW%3DX?range=5d&interval=1d',
  },
  {
    id: 'yahoo-finance-chart-tnx',
    kind: 'market-data',
    title: 'Yahoo Finance 미국 10년물 국채금리 공개 차트',
    publisher: 'Yahoo Finance',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/%5ETNX?range=5d&interval=1d',
  },
  {
    id: 'yahoo-finance-chart-gc-f',
    kind: 'market-data',
    title: 'Yahoo Finance Gold Futures 공개 차트',
    publisher: 'Yahoo Finance',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/GC%3DF?range=5d&interval=1d',
  },
  {
    id: 'yahoo-finance-chart-hg-f',
    kind: 'market-data',
    title: 'Yahoo Finance Copper Futures 공개 차트',
    publisher: 'Yahoo Finance',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/HG%3DF?range=5d&interval=1d',
  },
  {
    id: 'yahoo-finance-chart-cl-f',
    kind: 'market-data',
    title: 'Yahoo Finance WTI Futures 공개 차트',
    publisher: 'Yahoo Finance',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/CL%3DF?range=5d&interval=1d',
  },
  {
    id: 'iea-critical-minerals-grid-copper',
    kind: 'industry-data',
    title: 'Mineral requirements for clean energy transitions',
    publisher: 'International Energy Agency',
    url: 'https://www.iea.org/reports/the-role-of-critical-minerals-in-clean-energy-transitions/mineral-requirements-for-clean-energy-transitions',
  },
  {
    id: 'iea-electricity-2026',
    kind: 'industry-data',
    title: 'Electricity 2026',
    publisher: 'International Energy Agency',
    url: 'https://www.iea.org/reports/electricity-2026',
    publishedAt: '2026-02-06',
  },
  {
    id: 'cme-gold-contract-specs',
    kind: 'market-data',
    title: 'Gold Futures Contract Specifications',
    publisher: 'CME Group',
    url: 'https://www.cmegroup.com/markets/metals/precious/gold.contractSpecs.html',
  },
  {
    id: 'cme-copper-contract-specs',
    kind: 'market-data',
    title: 'Copper Futures Contract Specifications',
    publisher: 'CME Group',
    url: 'https://www.cmegroup.com/markets/metals/base/copper.contractSpecs.html',
  },
  {
    id: 'cme-wti-contract-specs',
    kind: 'market-data',
    title: 'WTI Crude Oil Futures Contract Specifications',
    publisher: 'CME Group',
    url: 'https://www.cmegroup.com/markets/energy/crude-oil/light-sweet-crude.contractSpecs.html',
  },
  {
    id: 'imf-weo-april-2026',
    kind: 'government',
    title: 'World Economic Outlook, April 2026: Global Economy in the Shadow of War',
    publisher: 'IMF',
    url: 'https://www.imf.org/en/publications/weo/issues/2026/04/14/world-economic-outlook-april-2026',
    publishedAt: '2026-04-14',
  },
  {
    id: 'world-bank-gep-june-2026',
    kind: 'government',
    title: 'Global Economic Prospects, June 2026',
    publisher: 'World Bank',
    url: 'https://thedocs.worldbank.org/en/doc/2b672b3b0415d6b66c45b66579db4ef5-0050012026/global-economic-prospects-june-2026',
    publishedAt: '2026-06-16',
  },
  {
    id: 'oecd-economic-outlook-june-2026',
    kind: 'government',
    title: 'OECD Economic Outlook, Volume 2026 Issue 1',
    publisher: 'OECD',
    url: 'https://www.oecd.org/en/publications/2026/06/oecd-economic-outlook-volume-2026-issue-1_8be0dba6/full-report/editorial-under-pressure_2fc7cf99.html',
    publishedAt: '2026-06-03',
  },
  {
    id: 'nvidia-fy2027-q1-results',
    kind: 'company-ir',
    title: 'NVIDIA Announces Financial Results for First Quarter Fiscal 2027',
    publisher: 'NVIDIA',
    url: 'https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-first-quarter-fiscal-2027',
    publishedAt: '2026-05-20',
  },
  {
    id: 'micron-fy2026-q3-results',
    kind: 'company-ir',
    title: 'Micron Technology Reports Results for the Third Quarter of Fiscal 2026',
    publisher: 'Micron Technology',
    url: 'https://investors.micron.com/news-releases/news-release-details/micron-technology-inc-reports-results-third-quarter',
    publishedAt: '2026-06-24',
  },
  {
    id: 'semi-memory-fab-outlook-q2-2026',
    kind: 'industry-data',
    title: 'SEMI Projects 300mm Memory Equipment Investment to Surpass $50 Billion in 2026',
    publisher: 'SEMI',
    url: 'https://www.semi.org/en/semi-press-release/semi-projects-300mm-memory-equipment-investment-to-surpass-50-billion-dollars-in-2026',
    publishedAt: '2026-06-29',
  },
  {
    id: 'iea-energy-and-ai-2025',
    kind: 'industry-data',
    title: 'Energy and AI',
    publisher: 'International Energy Agency',
    url: 'https://www.iea.org/reports/energy-and-ai/',
    publishedAt: '2025-04-10',
  },
  {
    id: 'eaton-q1-2026-results',
    kind: 'company-ir',
    title: 'Eaton Reports Record First Quarter 2026 Results',
    publisher: 'Eaton',
    url: 'https://www.eaton.com/us/en-us/company/news-insights/news-releases/2026/eaton-reports-record-first-quarter-2026-results.html',
    publishedAt: '2026-04-30',
  },
  {
    id: 'sk-hynix-q1-2026-results',
    kind: 'company-release',
    title: 'SK hynix Announces 1Q26 Financial Results',
    publisher: 'SK hynix',
    url: 'https://news.skhynix.com/q1-2026-business-results/',
    publishedAt: '2026-04-23',
  },
  {
    id: 'sk-hynix-hbm4-production-2025',
    kind: 'company-release',
    title: 'SK hynix Completes World’s First HBM4 Development and Readies Mass Production',
    publisher: 'SK hynix',
    url: 'https://news.skhynix.com/sk-hynix-completes-worlds-first-hbm4-development-and-readies-mass-production/',
    publishedAt: '2025-09-12',
  },
  {
    id: 'micron-virginia-expansion-2026',
    kind: 'company-ir',
    title: 'Micron Advances Made-in-America Memory With Manufacturing Expansion in Virginia',
    publisher: 'Micron Technology',
    url: 'https://investors.micron.com/news-releases/news-release-details/micron-advances-made-america-memory-manufacturing-expansion',
    publishedAt: '2026-05-22',
  },
  {
    id: 'dell-fy2027-q1-results',
    kind: 'company-release',
    title: 'Dell Technologies Delivers First Quarter Fiscal 2027 Financial Results',
    publisher: 'Dell Technologies',
    url: 'https://www.dell.com/en-us/dt/corporate/newsroom/announcements/detailpage.press-releases~usa~2026~05~dell-technologies-delivers-first-quarter-fiscal-2027-financial-results.htm',
    publishedAt: '2026-05-28',
  },
  {
    id: 'meta-2025-senior-notes-8k',
    kind: 'sec-filing',
    title: 'Meta Platforms 8-K: Senior Notes Offering Completed',
    publisher: 'SEC',
    url: 'https://www.sec.gov/Archives/edgar/data/1326801/000119312525262593/d75422d8k.htm',
    publishedAt: '2025-11-03',
  },
  {
    id: 'netflix-q2-2026-8k',
    kind: 'sec-filing',
    title: 'Current Report on Form 8-K · Q2 2026 results',
    publisher: 'Netflix, Inc. · U.S. SEC',
    url: 'https://www.sec.gov/Archives/edgar/data/1065280/000106528026000211/nflx-20260716.htm',
    publishedAt: '2026-07-16',
  },
  {
    id: 'netflix-q2-2026-letter',
    kind: 'company-ir',
    title: 'Q2 2026 Shareholder Letter',
    publisher: 'Netflix, Inc.',
    url: 'https://www.sec.gov/Archives/edgar/data/1065280/000106528026000211/ex991_q226.htm',
    publishedAt: '2026-07-16',
  },
  {
    id: 'netflix-q2-2026-10q',
    kind: 'sec-filing',
    title: 'Quarterly Report on Form 10-Q · quarter ended June 30, 2026',
    publisher: 'Netflix, Inc. · U.S. SEC',
    url: 'https://www.sec.gov/Archives/edgar/data/1065280/000106528026000212/nflx-20260630.htm',
    publishedAt: '2026-07-17',
  },
  {
    id: 'eia-steo-july-2026',
    kind: 'government',
    title: 'Short-Term Energy Outlook, July 2026',
    publisher: 'U.S. Energy Information Administration',
    url: 'https://www.eia.gov/outlooks/steo/',
    publishedAt: '2026-07-07',
  },
  {
    id: 'world-bank-commodity-outlook-april-2026',
    kind: 'government',
    title: 'Commodity Markets Outlook, April 2026',
    publisher: 'World Bank',
    url: 'https://thedocs.worldbank.org/en/doc/f3138644a1e8e2bb631399ae11d6c408-0050012026/commodity-markets-outlook-april-2026',
    publishedAt: '2026-04-28',
  },
  {
    id: 'iea-critical-minerals-outlook-2025',
    kind: 'industry-data',
    title: 'Global Critical Minerals Outlook 2025',
    publisher: 'International Energy Agency',
    url: 'https://www.iea.org/reports/global-critical-minerals-outlook-2025',
    publishedAt: '2025-05-21',
  },
  {
    id: 'world-bank-infrastructure-foundations-2026',
    kind: 'government',
    title: 'Infrastructure Foundations: From Current Assets to Future Growth',
    publisher: 'World Bank',
    url: 'https://www.worldbank.org/en/topic/infrastructure/publication/infrastructure-foundations-from-current-assets-to-future-growth',
    publishedAt: '2026-04-24',
  },
  {
    id: 'molit-work-plan-2026',
    kind: 'government',
    title: '2026 국토교통부 업무계획',
    publisher: '국토교통부',
    url: 'https://www.molit.go.kr/2026plan/sub2_economy.html',
    publishedAt: '2025-12-12',
  },
  {
    id: 'us-census-construction-spending-may-2026',
    kind: 'government',
    title: 'Construction Spending, May 2026',
    publisher: 'U.S. Census Bureau',
    url: 'https://www.census.gov/construction/c30/pdf/release.pdf',
    publishedAt: '2026-07-01',
  },
  {
    id: 'ge-vernova-q1-2026-results',
    kind: 'company-ir',
    title: 'GE Vernova Reports First Quarter 2026 Financial Results and Raises 2026 Guidance',
    publisher: 'GE Vernova',
    url: 'https://www.gevernova.com/news/press-releases/ge-vernova-reports-first-quarter-2026-financial',
    publishedAt: '2026-04-22',
  },
  {
    id: 'siemens-energy-q1-fy2026-results',
    kind: 'company-ir',
    title: 'Q1 FY 2026: Continued Market Momentum Drives Strong Start to the Year',
    publisher: 'Siemens Energy',
    url: 'https://www.siemens-energy.com/global/en/home/press-releases/earnings-release-q1-fy-2026.html',
    publishedAt: '2026-02-11',
  },
  {
    id: 'fred-series-dgs2',
    kind: 'government',
    title: 'DGS2 · Market Yield on U.S. Treasury Securities at 2-Year Constant Maturity',
    publisher: 'FRED · Board of Governors of the Federal Reserve System (US)',
    url: 'https://fred.stlouisfed.org/series/DGS2',
    note: 'Percent · Daily · Not Seasonally Adjusted',
  },
  {
    id: 'fred-series-dgs10',
    kind: 'government',
    title: 'DGS10 · Market Yield on U.S. Treasury Securities at 10-Year Constant Maturity',
    publisher: 'FRED · Board of Governors of the Federal Reserve System (US)',
    url: 'https://fred.stlouisfed.org/series/DGS10',
    note: 'Percent · Daily · Not Seasonally Adjusted',
  },
  {
    id: 'fred-series-t10y2y',
    kind: 'government',
    title: 'T10Y2Y · 10-Year Treasury Constant Maturity Minus 2-Year Treasury Constant Maturity',
    publisher: 'FRED · Federal Reserve Bank of St. Louis',
    url: 'https://fred.stlouisfed.org/series/T10Y2Y',
    note: 'Percent · Daily · Not Seasonally Adjusted',
  },
  {
    id: 'fred-series-nfci',
    kind: 'government',
    title: 'NFCI · Chicago Fed National Financial Conditions Index',
    publisher: 'FRED · Federal Reserve Bank of Chicago',
    url: 'https://fred.stlouisfed.org/series/NFCI',
    note: 'Index · Weekly, Ending Friday · Not Seasonally Adjusted',
  },
  {
    id: 'fred-series-walcl',
    kind: 'government',
    title: 'WALCL · Federal Reserve Total Assets, Wednesday Level',
    publisher: 'FRED · Board of Governors of the Federal Reserve System (US)',
    url: 'https://fred.stlouisfed.org/series/WALCL',
    note: 'Millions of U.S. Dollars · Weekly, As of Wednesday · Not Seasonally Adjusted',
  },
  {
    id: 'fred-series-m2sl',
    kind: 'government',
    title: 'M2SL · M2',
    publisher: 'FRED · Board of Governors of the Federal Reserve System (US)',
    url: 'https://fred.stlouisfed.org/series/M2SL',
    note: 'Billions of Dollars · Monthly · Seasonally Adjusted',
  },
  {
    id: 'fred-series-indpro',
    kind: 'government',
    title: 'INDPRO · Industrial Production: Total Index',
    publisher: 'FRED · Board of Governors of the Federal Reserve System (US)',
    url: 'https://fred.stlouisfed.org/series/INDPRO',
    note: 'Index 2017=100 · Monthly · Seasonally Adjusted',
  },
  {
    id: 'fred-series-cumfns',
    kind: 'government',
    title: 'CUMFNS · Capacity Utilization: Manufacturing (SIC)',
    publisher: 'FRED · Board of Governors of the Federal Reserve System (US)',
    url: 'https://fred.stlouisfed.org/series/CUMFNS',
    note: 'Percent · Monthly · Seasonally Adjusted',
  },
  {
    id: 'fred-series-permit',
    kind: 'government',
    title: 'PERMIT · New Privately-Owned Housing Units Authorized: Total Units',
    publisher: 'FRED · U.S. Census Bureau and U.S. Department of Housing and Urban Development',
    url: 'https://fred.stlouisfed.org/series/PERMIT',
    note: 'Thousands of Units · Monthly · Seasonally Adjusted Annual Rate',
  },
  {
    id: 'smci-sec-2025-10k',
    kind: 'sec-filing',
    title: 'Super Micro Computer 2025 Form 10-K',
    publisher: 'SEC · Super Micro Computer',
    url: 'https://www.sec.gov/Archives/edgar/data/1375365/000137536525000027/0001375365-25-000027-index.htm',
    publishedAt: '2025-08-28',
  },
  {
    id: 'smci-sec-2026-q3-10q',
    kind: 'sec-filing',
    title: 'Super Micro Computer FY2026 Q3 Form 10-Q',
    publisher: 'SEC · Super Micro Computer',
    url: 'https://www.sec.gov/Archives/edgar/data/1375365/000137536526000014/0001375365-26-000014-index.htm',
    publishedAt: '2026-05-11',
  },
  {
    id: 'smci-sec-2026-preliminary-8k',
    kind: 'sec-filing',
    title: 'Super Micro Computer Preliminary Business Update Form 8-K',
    publisher: 'SEC · Super Micro Computer',
    url: 'https://www.sec.gov/Archives/edgar/data/1375365/000137536526000019/smci-20260721.htm',
    publishedAt: '2026-07-21',
  },
  {
    id: 'smci-ir-2026-q4-preliminary-update',
    kind: 'company-ir',
    title: 'Supermicro Provides Fourth Quarter of Fiscal Year 2026 Preliminary Business Update',
    publisher: 'Super Micro Computer',
    url: 'https://ir.supermicro.com/news/news-details/2026/Supermicro-Provides-Fourth-Quarter-of-Fiscal-Year-2026-Preliminary-Business-Update/default.aspx',
    publishedAt: '2026-07-21',
    note: '미감사 예비 수치 · 최종 실적은 달라질 수 있음',
  },
  {
    id: 'smci-yahoo-price-2026-07-22',
    kind: 'market-data',
    title: 'SMCI historical chart data',
    publisher: 'Yahoo Finance',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/SMCI?period1=1780272000&period2=1784851200&interval=1d&events=history',
    publishedAt: '2026-07-22',
    note: '2026-07-22 미국 정규장 종가·거래량 및 직전 20거래일 평균 계산',
  },
  {
    id: 'alphabet-2026-q1-10q',
    kind: 'sec-filing',
    title: 'Alphabet Inc. Form 10-Q for the quarter ended March 31, 2026',
    publisher: 'SEC · Alphabet',
    url: 'https://www.sec.gov/Archives/edgar/data/1652044/000165204426000048/goog-20260331.htm',
    publishedAt: '2026-04-30',
    note: 'US GAAP 연결 재무제표 · Google Services 및 Google Cloud 세그먼트',
  },
  {
    id: 'alphabet-wiz-completion-2026',
    kind: 'company-release',
    title: 'Google Completes Acquisition of Wiz',
    publisher: 'Alphabet Investor Relations',
    url: 'https://abc.xyz/investor/news/news-details/2026/Google-Completes-Acquisition-of-Wiz-2026-ta7OaU2uA0/default.aspx',
    publishedAt: '2026-03-11',
    note: '인수 완료와 거래 금액 확인 · 시너지와 통합 성과는 미확정',
  },
  {
    id: 'hana-financial-1h26-presentation',
    kind: 'company-ir',
    title: 'Hana Financial Group 1H26 Presentation',
    publisher: '하나금융그룹',
    url: 'https://www.hanafn.com:8002/download/10079717/crossDownload.do',
    publishedAt: '2026-07-24',
    note: 'IFRS 연결 기준 2026년 상반기 실적·자산건전성·자본적정성',
  },
  {
    id: 'hana-financial-1h26-databook',
    kind: 'company-ir',
    title: 'Hana Financial Group 1H26 IR Databook',
    publisher: '하나금융그룹',
    url: 'https://www.hanafn.com:8002/download/10079741/crossDownload.do',
    publishedAt: '2026-07-24',
    note: '그룹 연결 손익·대출·예금·자산건전성·Basel III 자본비율',
  },
];
