import type { DailyStockDissection } from '../types.js';

export const skHynixSelloff: DailyStockDissection = {
  id: 'stock-2026-07-13-sk-hynix-selloff',
  slug: '2026-07-13-sk-hynix-selloff',
  status: 'published',
  publishedAt: '2026-07-17',
  eventAsOf: '2026-07-13',
  priceAsOf: '2026-07-13',
  company: { name: 'SK하이닉스', ticker: '000660.KS', companySlug: 'sk-hynix' },
  headline: 'SK하이닉스, 왜 하루 만에 15.37%나 급락했을까?',
  priceMove: {
    value: -15.37,
    unit: 'percent',
    periodLabel: '2026년 7월 13일 기준',
    sourceId: 'skh-price-2026-07-13',
    precision: 2,
  },
  directCatalyst: '중동 긴장, AI·메모리 피크아웃 우려, ADR 프리미엄 부담과 대규모 매도가 겹쳤습니다.',
  marketInterpretation: '회사 실적이 하루 만에 15% 나빠졌다기보다, 시장이 실적 악화 가능성과 수급 부담을 먼저 가격에 반영한 움직임입니다.',
  moveCharacter: 'mixed',
  cardCharacter: '시장 공포와 수급·밸류에이션 재조정',
  confirmedItems: [
    '2026년 7월 13일 SK하이닉스 주가는 -15.37% 움직였습니다.',
    '같은 거래일 삼성전자 주가는 -10.70% 움직여, 두 종목의 수익률 차이는 -4.67%p였습니다.',
    '중동 긴장 확대, 유가 상승, 달러 강세와 위험자산 회피가 국내 증시 전반에 부담을 줬습니다.',
  ],
  unconfirmedItems: [
    'HBM 주문 취소',
    '주요 고객사 물량 축소',
    '실적 전망 공식 하향',
    'HBM 가격 급락',
    '대형 수주 취소',
  ],
  reasons: [
    { title: '시장 전체 위험회피', explanation: '중동 긴장이 확대되고 유가와 달러가 오르면서 국내 위험자산 전반에 매도가 집중됐습니다.' },
    { title: 'AI·메모리 기대 재평가', explanation: 'HBM과 AI 서버 수요가 정점을 지나는 것 아니냐는 의심이 커지며 기대를 많이 반영한 종목의 변동성이 확대됐습니다.' },
    { title: 'ADR 프리미엄 부담', explanation: '미국 ADR 상장 첫날 강세 이후 국내 본주와의 가격 괴리가 커져 차익실현과 수급 재조정 부담이 생겼습니다.' },
    { title: '대규모 매도와 청산', explanation: '외국인·기관 매도에 레버리지 청산과 손절 물량이 겹치며 낙폭이 커졌습니다.' },
  ],
  verification: {
    authoredBy: 'owner',
    verifiedBy: 'owner',
    verifiedAt: '2026-07-17T16:55:00+09:00',
    status: 'ownerVerified',
    note: '사용자가 제공한 완성 원고와 수치·사건 기준일을 편집 기준에 따라 확인했습니다.',
  },
  evidence: [
    {
      id: 'skh-price-2026-07-13',
      type: 'price',
      factStatus: 'marketData',
      publisher: '사용자 검증 시세 자료',
      title: 'SK하이닉스와 삼성전자 동일 거래일 등락률',
      asOf: '2026-07-13',
      note: 'SK하이닉스 -15.37%, 삼성전자 -10.70%. 같은 거래일 종가 기준 수치입니다.',
    },
    {
      id: 'skh-market-2026-07-13',
      type: 'market',
      factStatus: 'mediaReported',
      title: '중동 긴장·유가·달러·위험회피 환경',
      asOf: '2026-07-13',
      note: '시장 전체 위험회피 배경을 설명하는 근거 유형입니다.',
    },
    {
      id: 'skh-sector-2026-07-13',
      type: 'sector',
      factStatus: 'editorialInterpretation',
      title: 'AI·메모리 피크아웃 우려와 HBM 기대 재평가',
      asOf: '2026-07-13',
      note: '확정된 주문 취소가 아니라 당시 가격에 반영된 업종 우려로 구분합니다.',
    },
    {
      id: 'skh-flow-2026-07-13',
      type: 'flow',
      factStatus: 'marketData',
      title: '외국인·기관 매도와 레버리지 청산',
      asOf: '2026-07-13',
      note: '당일 낙폭을 키운 수급 자료 유형입니다.',
    },
  ],
  fullArticle: [
    '7월 13일 SK하이닉스는 -15.37% 급락했습니다.',
    '삼성전자도 -10.70% 하락했지만, 하이닉스의 낙폭이 더 컸습니다.',
    '이번 하락은 한 가지 악재보다 여러 충격이 겹친 결과에 가깝습니다.',
    '먼저 중동 긴장 확대입니다. 유가가 오르고 달러가 강해지면서 위험자산 회피 심리가 커졌고, 국내 증시 전체가 크게 흔들렸습니다.',
    '두 번째는 AI·메모리 피크아웃 우려입니다. HBM과 AI 서버 수요가 정점을 찍는 것 아니냐는 의심이 커지면서 AI 기대를 가장 많이 반영했던 하이닉스가 더 세게 맞았습니다.',
    '세 번째는 ADR 프리미엄 부담입니다. 미국 ADR 상장 첫날 강세 이후 국내 본주와 가격 괴리가 커졌고, 차익실현과 수급 재조정 부담이 발생했습니다.',
    '마지막은 외국인·기관의 대규모 매도입니다. 시장 급락 속에서 레버리지 청산과 손절 물량까지 겹치며 낙폭이 더 커졌습니다.',
    '다만 아직 확인되지 않은 것도 많습니다. HBM 주문 취소, 주요 고객사 물량 축소, 실적 전망 공식 하향, HBM 가격 급락, 대형 수주 취소는 현재까지 공식 확인되지 않았습니다.',
    '즉, 회사 실적이 하루 만에 15% 나빠졌다기보다 시장이 먼저 최악의 시나리오를 가격에 반영한 성격이 강합니다.',
    '오늘 급락은 기업 붕괴보다 밸류에이션과 수급 재조정에 더 가깝습니다.',
    '결국 오늘 하이닉스를 무너뜨린 건 실적 악화 확정보다 공포와 수급이었습니다.',
  ],
  editorialConclusion: '회사 실적이 하루 만에 15% 나빠졌다기보다, 시장이 실적 악화 가능성과 수급 부담을 먼저 가격에 반영한 움직임입니다.',
  comparison: {
    sector: { name: '삼성전자', value: -10.70, asOf: '2026-07-13', sourceId: 'skh-price-2026-07-13', precision: 2 },
  },
  marketWideFactors: ['중동 긴장 확대', '유가 상승', '달러 강세', '위험자산 회피'],
  companySpecificFactors: ['AI·메모리 피크아웃 우려', 'HBM 기대 재평가', 'ADR 프리미엄 부담', '외국인·기관 매도', '레버리지 청산과 손절 물량'],
  thesisImpact: 'maintain',
  watchItems: ['ADR 가격 안정 여부', 'HBM과 AI 서버 수요', '외국인 수급', '메모리 가격 흐름', '다음 실적과 가이던스'],
  relatedThreeReadsIds: [],
  sourceIds: ['skh-market-2026-07-13', 'skh-sector-2026-07-13', 'skh-flow-2026-07-13'],
  disclaimer: '본 콘텐츠는 투자 권유가 아닌 종목 분석 목적의 자료입니다.',
};

export default skHynixSelloff;
