import type { DailyStockDissection } from '../types.js';

export const intelEarningsCapexReversal: DailyStockDissection = {
  id: 'stock-2026-07-25-intel-earnings-capex-reversal',
  slug: '2026-07-25-intel-earnings-capex-reversal',
  status: 'published',
  publishedAt: '2026-07-25',
  eventAsOf: '2026-07-23',
  priceAsOf: '2026-07-24',
  company: { name: 'Intel Corporation', ticker: 'INTC' },
  headline: '인텔, 왜 -7.892% 움직였을까?',
  priceMove: {
    value: -7.892,
    unit: 'percent',
    periodLabel: '2026년 7월 24일 미국 정규장 종가 · $100.23 → $92.32',
    sourceId: 'intel-yahoo-price-2026-07-24',
    precision: 3,
  },
  directCatalyst: '7월 23일 장 마감 후 발표된 Q2 실적과 Q3 가이던스는 시장 기대를 웃돌았지만, 2026년 자본지출 전망이 $18B에서 $20B로 높아지고 Foundry 적자가 지속된 점이 함께 공개됐습니다.',
  marketInterpretation: '영업 지표는 개선됐지만 시장의 검증 기준은 단순한 실적 회복에서 대규모 투자 회수와 Foundry의 현금수익 전환으로 높아졌습니다. 반도체 업종 약세와 포지션 축소가 낙폭을 키웠으나 요인별 기여도는 확인할 수 없습니다.',
  moveCharacter: 'mixed',
  cardCharacter: '영업 개선 속 기대치 재조정',
  confirmedItems: [
    '2026년 7월 24일 정규장 종가 $92.32, 전일 대비 -7.892%',
    'Q2 매출 $16.128B, 전년 동기 대비 +25.4%',
    'Q2 GAAP 매출총이익률 40.4%, GAAP 영업이익 $1.796B',
    'Q2 비GAAP 순이익 $2.197B, 비GAAP EPS $0.42',
    'Q2 DCAI 매출 $6.262B, 전년 동기 대비 +59%',
    'Q2 Foundry 매출 $5.765B, 영업손실 $2.089B',
    'Q3 회사 전망은 매출 $15.8B~$16.8B, 비GAAP 매출총이익률 42.0%, EPS $0.38',
    '2026년 자본지출 전망을 $18B에서 $20B로 상향',
    '거래량 179,108,323주, 직전 20거래일 평균의 1.667배',
  ],
  unconfirmedItems: [
    '14A 고객 논의가 수익성 있는 외부 Foundry 매출로 이어지는지',
    'Apple이 Intel 생산을 공식 계약했다는 주장',
    '2026~2027년 투자 확대가 자본비용을 넘는 수익률을 만드는지',
    '특정 대형주주의 강제매도가 급락을 만들었다는 주장',
    '자본지출·Foundry 적자·이익 실현·업종 매도의 하락 기여도',
    '2026년 Q3 실적 발표 공식 날짜',
  ],
  reasons: [
    { title: '높아진 회복 기대', explanation: '7월 23일 기준 연초 대비 170% 이상 오른 상태라 회복 방향보다 속도와 투자수익률이 중요해졌습니다.' },
    { title: 'Foundry 수익성 검증', explanation: 'Foundry 매출은 31% 늘었지만 $2.089B 영업손실이 남아 있습니다.' },
    { title: '자본지출의 양면성', explanation: 'AI CPU와 14A 수요 대응 투자는 기회를 늘리지만 현금흐름·자금조달·감가상각 부담도 키울 수 있습니다.' },
    { title: '업종 약세와 포지셔닝', explanation: 'SOXX 약세와 거래량 1.667배가 낙폭을 키웠으나 강제매도는 확인되지 않았습니다.' },
  ],
  verification: {
    authoredBy: 'owner',
    verifiedBy: 'owner',
    verifiedAt: '2026-07-25T12:38:57+09:00',
    status: 'ownerVerified',
    note: '구조화 handoff, 공개 website article과 verified research의 날짜·세션·핵심 수치 일치를 확인했습니다.',
  },
  intake: {
    contentType: 'stock_dissection',
    status: 'owner_verified',
    session: 'regular',
    researchSourceFile: 'docs/editorial-inputs/2026-07-25-intel-earnings-capex-reversal/01_verified-research.md',
    detailSourceFile: 'docs/editorial-inputs/2026-07-25-intel-earnings-capex-reversal/04_website-article.md',
    handoffSourceFile: 'docs/editorial-inputs/2026-07-25-intel-earnings-capex-reversal/05_website-handoff.yaml',
    keyFiguresConsistent: true,
  },
  fullArticle: [
    'Intel의 7월 24일 급락은 2분기 영업 실적 악화만으로 설명하기 어렵습니다. 매출은 25.4% 늘었고 비GAAP EPS와 3분기 가이던스는 시장 기대를 웃돌았으며 데이터센터·AI 매출도 59% 증가했습니다.',
    '가격이 반대로 움직인 핵심은 AI 수요에 대응해 늘리는 설비투자가 언제 파운드리 외부 매출과 현금수익으로 전환되는가라는 질문입니다. Foundry는 성장했지만 $2.089B의 영업손실을 기록했고 회사는 올해 자본지출 전망을 $18B에서 $20B로 올렸습니다.',
    '실적 발표 직후 보도된 +5.2%는 시간외 스냅샷입니다. 대표 등락률은 다음 날 미국 정규장 종가 기준 -7.892%이며 두 세션을 하나의 일간 수익률처럼 합치지 않습니다.',
    '같은 세션에 S&P 500은 0.050% 상승했고 SOXX는 4.396%, AMD는 3.287% 하락했습니다. Intel은 각각 -7.942%p, -3.496%p, -4.605%p 뒤처졌고 거래량은 직전 20거래일 평균의 1.667배였습니다.',
    'GAAP 순손실 $11.033B에는 미국 정부 계약 관련 에스크로 주식 평가손실 $12.529B가 포함돼 있어 본업 영업손실과 구분해야 합니다. 반면 조정 잉여현금흐름 -$8.419B와 향후 투자 확대는 별도의 현금흐름 점검 대상입니다.',
    '이번 움직임은 전면적인 펀더멘털 악화보다 기대치 재조정, 밸류에이션 변화, 신규 사업 선택가치와 포지셔닝이 결합된 mixed 사례입니다. 기존 판단은 partially_revise이며 매출·마진·CapEx·현금흐름 입력값이 함께 바뀌어 가치평가 재검토가 필요합니다.',
  ],
  editorialConclusion: '본업 회복은 확인됐지만 시장의 질문은 회복 가능성에서 추가 자본의 회수 시점으로 이동했습니다. 주가 하락 자체보다 Foundry 손실과 투자 확대가 실제 현금수익으로 바뀌는지를 확인해야 합니다.',
  comparison: {
    market: { name: 'S&P 500', value: 0.050, asOf: '2026-07-24', sourceId: 'intel-ap-market-2026-07-24', precision: 3 },
    sector: { name: 'SOXX', value: -4.396, asOf: '2026-07-24', sourceId: 'intel-soxx-price-2026-07-24', precision: 3 },
  },
  marketWideFactors: [
    '2026년 7월 24일 S&P 500 +0.050%, Nasdaq Composite -0.644%',
    'SOXX -4.396%, Micron -7.0%, Broadcom -2.7%로 반도체 업종이 약세였습니다.',
    'AI 설비투자 수익성 우려와 중동 충돌·관세·금리 불확실성이 배경이었습니다.',
  ],
  companySpecificFactors: [
    'Q2 매출·비GAAP EPS와 Q3 전망은 시장 기대를 웃돌았습니다.',
    '2026년 CapEx 전망이 $18B에서 $20B로 확대됐습니다.',
    'Foundry는 $2.089B 영업손실을 기록했습니다.',
    '시간외 +5.2% 뒤 다음 정규장 -7.892%로 반전했고 거래량은 1.667배였습니다.',
  ],
  thesisImpact: 'partiallyRevise',
  watchItems: [
    '2026년 7월 27일 Intel과 SOXX 상대수익률 및 거래량 정상화',
    '2026년 7월 28~29일 FOMC 금리 경로',
    'Q3 매출 $15.8B~$16.8B·비GAAP 매출총이익률 42.0%·EPS $0.38 전망',
    '2026년 10월 DCAI 성장·Foundry 손실·2027년 투자계획',
    '2028년 14A 양산과 외부 고객 매출·수익성 연결',
  ],
  relatedThreeReadsIds: [],
  sourceIds: [
    'intel-ir-q2-2026',
    'intel-reuters-2026-07-23',
    'intel-ap-market-2026-07-24',
    'intel-soxx-price-2026-07-24',
    'intel-fed-fomc-2026',
  ],
  evidence: [
    { id: 'intel-ir-q2-2026', type: 'company', factStatus: 'official', publisher: 'Intel Investor Relations', title: 'Intel Reports Second-Quarter 2026 Financial Results', publishedAt: '2026-07-23', asOf: '2026-06-27', url: 'https://www.intc.com/news-events/press-releases/detail/1776/intel-reports-second-quarter-2026-financial-results', note: 'Q2 실적·사업부 손익·Q3 전망' },
    { id: 'intel-reuters-2026-07-23', type: 'news', factStatus: 'mediaReported', publisher: 'Reuters', title: 'Intel forecast crushes estimates as AI boom boosts chip demand', publishedAt: '2026-07-23', asOf: '2026-07-23', url: 'https://au.investing.com/news/stock-market-news/intel-sales-profit-forecast-beat-estimates-boosts-spending-plans-on-ai-boom-4549974', note: 'LSEG 기대, 시간외 반응, CapEx 상향과 주가 맥락' },
    { id: 'intel-ap-market-2026-07-24', type: 'market', factStatus: 'mediaReported', publisher: 'AP', title: 'Stocks waver on Wall Street while crude oil prices fall for the first time in a week', publishedAt: '2026-07-24', asOf: '2026-07-24', url: 'https://apnews.com/article/stocks-markets-tariffs-oil-trump-ai-0b9c3b2aa5ca83eb391c1388efe03c97', note: '동일 세션 S&P 500·Nasdaq과 반도체 업종 배경' },
    { id: 'intel-yahoo-price-2026-07-24', type: 'price', factStatus: 'marketData', publisher: 'Yahoo Finance', title: 'INTC Historical Chart API', asOf: '2026-07-24', url: 'https://query1.finance.yahoo.com/v8/finance/chart/INTC?period1=1778889600&period2=1785110400&interval=1d&events=history', note: '정규장 종가·거래량과 직전 20거래일 평균 계산' },
    { id: 'intel-nasdaq-price-2026-07-24', type: 'price', factStatus: 'marketData', publisher: 'Nasdaq', title: 'Intel Corporation Common Stock Historical Data', asOf: '2026-07-24', url: 'https://www.nasdaq.com/market-activity/stocks/intc/historical', note: '정규장 종가 보조 확인' },
    { id: 'intel-soxx-price-2026-07-24', type: 'sector', factStatus: 'marketData', publisher: 'Yahoo Finance', title: 'SOXX Historical Chart API', asOf: '2026-07-24', url: 'https://query1.finance.yahoo.com/v8/finance/chart/SOXX?period1=1784246400&period2=1785110400&interval=1d', note: '동일 세션 반도체 ETF 비교' },
    { id: 'intel-amd-price-2026-07-24', type: 'sector', factStatus: 'marketData', publisher: 'Yahoo Finance', title: 'AMD Historical Chart API', asOf: '2026-07-24', url: 'https://query1.finance.yahoo.com/v8/finance/chart/AMD?period1=1784246400&period2=1785110400&interval=1d', note: '동일 세션 CPU 경쟁사 비교' },
    { id: 'intel-fed-fomc-2026', type: 'regulatory', factStatus: 'official', publisher: 'Federal Reserve', title: 'FOMC Meeting Calendars', publishedAt: '2026-07-08', asOf: '2026-07-25', url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm', note: '7월 28~29일 FOMC 일정' },
    { id: 'intel-ir-calendar-2026-07-25', type: 'company', factStatus: 'official', publisher: 'Intel Investor Relations', title: 'IR Calendar', asOf: '2026-07-25', url: 'https://www.intc.com/news-events/ir-calendar', note: 'Q3 실적 발표 공식 일정 미게시 확인' },
    { id: 'intel-editorial-interpretation-2026-07-25', type: 'market', factStatus: 'editorialInterpretation', publisher: '주가해부실', title: '본 리서치 종합 판단', publishedAt: '2026-07-25', asOf: '2026-07-25', note: '투자 회수 검증으로 높아진 기대치와 mixed 움직임이라는 편집 해석' },
  ],
  disclaimer: '본 콘텐츠는 투자 권유가 아닌 종목 분석 목적의 자료입니다. 공개된 자료를 기준으로 작성했으며 이후 정보에 따라 판단은 달라질 수 있습니다.',
};

export default intelEarningsCapexReversal;
