import type { SupplyChainBottleneck } from './types.js';

export const supplyChainBottlenecks: SupplyChainBottleneck[] = [
  {
    id: 'grid-transformers-high-voltage',
    slug: 'grid-transformers-high-voltage',
    title: '변압기·고압 전력기기 공급 제약',
    shortTitle: '변압기·고압 전력기기',
    category: 'power-grid',
    status: 'tight',
    trend: 'tightening',
    confidence: 'high',
    featured: true,
    summary: '전력망과 데이터센터용 전력기기 주문이 빠르게 늘어 공급능력 증설이 따라가는지 계속 확인해야 합니다.',
    assessment: '공식 전력 투자 전망과 복수 기업의 수주 지표가 같은 방향을 보여 현재 공급 여건을 타이트로 판단합니다. 다만 제품·전압·지역별 리드타임은 같지 않습니다.',
    pressureSignals: [
      '전기 부문 수주잔고가 전년 대비 큰 폭으로 증가했습니다.',
      '전력망 투자와 데이터센터용 전력기기 주문이 동시에 확대되고 있습니다.',
      '고압 장비는 생산라인 증설과 고객 인증에 시간이 필요합니다.',
    ],
    reliefSignals: [
      '신규 변압기·전력기기 생산라인의 실제 가동 시작',
      '제품별 리드타임 축소와 수주잔고 증가율 둔화',
      '지역별 대체 공급자와 인증 제품 확대',
    ],
    uncertainties: [
      '공개 수주잔고에는 변압기 외 다른 전기 제품이 함께 포함됩니다.',
      '기업별 제품 구성과 지역별 납기는 공개 범위가 다릅니다.',
    ],
    evidence: [
      {
        id: 'grid-iea-investment-gap',
        label: '2030년 필요 전력망 투자',
        value: '+50%',
        context: 'IEA는 현재 연간 약 4,000억 달러 수준에서 2030년까지 투자가 절반 더 늘어야 한다고 봅니다.',
        asOf: '2026-02-06',
        sourceRef: 'iea-electricity-2026',
        kind: 'official-data',
      },
      {
        id: 'grid-eaton-electrical-backlog',
        label: 'Eaton Electrical 수주잔고',
        value: '+48%',
        context: '2026년 1분기 공식 실적 발표의 전년 대비 수주잔고 증가율입니다.',
        asOf: '2026-04-30',
        sourceRef: 'eaton-q1-2026-results',
        kind: 'company-disclosure',
      },
      {
        id: 'grid-ge-data-center-orders',
        label: 'GE Vernova 데이터센터 전력기기 주문',
        value: '$2.4B',
        context: '2026년 1분기 Electrification 장비 주문 중 데이터센터 지원 목적 주문입니다.',
        asOf: '2026-04-22',
        sourceRef: 'ge-vernova-q1-2026-results',
        kind: 'company-disclosure',
      },
    ],
    sourceRefs: ['iea-electricity-2026', 'eaton-q1-2026-results', 'ge-vernova-q1-2026-results'],
    reportIds: ['iea-electricity-2026', 'eaton-q1-2026'],
    marketMapIds: ['datacenter-power-cooling', 'semiconductor-cluster-infrastructure'],
    companyLinks: [
      { companyId: 'datacenter-power-eaton', role: 'constrained-supplier', reason: '데이터센터·전력망용 전력관리 장비 공급자이며 수주잔고 변화를 공개합니다.' },
      { companyId: 'us-energy-grid-ge-vernova', role: 'capacity-provider', reason: 'Grid Solutions와 Prolec GE를 통해 전력망 장비 공급능력을 확대하고 있습니다.' },
      { companyId: 'cluster-ls-electric', role: 'alternative-supplier', reason: '배전·전력설비의 국내 공급 대안으로 생산능력과 수주를 확인합니다.' },
      { companyId: 'cluster-hyosung-heavy', role: 'alternative-supplier', reason: '변압기·고압 전력설비 공급자로 제품별 수주와 증설을 확인합니다.' },
    ],
    pickIds: [],
    macroIndicatorIds: ['us-industrial-production', 'us-manufacturing-utilization'],
    asOf: '2026-04-30',
    reviewedAt: '2026-07-12',
  },
  {
    id: 'data-center-power-cooling',
    slug: 'data-center-power-cooling',
    title: '데이터센터 전력·냉각 공급 제약',
    shortTitle: '데이터센터 전력·냉각',
    category: 'data-centers',
    status: 'tight',
    trend: 'tightening',
    confidence: 'high',
    summary: 'AI 서버 증설 속도가 전력 인입·배전·냉각 설비 공급과 현장 구축 속도를 압박하고 있습니다.',
    assessment: '데이터센터 전력수요 전망, AI 컴퓨팅 매출, 전력기기 수주잔고가 함께 증가해 구조적 공급 압력이 이어지는 것으로 판단합니다.',
    pressureSignals: [
      '데이터센터 전력수요가 2030년까지 두 배 이상 늘어날 전망입니다.',
      'AI 컴퓨팅 수요가 GPU뿐 아니라 배전·UPS·냉각 설비 주문을 밀고 있습니다.',
      '전력 인입과 냉각 설계는 장비 납기 외에도 인허가·시공 기간이 필요합니다.',
    ],
    reliefSignals: [
      '신규 전력·냉각 생산라인 가동과 설치 인력 확대',
      '데이터센터 전력 인입 대기기간과 장비 납기 축소',
      '고밀도 랙의 전력 효율 개선과 대체 냉각 방식 확산',
    ],
    uncertainties: [
      '프로젝트별 전력 밀도와 냉각 방식에 따라 병목 지점이 다릅니다.',
      '발표된 데이터센터 투자가 모두 같은 일정으로 집행되는 것은 아닙니다.',
    ],
    evidence: [
      {
        id: 'dc-iea-electricity-demand',
        label: '2030년 데이터센터 전력소비',
        value: '945',
        unit: 'TWh',
        context: 'IEA의 세계 데이터센터 전력소비 전망입니다.',
        asOf: '2025-04-10',
        sourceRef: 'iea-energy-and-ai-2025',
        kind: 'official-data',
      },
      {
        id: 'dc-nvidia-revenue',
        label: 'NVIDIA 데이터센터 매출',
        value: '$75.2B',
        context: 'FY2027 1분기 실제 매출이며 전년 동기 대비 92% 증가했습니다.',
        asOf: '2026-05-20',
        sourceRef: 'nvidia-fy2027-q1-results',
        kind: 'company-disclosure',
      },
      {
        id: 'dc-eaton-backlog',
        label: 'Eaton Electrical 수주잔고',
        value: '+48%',
        context: '2026년 1분기 기준 전년 대비 증가율입니다.',
        asOf: '2026-04-30',
        sourceRef: 'eaton-q1-2026-results',
        kind: 'company-disclosure',
      },
    ],
    sourceRefs: ['iea-energy-and-ai-2025', 'nvidia-fy2027-q1-results', 'eaton-q1-2026-results'],
    reportIds: ['iea-energy-and-ai-2025', 'nvidia-fy2027-q1', 'eaton-q1-2026'],
    marketMapIds: ['datacenter-power-cooling'],
    companyLinks: [
      { companyId: 'us-semiconductors-nvidia', role: 'demand-driver', reason: 'AI GPU와 시스템 수요가 데이터센터 전력·냉각 밀도를 높이는 수요 측 기업입니다.' },
      { companyId: 'datacenter-power-vertiv', role: 'constrained-supplier', reason: 'UPS·열관리·냉각 인프라 공급자로 주문과 납기를 확인합니다.' },
      { companyId: 'datacenter-power-eaton', role: 'capacity-provider', reason: '배전·전력관리 장비 공급능력과 수주잔고를 공개합니다.' },
      { companyId: 'datacenter-power-schneider', role: 'alternative-supplier', reason: '전력관리·자동화·데이터센터 인프라의 대체 공급 축입니다.' },
      { companyId: 'datacenter-power-lg-electronics', role: 'capacity-provider', reason: '칠러와 냉각 솔루션 공급 확대 여부를 확인합니다.' },
    ],
    pickIds: ['pick-lg-electronics-ai-datacenter-cooling'],
    macroIndicatorIds: ['us-industrial-production', 'us-manufacturing-utilization'],
    asOf: '2026-05-20',
    reviewedAt: '2026-07-12',
  },
  {
    id: 'gas-turbine-capacity',
    slug: 'gas-turbine-capacity',
    title: '대형 가스터빈 생산 슬롯 제약',
    shortTitle: '가스터빈 생산 슬롯',
    category: 'generation',
    status: 'tight',
    trend: 'tightening',
    confidence: 'high',
    summary: '전력 수요 확대와 함께 대형 가스터빈 주문·예약이 빠르게 쌓이며 생산 슬롯이 장기화되고 있습니다.',
    assessment: '두 주요 공급자의 공식 주문·백로그 자료가 같은 방향을 보여 생산 슬롯을 타이트로 판단합니다. 실제 발전소 일정은 인허가와 EPC 진행 상황도 함께 봐야 합니다.',
    pressureSignals: [
      'GE Vernova의 가스터빈 백로그·슬롯 예약이 분기 중 83GW에서 100GW로 늘었습니다.',
      'Siemens Energy Gas Services가 한 분기에 102대의 가스터빈 주문을 기록했습니다.',
      '대형 터빈은 생산과 현장 설치까지 긴 프로젝트 주기를 가집니다.',
    ],
    reliefSignals: [
      '주요 공급자의 연간 생산대수와 조립능력 확대',
      '슬롯 예약 증가율 둔화와 취소 없이 실제 계약 전환',
      '대체 발전원·저장장치의 상업 운전 확대',
    ],
    uncertainties: [
      '슬롯 예약은 최종 장비 인도나 발전소 착공과 동일하지 않습니다.',
      '가스터빈 크기·효율·지역별 규제에 따라 공급 여건이 다릅니다.',
    ],
    evidence: [
      {
        id: 'gas-ge-slot-backlog',
        label: 'GE Vernova 백로그·슬롯 예약',
        value: '100',
        unit: 'GW',
        context: '2026년 1분기 말 기준이며 직전 83GW에서 증가했습니다.',
        asOf: '2026-04-22',
        sourceRef: 'ge-vernova-q1-2026-results',
        kind: 'company-disclosure',
      },
      {
        id: 'gas-siemens-orders',
        label: 'Siemens Energy 가스터빈 주문',
        value: '102',
        unit: '대',
        context: 'FY2026 1분기 Gas Services가 기록한 공식 주문 수입니다.',
        asOf: '2026-02-11',
        sourceRef: 'siemens-energy-q1-fy2026-results',
        kind: 'company-disclosure',
      },
      {
        id: 'gas-iea-demand-growth',
        label: '2026–2030 세계 전력수요 성장',
        value: '3.6%',
        context: 'IEA가 제시한 연평균 세계 전력수요 성장 전망입니다.',
        asOf: '2026-02-06',
        sourceRef: 'iea-electricity-2026',
        kind: 'official-data',
      },
    ],
    sourceRefs: ['ge-vernova-q1-2026-results', 'siemens-energy-q1-fy2026-results', 'iea-electricity-2026'],
    reportIds: ['iea-electricity-2026'],
    marketMapIds: ['datacenter-power-cooling', 'reconstruction-infrastructure'],
    companyLinks: [
      { companyId: 'us-energy-grid-ge-vernova', role: 'constrained-supplier', reason: '대형 가스터빈 백로그와 생산 슬롯 예약을 직접 공개하는 공급자입니다.' },
      { companyId: 'us-energy-grid-nextera', role: 'demand-driver', reason: '발전·전력설비 투자를 집행하는 유틸리티 수요 측 기업입니다.' },
    ],
    pickIds: [],
    macroIndicatorIds: ['us-industrial-production', 'us-manufacturing-utilization'],
    asOf: '2026-04-22',
    reviewedAt: '2026-07-12',
  },
  {
    id: 'hbm-advanced-packaging',
    slug: 'hbm-advanced-packaging',
    title: 'HBM·첨단 패키징 생산 제약',
    shortTitle: 'HBM·첨단 패키징',
    category: 'semiconductors',
    status: 'tight',
    trend: 'tightening',
    confidence: 'high',
    summary: 'AI 가속기 수요가 HBM 생산·후공정·장비 투자를 동시에 밀어 공급능력 전환 속도가 핵심입니다.',
    assessment: 'AI 데이터센터 매출과 메모리 업체 실적·가이던스, 산업 장비투자 전망이 같은 방향을 보여 공급망이 타이트한 것으로 판단합니다.',
    pressureSignals: [
      'AI 데이터센터 매출 성장으로 고대역폭 메모리 수요가 빠르게 늘고 있습니다.',
      'HBM은 메모리 웨이퍼뿐 아니라 적층·본딩·테스트 공정 능력이 필요합니다.',
      '300mm 메모리 장비 투자가 확대되지만 신규 생산능력 반영에는 시차가 있습니다.',
    ],
    reliefSignals: [
      '신규 HBM 생산라인의 고객 인증과 양산 출하 시작',
      '첨단 패키징·본딩 장비 생산능력 확대',
      'HBM 공급자 다변화와 범용 메모리 재고 정상화',
    ],
    uncertainties: [
      '기업별 HBM 세대와 고객 인증 시점은 공개 범위가 제한적입니다.',
      '범용 DRAM 가격 사이클과 HBM 공급 여건은 다르게 움직일 수 있습니다.',
    ],
    evidence: [
      {
        id: 'hbm-nvidia-demand',
        label: 'NVIDIA 데이터센터 매출',
        value: '$75.2B',
        context: 'FY2027 1분기 실제 매출이며 AI 시스템 수요의 수요 측 지표입니다.',
        asOf: '2026-05-20',
        sourceRef: 'nvidia-fy2027-q1-results',
        kind: 'company-disclosure',
      },
      {
        id: 'hbm-micron-guidance',
        label: 'Micron 다음 분기 매출 가이던스',
        value: '$50B ± $1B',
        context: 'FY2026 4분기 공식 전망으로 메모리 수요와 가격 환경을 함께 반영합니다.',
        asOf: '2026-06-24',
        sourceRef: 'micron-fy2026-q3-results',
        kind: 'company-disclosure',
      },
      {
        id: 'hbm-semi-investment',
        label: '2026년 300mm 메모리 장비 투자',
        value: '$52B',
        context: 'SEMI가 제시한 2026년 산업 전망입니다.',
        asOf: '2026-06-29',
        sourceRef: 'semi-memory-fab-outlook-q2-2026',
        kind: 'industry-report',
      },
    ],
    sourceRefs: ['nvidia-fy2027-q1-results', 'micron-fy2026-q3-results', 'semi-memory-fab-outlook-q2-2026'],
    reportIds: ['nvidia-fy2027-q1', 'micron-fy2026-q3', 'semi-300mm-memory-2026'],
    marketMapIds: ['us-semiconductors'],
    companyLinks: [
      { companyId: 'ai-datacenter-sk-hynix', role: 'constrained-supplier', reason: 'HBM 양산과 고객 인증을 통해 공급능력을 제공하는 핵심 메모리 공급자입니다.' },
      { companyId: 'ai-datacenter-micron', role: 'capacity-provider', reason: 'HBM·DRAM 증설과 출하가 추가 공급능력으로 연결되는지 확인합니다.' },
      { companyId: 'us-semiconductors-nvidia', role: 'demand-driver', reason: 'AI 가속기 판매가 HBM과 첨단 패키징 수요를 유발합니다.' },
      { companyId: 'ai-datacenter-asml', role: 'procurement-exposure', reason: '첨단 메모리 생산에 필요한 노광장비 공급과 고객 CAPEX에 노출됩니다.' },
      { companyId: 'ai-datacenter-hanmi', role: 'capacity-provider', reason: 'HBM 적층·본딩 공정 장비 공급능력 확대 여부를 확인합니다.' },
    ],
    pickIds: ['pick-micron-ai-memory-hbm-demand'],
    asOf: '2026-06-29',
    reviewedAt: '2026-07-12',
  },
  {
    id: 'copper-grid-metals',
    slug: 'copper-grid-metals',
    title: '구리·전력망 핵심 금속 공급 관찰',
    shortTitle: '구리·전력망 핵심 금속',
    category: 'critical-minerals',
    status: 'watch',
    trend: 'stable',
    confidence: 'medium',
    summary: '장기 구리 공급 부족 전망은 뚜렷하지만 단기 재고와 가격 변동만으로 현재의 심각한 병목을 단정하기 어렵습니다.',
    assessment: '복수 공공기관의 장기 수급 전망을 근거로 관찰 상태로 둡니다. 현재 가격 상승을 곧바로 물리적 공급 차질로 해석하지 않습니다.',
    pressureSignals: [
      '전력망·데이터센터·전기화가 장기 구리 수요를 늘리고 있습니다.',
      '현재 프로젝트 파이프라인 기준 장기 공급 부족 전망이 제시됐습니다.',
      '신규 광산은 인허가부터 상업 생산까지 긴 시간이 필요합니다.',
    ],
    reliefSignals: [
      '신규 광산·재활용 설비의 상업 생산 시작',
      '정련 수수료와 거래소 재고의 정상화',
      '대체 소재와 구리 사용 효율 개선',
    ],
    uncertainties: [
      '장기 전망은 신규 프로젝트 승인과 수요 시나리오에 민감합니다.',
      '선물 가격은 재고뿐 아니라 달러·금리·투기 수요의 영향도 받습니다.',
    ],
    evidence: [
      {
        id: 'copper-iea-shortfall',
        label: '2035년 구리 공급 부족 전망',
        value: '30%',
        context: 'IEA가 현재 프로젝트 파이프라인을 기준으로 제시한 전망입니다.',
        asOf: '2025-05-21',
        sourceRef: 'iea-critical-minerals-outlook-2025',
        kind: 'official-data',
      },
      {
        id: 'copper-iea-demand',
        label: '2040년 구리 수요 증가',
        value: '+30%',
        context: 'IEA의 현재 대비 장기 수요 전망입니다.',
        asOf: '2025-05-21',
        sourceRef: 'iea-critical-minerals-outlook-2025',
        kind: 'official-data',
      },
      {
        id: 'copper-world-bank-prices',
        label: '2026년 원자재 가격 전망',
        value: '+16%',
        context: 'World Bank 전체 원자재 지수 전망으로 구리 단일 가격 전망은 아닙니다.',
        asOf: '2026-04-28',
        sourceRef: 'world-bank-commodity-outlook-april-2026',
        kind: 'official-data',
      },
    ],
    sourceRefs: ['iea-critical-minerals-outlook-2025', 'world-bank-commodity-outlook-april-2026'],
    reportIds: ['iea-critical-minerals-outlook-2025', 'world-bank-commodity-outlook-april-2026'],
    marketMapIds: ['datacenter-power-cooling', 'semiconductor-cluster-infrastructure'],
    companyLinks: [
      { companyId: 'cluster-ls-electric', role: 'procurement-exposure', reason: '배전·전력기기 생산에 필요한 구리와 전선 원가·조달에 노출됩니다.' },
      { companyId: 'cluster-hyosung-heavy', role: 'procurement-exposure', reason: '변압기·전력설비 생산의 금속 조달과 납기에 노출됩니다.' },
      { companyId: 'us-energy-grid-nextera', role: 'demand-driver', reason: '전력망·발전 투자 집행이 구리 수요를 유발합니다.' },
    ],
    pickIds: ['pick-lg-electronics-ai-datacenter-cooling'],
    macroIndicatorIds: ['us-industrial-production', 'us-building-permits'],
    asOf: '2026-04-28',
    reviewedAt: '2026-07-12',
  },
  {
    id: 'semiconductor-fab-infrastructure',
    slug: 'semiconductor-fab-infrastructure',
    title: '반도체 팹 전력·건설 인프라 관찰',
    shortTitle: '반도체 팹 인프라',
    category: 'industrial-infrastructure',
    status: 'watch',
    trend: 'stable',
    confidence: 'low',
    summary: '메모리 설비투자는 확대되고 있지만 부지·전력·기초공사 전체가 현재 병목이라는 직접 지표는 제한적입니다.',
    assessment: '장비 투자와 전력망 투자 필요성은 확인되지만 프로젝트별 착공·전력 인입·공정 납기의 최신 직접 자료가 부족해 제한적 신뢰도의 관찰 상태로 둡니다.',
    pressureSignals: [
      '300mm 메모리 장비 투자가 2026~2027년에 확대될 전망입니다.',
      '팹 증설은 전력 인입·용수·기초공사·전력설비를 동시에 요구합니다.',
      '전력망 투자 속도가 산업단지 신규 수요를 따라가야 합니다.',
    ],
    reliefSignals: [
      '산업단지 전력·용수 인입 공사의 준공',
      '팹 부지 착공과 장비 반입 일정의 정상 진행',
      '전력기기·기초자재 납기와 현장 인력 수급 개선',
    ],
    uncertainties: [
      '산업 장비 투자 전망은 개별 국내 팹 착공 일정과 동일하지 않습니다.',
      '직접 공급계약이 확인되지 않은 기업은 후보 관계로만 봅니다.',
      '부지·인허가·전력 인입 자료의 공개 시점이 프로젝트마다 다릅니다.',
    ],
    evidence: [
      {
        id: 'fab-semi-investment',
        label: '2026년 300mm 메모리 장비 투자',
        value: '$52B',
        context: 'SEMI가 제시한 세계 300mm 메모리 장비 투자 전망입니다.',
        asOf: '2026-06-29',
        sourceRef: 'semi-memory-fab-outlook-q2-2026',
        kind: 'industry-report',
      },
      {
        id: 'fab-semi-capacity',
        label: '2026년 300mm 메모리 생산능력',
        value: '4.1M',
        unit: 'wpm',
        context: 'SEMI의 월 웨이퍼 투입능력 전망입니다.',
        asOf: '2026-06-29',
        sourceRef: 'semi-memory-fab-outlook-q2-2026',
        kind: 'industry-report',
      },
      {
        id: 'fab-iea-grid-investment',
        label: '2030년 필요 전력망 투자',
        value: '+50%',
        context: 'IEA 세계 전력망 투자 전망이며 개별 팹 전력 인입 일정은 아닙니다.',
        asOf: '2026-02-06',
        sourceRef: 'iea-electricity-2026',
        kind: 'official-data',
      },
    ],
    sourceRefs: ['semi-memory-fab-outlook-q2-2026', 'iea-electricity-2026'],
    reportIds: ['semi-300mm-memory-2026', 'iea-electricity-2026'],
    marketMapIds: ['semiconductor-cluster-infrastructure', 'us-semiconductors'],
    companyLinks: [
      { companyId: 'ai-datacenter-asml', role: 'demand-driver', reason: '첨단 팹 장비 투자와 생산능력 확대의 직접 수요 축입니다.' },
      { companyId: 'cluster-dongyang-pile', role: 'procurement-exposure', reason: '팹·산업단지 기초공사 수요와 연결 가능하지만 직접 계약은 별도 확인합니다.' },
      { companyId: 'cluster-ls-electric', role: 'capacity-provider', reason: '산업단지 배전·전력설비 공급능력을 제공합니다.' },
      { companyId: 'cluster-hyundai-ec', role: 'capacity-provider', reason: '대형 산업시설 EPC와 기반시설 구축 역량을 확인합니다.' },
      { companyId: 'cluster-samsung-ct', role: 'alternative-supplier', reason: '첨단 산업시설 건설·EPC의 대체 공급 축입니다.' },
    ],
    pickIds: ['pick-dongyang-pile-semiconductor-cluster-infrastructure', 'pick-kcc-silicone-margin-asset-value'],
    macroIndicatorIds: ['us-manufacturing-utilization', 'us-building-permits'],
    asOf: '2026-06-29',
    reviewedAt: '2026-07-12',
  },
];
